### ISSUE TITLE
Als PO wil ik een goed User Experience (UX) plan

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#1]
zodat we in het scrum team weten wat de aanpak is. Het UX en procesteam weten wat ze moeten doen en de product owner weet wat ze kan verwachten. 
Fase 1: start interviews met eventuele aanpassingen in de spec's, user story's die gebruikt worden om te bouwen
Fase 2: plan om m.b.v. een demo te testen (feedback van stellen) zodat we zeker weten dat de applicatie goed is en we waarde toevoegen voor stellen en backoffice.

**Comment by JanWillemKooi** [comment]
Zowel stellen (burgers die net zijn getrouwd of willen gaan trouwen) en backofficemedewerkers (ambtenaren betrokken bij het trouwproces) moeten betrokken worden bij het samenstellen van het plan

**Comment by JeroenduC** [comment]
UX Plan is aan het begin van het project met Kunera gedeeld, en later met de rest van het team. Issue is (al lang) klaar. 

Helaas geen digitale versie van beschikbaar, dus niks om naar te linken.
