### ISSUE TITLE
Als UX-designer wil ik interviews met koppels inplannen

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#10]
- [ ] Done: Er zijn minimaal vijf interviews met koppels ingepland.

**Comment by JanWillemKooi** [comment]
Op welke termijn zijn deze interviews gepland? Kan je iets zeggen over de stellen? (jong, oud, zelfde/ verschillend geslacht, hertrouwd etc) Delen jullie de vragen en antwoorden ook hier op GitHub?

**Comment by JanWillemKooi** [comment]
Alle informatie over interviews is te vinden op:
https://github.com/VNG-Realisatie/huwelijksplanner/tree/master/documenten/gebruikersonderzoek/interviews
