### ISSUE TITLE
Als product owner wil ik een doorkijk in de development ontwikkeling trouwplanner tot mei

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#102]
zodat ik een goede inschatting kan maken qua MVP

Scenario's
- [x] Gebruik huidige front-end
- [x] Gebruik mijnApp
- [ ] Gebruik een hybride variant

**Comment by CMasselink** [comment]
Dit staat in review, wat kan ik reviewen?

**Comment by matthiasoliveiro** [comment]
Kan, het is alleen al opgeleverd aan Jan-Willem en Kunera die hadden het dinsdag nodig. Het is dus een beetje het paard achter de wagen spannen.

**Comment by JanWillemKooi** [comment]
Doorkijk is opgeleverd door Conduction met een inschatting van de hoeveelheid werk. Alle user story die zijn meegenomen hebben als label [ingeschat]. Aangezien hier ook een aantal vertrouwelijke elementen inzitten sluit ik deze user story hier af. Op de backlog zijn voldoende user story gerelateerd aan MVP om te voorkomen dat we de definitie van de MVP vergeten.
