### ISSUE TITLE
Als developer wil ik een aparte kubernetes dev omgeving voor Trouwplanner

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#121]
Zodat ik niet afhankelijk ben van andere omgevingen voor mijn gegevens en functionaliteit

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
In de Utrecht omgeving wordt al gebruik gemaakt van Kubernetes voor de proeftuin Zaakgerichtwerken, wellicht handig om te weten.

**Comment by rubenvdlinde** [comment]
Dat weten we, moeten we het hier nog wel regelen.
