### ISSUE TITLE
Als developer wil ik een aparte kubernetes test omgeving voor Trouwplanner

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#122]
Zodat ik niet afhankelijk ben van andere omgevingen voor mijn gegevens en functionaliteit

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by JanWillemKooi** [comment]
Wie kan de review uitvoeren? Op dit moment is alleen @rubenvdlinde gekoppeld.
