### ISSUE TITLE
Als developer wil ik dat andere services kunnen bevragen via NLX 

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#126]
Zodat ik loging conform het NLX stramien kan ontsluiten

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by JanWillemKooi** [comment]
Dubbel met #149. Hier sluiten.
