### ISSUE TITLE
Als UX-designer wil ik de interviews verwerken die zijn afgenomen om een eerste goede beeld te krijgen waar we waarde voor de gebruikers kunnen toevoegen

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#13]
- [ ] Done: Alle vijf de interviews zijn verwerkt en de bestaande personakoppels zijn aangepast. De Product Strategie is aangepast met nieuwe inzichten.

**Comment by JanWillemKooi** [comment]
Is het mogelijk om wat voortgang te zien in deze user story? Bijvoorbeeld door een verwijzing naar een documentje of afspraak in de US zelf. Dan krijgt de rest van het team een beetje een idee van wat er gebeurd.

**Comment by MichelleDautzenberg** [comment]
Uitgewerkte interviews, personas en inzichten zijn hier te vinden: https://github.com/VNG-Realisatie/huwelijksplanner/tree/master/documenten/gebruikersonderzoek
