### ISSUE TITLE
Als developer wil ik een overzicht van onze ontwikkelafspraken / way of working

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#131]
Zodat het duidelijk is hoe we dingen doen

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by matthiasoliveiro** [comment]
Way of working voor het techniek team aangepast en in de git gezet.
https://github.com/VNG-Realisatie/huwelijksplanner/blob/master/documenten/techniek/way%20of%20working.md

**Comment by matthiasoliveiro** [comment]
@CMasselink @JanWillemKooi @ThijsBroersen Request for review voor het bovenstaande

**Comment by CMasselink** [comment]
Ik heb wat aanpassingen gedaan

**Comment by JanWillemKooi** [comment]
Ik had al aanpassingen gedaan. Ik zou de common ground laag waarin een component zich gaat bevinden, duidelijk willen hebben. Maar misschien zijn dat de stellingen van hoe een component zich verhoudt tot andere componenten.
