### ISSUE TITLE
Als burger wil ik verschillende soorten huwelijk kunnen selecteren

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#140]
zodat ik kan kiezen tussen gratis, standaard, uitgebreid. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by JanWillemKooi** [comment]
Vanuit Kunera en de politiek wordt de suggestie van een flitshuwelijk ingebracht. Daar moet zeker toch refinement over heen.

**Comment by rubenvdlinde** [comment]
Oké, deze is wat heen en weer aan het schuiven. En hangt nu kennelijk op flits huwelijk. Hebben we daar inmiddels een definitie van? Of kunnen we er later één bedenken?

Ik kan me agile gezien ook voorstellen dat we nu even een prikkelend schot voor de boeg doen voor het flits huwelijke. 
- JIj en Partner
- Geen getuigen (doen we ballie ambtenaren voor)
- Geen locatie keuze (altijd ballie)
- Geen ambtenaar keuze (who ever er die dag zit)
-Geen datum keuze (we vertellen het als de akte klaar is, dan kan je gewoon langskomen conform normaal ballie model)
- Geen extra's
- Alleen voor mensen die 100% te checken zijn via automatisering (dus alle fammilie leden in brp, nooit buiten nederland gewoond etc)

Of dit juist is de volgende vraag, maar het zet wel even een stelling neer naar aanleiding waarvan het procces team de discusie kan voeren. En wij hebben het binnen een uur of wat gergeld.

Bovendien ook leuk naar de raad toe om te vertellen dat we er mee bezig zijn?

**Comment by rubenvdlinde** [comment]
@rjzondervan eventueel in te plennen als reqoustType afhankelijk van reactie Utrecht

**Comment by CMasselink** [comment]
@DdeBruijn @MichelleDautzenberg 
Verschillende type huwelijken kunnen toch al aangegeven worden? 
Het flitshuwelijk is meer productinrichting denk ik. 
Deze zou dan dicht kunnen?

**Comment by MichelleDautzenberg** [comment]
Eens. Dat zou volgens mij een extra product zijn om toe te voegen in de PDC. 
Ik neem hem mee voor onze discussie dinsdag met Kunera over de MVP ook. 

Maar wat mij betreft kan deze story op done. Mocht er dan een product voor flitshuwelijk moeten komen maken we daar een nieuwe US van.

**Comment by CMasselink** [comment]
Gesloten, functionaliteit is reeds gerealiseerd
