### ISSUE TITLE
Als developer wil ik duidelijkheid over de architectuur

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#145]
zodat ik een kader heb waar aan alle componenten getoetst kan worden.

**Comment by JanWillemKooi** [comment]
Wat is hier de user story? Is de architectuur niet duidelijk? Of moet er een architectuur gemaakt worden? En zoja, dat is dan de basis van het huidige werk? 
Kan deze concreter gemaakt worden?

**Comment by rubenvdlinde** [comment]
Volgensmij is de onderliggende vraag of we voldoende inzicht kunnen creëren voor bijvoorbeeld @CMasselink over de onderlinge verhouding van de componenten?.

**Comment by JanWillemKooi** [comment]
Eigenlijk heb ik nog steeds dezelfde vraag als bij de start van de sprint. Kan deze concreter gemaakt worden?
