### ISSUE TITLE
Als developer wil ik versie beheer

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#146]
zodat het duidelijk is wat er gebeurt op welke versie

Oplossingsrichting:
Elke sprint hogen we het (minor) versienummer van een gewijzigd component op.
We hanteren semantic versioning.

- [ ]  Dependecies toevoegen
- [ ] Api standaarden

**Comment by JanWillemKooi** [comment]
Hoe willen jullie dit inrichten? Gaat dit over versiebeheer op de ontwikkelstaat? Is dat niet standaard ingericht op de CI/CD pipe line?

**Comment by JanWillemKooi** [comment]
Hebben jullie een voorstel?

**Comment by rubenvdlinde** [comment]
Ja we waren van plan om versies aan te duiden met gittags, dan creëren we een samenhangend geheel van code. Echter heeft github deze week het concept van packadges geintroduceerd dus daar moeten we even induiken.

**Comment by matthiasoliveiro** [comment]
Even ter verduidelijking met versie beheer bedoelen we hoe verschillende versies van componenten met elkaar inter acteren. Denk hierbij aan dependencies.

**Comment by JanWillemKooi** [comment]
Wie kan hiervan de review doen? Kunnen we die persoon ook koppelen?
