### ISSUE TITLE
Als developer wil ik gebruikmaken van Travis

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#148]
zodat ik de CI kan inrichten

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
We doen dit tegenwoordig via github ci/cd dus dit ticket en dat is dan al weer geregeld dus dit ticket is niet meer relevant (en eigenlijk reeds uitgevoerd maar op een andere manier)
