### ISSUE TITLE
Als developer wil ik NLX geïntegreerd hebben

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#149]
zodat logging en audit trail goed geborgd is.

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [x] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [x] Voeg alle taken die nodig zijn voor de user story toe.

DoD
- [ ] ontsluiten via NLX
- [ ] bevragen via NLX

**Comment by MichelleDautzenberg** [comment]
In de Utrechtse omgeving werken we al met NLX, dus is al eea geconfigureerd.

**Comment by MichelleDautzenberg** [comment]
Is dit niet hetzelfde als #125  en #126

**Comment by rubenvdlinde** [comment]
Iedere omgeving heeft een eigen NLX configuratie en endpoint, dus we zullen dit voor trouwen apart moeten organiseren.

**Comment by CMasselink** [comment]
Volgens mij ook dubbel met #6 

Componenten via NLX ontsluitbaar maken zou denk ik onderdeel moeten zijn van DoD

**Comment by JanWillemKooi** [comment]
Dubbel met de onderstaande us. Deze heb ik gesloten met verwijzing naar deze #149 Hieronder de belangrijkste teksten 
#6 Als PO wil ik gebruik maken van NLX zodat we aansluiten bij de architectuur van Common Ground
#125 Als developer wil ik dat mijn services worden ontsloten via NLX Zodat ik loging conform het NLX stramien kan ontsluiten
#126 Als developer wil ik dat andere services kunnen bevragen via NLX Zodat ik loging conform het NLX stramien kan ontsluiten

**Comment by JanWillemKooi** [comment]
Vraag die ik heb is.
Op welke versies van de Huwelijksplanner is NLX van belang? 
Ik denk het volgende:
ontwikkelversie (nu nog niet, maar bij sprint 7 of 8 wel)
demoversies (niet van belang)
testversie voor MVP (zeker)
MVP (zeker)

**Comment by rubenvdlinde** [comment]
@JanWillemKooi ik denk dat je hier een punt hebt, dit is een prio voor de iets langere termijn. Daar wil ik wel twee kanttekeningen bij maken (hou die even in het achterhoofd)

- Het ontsluiten van services via NLX leid er vermoedelijk toe dat ze beter getest worden
- Er is een punt te maken voor het ondersteunen van andere commonground initiatieven vanuit een gemeenschaps-belang

**Comment by JanWillemKooi** [comment]
Is er ook iets te zeggen over de prioriteiten? Anders blijft deze us open tot dat de MVP wordt opgeleverd. Wat moeten we doen om deze uit te werken in taken en daar prio's aan toe te voegen?
