### ISSUE TITLE
Als developer wil ik de Huwelijksplanner laten draaien op Haven

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#150]
zodat dit in lijn is met de VNG strategie

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
@PatrickCastenmiller en @CMasselink wat mij betreft kan deze hier van de kaart omdat die nu in het CaaS porject zowiezo al wordt afgevangen

**Comment by CMasselink** [comment]
Dit is wat mij betreft implementatie. Mag wat mij betreft dicht.
@PatrickCastenmiller eens?

**Comment by PatrickCastenmiller** [comment]
Ja, mee eens.
