### ISSUE TITLE
Als medewerker wil ik inzage hebben in de volledigheid van een reservering

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#160]
zodat ik in één oogopslag zie of een reservering compleet is. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
@bbrands02 Gaat hier in stap 1 even om de schermen

**Comment by MichelleDautzenberg** [comment]
Voor deze userstory voldoende. Verdere uitwerking aan de hand van specifiekere userstories die met de medewerkers zijn opgesteld.
