### ISSUE TITLE
Als medewerker wil ik inzage hebben in mijn openstaande taken

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#161]
zodat ik de reservering kan behandelen vanuit de trouwplanner

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
@bbrands02 volgensmij hoort deze thuis in je schermen project

**Comment by bbrands02** [comment]
Reviewbaar op:
https://db.huwelijksplanner.online/babs/melding

met username: wiedanook
en wachtwoord: test22

**Comment by MichelleDautzenberg** [comment]
Volgens mij voor deze userstory voldoende. Gedetailleerdere uitwerking volgt in specifiekere userstories die met de medewerkers zijn bepaald.
