### ISSUE TITLE
Als medewerker wil ik inzage hebben in alle ingevulde gegevens bij een reservering

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#162]
zodat .....

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
Hier is wat op voorbereid in het dashboard wat we maandag als startpunt voor een discusie hierover zouden kunnen gebruiken

**Comment by rubenvdlinde** [comment]
@bbrands02 Gaat hier in stap 1 even om de schermen

**Comment by MichelleDautzenberg** [comment]
VOor deze userstory voldoende. Verdere uitwerking gebeurd adhv specifiekere userstories die met de medewerkers worden ogpesteld.
