### ISSUE TITLE
Als medewerker wil ik dat er structurele controle plaatsvind op de aanwezigheid en het resultaat van de melding bij een reservering.

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#166]
zodat ik het direct weet als de melding ontbreekt of deze negatief is.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by RickWildHoorn** [comment]
Melding moet ook inhoudelijk gecheckt worden. Gaat een eventuele eerdere melding bijvoorbeeld ook over dezelfde personen, is een melding niet langer dan 1 jaar geleden gedaan etc.

**Comment by CMasselink** [comment]
Is dubbel met #476
