### ISSUE TITLE
Als burger wil ik de mogelijkheid hebben om mijn reservering te wijzigen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#169]
- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by CMasselink** [comment]
We gaan deze ready maken samen met de vakspecialisten.

**Comment by CMasselink** [comment]
Dit vraagstuk komt in andere andere userstories al terug, daarom deze sluiten
