### ISSUE TITLE
Als procesteam wil ik het BPMN model van de afhandeling van de reservering vastleggen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#171]
zodat we op basis van dit model met elkaar het gesprek aan kunnen gaan en userstories kunnen opstellen. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by JanWillemKooi** [comment]
@MichelleDautzenberg of @RickWildHoorn Laten jullie iets zien rond deze user story bij de demo morgen?

**Comment by MichelleDautzenberg** [comment]
Staan op Github ter inzage. Worden in sessie van 4 december besproken.
