### ISSUE TITLE
Als burger wil ik extra's kunnen aanvragen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#182]
zodat ik dit direct kan doen. Denk aan trouwboekje, internationale akte, memorabilia. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
In principee zouden extra;s nu al ondersteund moeten zijn (teschnisch dan) de vraag is even hebben we een goede lijst van extra's waarmee we dit kunnen testen?

**Comment by matthiasoliveiro** [comment]
Ready for review!

**Comment by JanWillemKooi** [comment]
Technisch is dit mogelijk. Het procesteam moet nadenken wat inhoudelijke wenselijk is. Hiervoor wordt een nieuw issue aangemaakt door @rubenvdlinde

**Comment by MichelleDautzenberg** [comment]
Besproken tijdens designweek:

bij elke extra een keuze voor Ja of Nee (bijv. radiobutton), zodat inwoner bewust wel of niet voor een extra kiest.

**Comment by JanWillemKooi** [comment]
Door de uitbreiding van de user story is de prioriteit en de sizing veranderd. Moet opnieuw worden besproken.

**Comment by MichelleDautzenberg** [comment]
Dit kan al.
