### ISSUE TITLE
Als developer wil archive functionaliteit

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#187]
zodat zodat ik voldoe aan de archief wet en de AVG

**Comment by CMasselink** [comment]
Dit moeten we even vanuit een business perspectief gaan formuleren.

**Comment by rubenvdlinde** [comment]
Is dit inmiddels via #428 opgepakt @MichelleDautzenberg? en daarmee ready to sprint?

**Comment by MichelleDautzenberg** [comment]
dit issue behoeft refinement en slicing, omdat het meerdere functionaliteiten betreft:
- het kunnen archiveren van zaken en bijbehorende documenten (gebeurt door OpenZaak #220 #421 #428 )
- het kunnen vernietigen/overdragen van zaken en bijbehorende documenten (RM module voor nodig, is Contezza aan het maken voor Alfresco)
- het kunnen archiveren van verzoeken (of domeinspecifieke registraties) en bijbehorende documenten
-het kunnen vernietigen/overdragen van verzoeken en bijbehorende documenten (of domeinspecifieke registraties)

**Comment by MichelleDautzenberg** [comment]
To do: uitzoeken wat er gearchiveerd dient te worden.

**Comment by MichelleDautzenberg** [comment]
Ik heb deze gesliced en sluit daarmee deze userstory.
