### ISSUE TITLE
Als beheerder wil ik kunnen inloggen (authenticatie) en wil daar beheerders rechten (autorisatie) toegewezen krijgen

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#190]
zodat ik beheer werkzaamheden kan doen. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

Deze user story beschrijf een inlog pagina voor beheerders. Andere user story's beschrijven verdere functionaliteiten die via dit scherm uitgevoerd kunnen worden.

**Comment by rubenvdlinde** [comment]
Is de beheerder een medewerker van een gemeente of kan dat ook een externe zijn?

**Comment by rubenvdlinde** [comment]
@bbrands02 dit zou in fase 1 even gaan om schermen

**Comment by CMasselink** [comment]
@rubenvdlinde @bbrands02 De schermen hiervoor zijn al gemaakt toch?

**Comment by CMasselink** [comment]
Inlogfunctionaliteit bestaat al.
