### ISSUE TITLE
Als trekker van de werkgroep Implementatie wil ik de bezetting van mijn team op orde hebben

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#193]
zodat we in staat zijn om te starten met het creëren van userstories die van belang zijn voor de implementatie (van het MVP)

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [x] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [x] Voeg alle taken die nodig zijn voor de user story toe.

- [x] Benodigde rollen benoemd
- [ ] Namen en rugnummers
- [ ] Eerste afspraak inplannen om afspraken te maken
- [ ] Bevestigen afspraken met managers via PO

**Comment by JanWillemW** [comment]
Met Henk van Dijkhuizen deelnemers besproken. Nu nog namen aan koppelen

**Comment by JanWillemW** [comment]
per ongeluk gesloten

**Comment by matthiasoliveiro** [comment]
@JanWillemW is dit issue nog relevant? Ik zet hem nu even op de backlog
