### ISSUE TITLE
Als PO wil ik een duidelijk huwelijksproces hebben

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#2]
zodat duidelijk is voor de inhoudelijke mensen vanuit de praktijk hoe de huwelijksplanner aansluit op het huidige proces

**Comment by JanWillemKooi** [comment]
- Het huidige proces moet goed in kaart gebracht worden

- Het gewenste proces moet goed in kaart gebracht worden

**Comment by DdeBruijn** [comment]
Voor mijn gevoel is deze niet klein genoeg voor 1 sprint en niet duidelijk wat 'het huwelijksproces' is. Reserveren? Melding? Wijzigen en/of Annuleren? Van start tot einde of slechts een deel?

**Comment by rubenvdlinde** [comment]
@MichelleDautzenberg en @DdeBruijn is dit inmiddels niet gerealiseerd met de BPM schema's?

**Comment by MichelleDautzenberg** [comment]
Ja, lijkt me wel. Processchema's gemaakt en met zijn alle besproken en akkoord bevonden. Er zijn al genoeg userstories voor de subprocessen waar nog extra info nodig is. Ik sluit deze.
