### ISSUE TITLE
Als Scrumteam wil ik een goede demo beschikbaar hebben

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#20]
DOD

- [ ] aan de hand van huidige app
- [ ] stabiel
- [ ] geen gekke data
- [ ] geen foutenmeldingen
- [ ] aparte omgeving voor "klooien"

**Comment by CMasselink** [comment]
Demo als in sprint review of als in "demo omgeving"?

**Comment by JanWillemKooi** [comment]
Op 12 november staan Kunera en ik op de tweede netwerkbijeenkomst 'Samen organiseren'. Wij krijgen een marktkraam bestaande uit een statafel met stroompunten. Er worden ongeveer 50 deelnemers verwacht. Ik heb met Matthias gesproken over hoe we dit vorm kunnen geven. Hij gaf aan al veel te hebben, en dat een demo omgeving ook nuttig is, voor anderen zoals het UX-team. Op korte termijn hebben we voor 12 nov in elk geval iets nodig.

**Comment by CMasselink** [comment]
Dan is deze user story dubbel met #75 toch?

**Comment by JanWillemKooi** [comment]
> 
> 
> Dan is deze user story dubbel met #75 toch?

#75 is specifiek voor 12 nov. Deze user story is bedoeld voor een demo die ook bruikbaar is voor bijvoorbeeld UX team. Misschien kan deze zijn als #75. Daar moeten we het over hebben tijdens de sprint.
