### ISSUE TITLE
Testdata inlezen in dev/test/acc omgeving

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#211]
De testdata gemaakt door het proces team moet worden in de omgevingen (dev test acc demo)

- [x] Check op volledigheid
- [x] Verrijking data set met verplichte gegevens
- [x] Geautomatiseerd data set inlezen.

**Comment by matthiasoliveiro** [comment]
Test persona's Helmond ontvangen en beoordeeld

**Comment by matthiasoliveiro** [comment]
@Ollie-nl @JeroenduC @MichelleDautzenberg @DdeBruijn @RickWildHoorn 

Onderstaande XLS kan gebruikt worden voor testdata. Let op deze XLS moet worden ingelezen worden bij het BRP component om zo bruikbaar te zijn als testdata. Verder zijn er nog wat beperkingen aangezien er wat data in deze sheets staan die niet uit het BRP komen of op een andere manier in het BRP staan. Hier moeten we nog een goeie oplossing voor verzinnen.

[PersonaGegevens.xlsx](https://github.com/VNG-Realisatie/huwelijksplanner/files/3968746/PersonaGegevens.xlsx)

Notities op de kleuren:
- Blauwe kolommen worden niet gebruikt door het BRP-component, maar worden wel gebruikt voor de spacing van de spacing van de gebruikte kolommen
- Donkergroene kolommen zijn verplichte kolommen die zonder verdere notitie kunnen worden gebruikt
- lichtgroene kolommen zijn niet-verplichte kolommen die zonder verdere aanpassing gebruikt kunnen worden|
- Oranje kolommen zijn verplichte kolommen met aantekeningen:
* Roepnaam: voorstel om aan te passen naar voornamen, gezien deze kolom ook wordt gebruikt voor voorletters
* Geboortedatum: let op met formatting, zorg dat het jaartal altijd vier cijfers heeft
* Huisnummer: voer hier geen huisnummertoevoegingen in

**Comment by DdeBruijn** [comment]
Hij is erg herkenbaar van de eerste versie van de testdata die er was.
Deze was echter achterhaald door een latere versie die ook gecheckt in in de GBA_V.
Die vind je op https://github.com/VNG-Realisatie/convenant-gemeenten/blob/master/Documents/Testdata/Partnerdataset_Def.xlsx

**Comment by matthiasoliveiro** [comment]
Heel herkenbaar, we kunnen deze informatie ook kwijt in deze excel. We moeten alleen samen even afstemmen wat het doel is van de testdata (wat wil je testen). We hebben nu er een manier voor om het te faciliteren. Als we meer functionaliteit moeten toevoegen dan zijn dat nu kleine toevoegingen.

**Comment by DdeBruijn** [comment]
We hebben de velden gekozen op basis van de wettelijke checks, dus onder curatele, geen huidige verbinding, soort verbintenis. Volgens had Thijs al iets van logica hierop bedacht. Hier zaten nog wel een aantal aannames in die nog niet waren getest, zoals dat een verbintenis die beëindigd was 2 gevulde velden had etc.

**Comment by JeroenduC** [comment]
Bestand aangepast en met Matthias gekeken hoe deze het beste is aan te leveren. Voor nu tot de conclusie gekomen dat dit met een handmatige actie het beste te doen is. Het aanbieden van een manier om meer testdata rondom persona's makkelijker te kunnen uploaden/aanpassen kan als nieuwe user story worden aangemaakt.

**Comment by JanWillemKooi** [comment]
@JeroenduC Is deze user stroy nu done? Dat mag deze ook naar die kolom gesleept worden
