### ISSUE TITLE
Als UX Team willen we de waardes uitwerken die we uit interviews gehaald hebben zodat het hele team beslissingen kan nemen op waardes

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#214]
- [ ] Workshop voorbereiden (veel output, weinig discussie)
- [ ] Uitnodigen deelnemers
- [ ] Uitvoeren workshop
- [ ] Digitaliseren resultaten workshop
- [ ] Prioriteren waardes
- [ ] Terugkoppelen aan Product Owner

**Comment by JeroenduC** [comment]
Deze Sprint krijgen we het voorbereiden van de workshop af, de andere taken nog niet.

@JanWillemKooi, en @Kunera

**Comment by JanWillemKooi** [comment]
Houden jullie de voortgang ook bij door de vinkjes te zetten?

**Comment by JanWillemKooi** [comment]
Is er al iets af van het lijstje aan het begin van de user story?

**Comment by matthiasoliveiro** [comment]
@JeroenduC is dit issue nog relevant? Ik zet hem voor nu op de backlog

**Comment by MichelleDautzenberg** [comment]
@JeroenduC Ik sluit deze. Voor de nieuwe interviews moeten we wat specifiekere userstories maken.
