### ISSUE TITLE
Als ontwikkelaar wil ik een Casco demo omgeving gaan opleveren

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#215]
zodat ik de testdata kan plaatsen #211 

- [ ] Systeem test uitgevoerd
- [ ] Acceptatie test uitgevoerd

**Comment by JanWillemKooi** [comment]
Is deze niet ook al in review aangezien #211 in review is?

**Comment by PatrickCastenmiller** [comment]
Is achterhaal, daarom sluitend.
