### ISSUE TITLE
Als developer willen we ZGW api's gaan herbruiken

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#220]
Dit moet ready gemaakt worden

**Comment by rubenvdlinde** [comment]
Aangezien we inmiddels zijn begonnen met het koppelen van zgw lijkt het me handig als deze ready wordt gemaakt :)

**Comment by matthiasoliveiro** [comment]
We pakken hem vraaggestuurd op.
