### ISSUE TITLE
Als PO wil ik overzicht in afhankelijkheid van issues

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#221]
Hoe in GitHub kan je dit overzicht verschaffen?
Onderzoek/ oplossing

**Comment by matthiasoliveiro** [comment]
Github is niet ideaal in het gebruik voor een PO. Het beste wat op dit moment kan doen is via epics overzicht verschaffen. Zie issue #234

**Comment by JanWillemKooi** [comment]
GitHub is inderdaad hierin niet geweldig. Bij Haal Centraal wordt gebruik gemaakt voor een zogenaamde Goalcanvas in Excel. Ook niet ideaal. Misschien een keer met de PO bespreken. Voor dit moment vind ik de aanpak in #218 en #234 voldoende
