### ISSUE TITLE
Als developer wil ik dat de feedback van het NLX team wordt verwerkt op de omgevingen

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#224]
zodat we bug vrij zijn.

Loadbalancing moet op een andere manier. Docker heeft hier intern  een oplossing voor.

**Comment by JanWillemKooi** [comment]
Wie moet reviewen?

**Comment by JanWillemKooi** [comment]
Wie moet reviewen?
