### ISSUE TITLE
Als inwoner wil ik een seintje krijgen als ik mijn melding mag doen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#228]
zodat ik dit niet vergeet. 
Reservering mag mogelijk al langer dan een jaar vantevoren, maar melding mag wettelijk pas een jaar vantevoren gemaakt worden. Zie ook #166 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Op het moment dat men een melding mag doen, een signaal naar de inwoner(s). Dat is dus een jaar vóór het huwelijk. 

Daarna periodiek een herinnering, dus bijvoorbeeld:
1.	1 jaar voor het huwelijk:	Eerste signaal “U mag nu de melding doen”.
2.	Iedere maand daarna:		Herinnering “U mag nu de melding doen”.
3.	4 weken voor het huwelijk:	Laatste (dringende) herinnering.

Zodra de melding gedaan is, hoeft er uiteraard geen herinnering meer verstuurd te worden.

**Comment by CMasselink** [comment]
Dubbel met #141
