### ISSUE TITLE
Als Scrumteam willen we een expertise groep met de naam Techniekteam met een doelstelling

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#23]
zodat voor iedereen duikdelijk is, wie met techniek bezig is en hoe dat aansluit op het geheel.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by JanWillemKooi** [comment]
Doel Techniekteam is: realiseren van Trouwplanner applicatie. Software development

In de groep zitten:
Thijs Broersen
Matthias Oliveiro
Ruben van der Linde
Constantijn Masselink

**Comment by matthiasoliveiro** [comment]
> zodat voor iedereen duikdelijk is, wie met techniek bezig is en hoe dat aansluit op het geheel.
> 
> * [ ]  Zorg dat de beschrijving duidelijk voor iedereen in het team is
> * [ ]  Koppel de juiste labels
> * [ ]  Let er op dat de user story in 1 sprint gerealiseerd kan worden

Dit zijn niet 123 taakjes die we kunnen afronden. Dit hoort meer thuis in een (technische) Definition of Done

**Comment by JanWillemKooi** [comment]
Dank @matthiasoliveiro voor je toevoeging. Het was mijn bedoeling om te organiseren dat de expertise groepen zouden nadenken over hun eigen scope en verantwoordelijkheden. Zonder dat dit nu echt is opgeschreven heb ik het idee dat deze user story geen bijdrage doet aan het verder verhelderen. Ik ga deze afsluiten en naar done slepen.
