### ISSUE TITLE
Als medewerker wil ik voor een inwoner de reservering kunnen wijzigen en annuleren (scherm) 

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#231]
zodat ik dit kan doen in situaties dat de inwoner dit niet zelf kan of meer mag doen. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
@bbrands02 volgensmij hoort deze thuis in je grote schermen verhaal

**Comment by MichelleDautzenberg** [comment]
Waar kan ik dit reviewen?

**Comment by bbrands02** [comment]
@MichelleDautzenberg Op https://dev.db.huwelijksplanner.online/babs/medewerker/huwelijk zit rechtsboven in een "Afkeuren" knop dat eigenlijk hetzelfde is als annuleren maar dan vanuit het beeld van de medewerker. Deze kan hernoemd worden als dat onduidelijk is.

**Comment by MichelleDautzenberg** [comment]
Ja ik vind Afkeuren en Annuleren nog wel 2 verschillende dingen. 

Bij Afkeuren heb je een reden om het huwelijk niet door te laten gaan en wil je dit waarschijnlijk ook ergens goed documenteren (Bijv. in de opmerkingen). Daarnaast wil je dat hier een goed afhandelingsproces achter zit waarin je aangeeft waarom je de reservering afgekeurd hebt en wat de consequenties daarvan zijn (kosten, vervolgreserveringen ed).

Bij Annuleren zal het eerder vanuit de inwoner komen die belt dat het toch niet doorgaat. En dan wil je een ander afhandelingsproces waarin duidelijk wordt bevestigd dat alles geannuleerd is en wat eventuele consequenties daarvan zijn (kosten ed.)

Mijn voorstel zou dan ook zijn om zowel een knop Afkeuren als een knop Annuleren te hebben.

**Comment by bbrands02** [comment]
@MichelleDautzenberg Ja duidelijk, misschien is het dan inderdaad beter om 3 knoppen te hebben,  annuleren, afwijzen, en goedkeuren. En dan bij annuleren en afwijzen een verplicht invoerveld te zetten waar de medewerker een reden kan opgeven voor het annuleren/afwijzen.

**Comment by MichelleDautzenberg** [comment]
Ja, dat lijkt me de beste oplossing!

**Comment by bbrands02** [comment]
Reviewbaar op https://dev.db.huwelijksplanner.online/mock/medewerker/huwelijk

**Comment by MichelleDautzenberg** [comment]
Ik vind hem mooi!
