### ISSUE TITLE
Als procesteam ik de processen klaar maken om uitgevoerd te kunnen worden door een proces engine

### ISSUE THREAD

**Issue by RickWildHoorn** [VNG-Realisatie/huwelijksplanner#233]
zodat .....

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by RickWildHoorn** [comment]
#79

**Comment by DdeBruijn** [comment]
Gesloten omdat de beslissing is genomen dat er geen proces engine gaat worden ingezet omdat dit momenteel niet realistisch is binnen de huidige planning.
