### ISSUE TITLE
Als developer wil ik het Digispoof component common ground proof maken

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#237]
Het digispoof component is een development tool die het mogelijk maakt om te testen als of je digid hebt. Om te kunnen blijven werken met de andere componenten is het belangrijk dat dit component in lijn blijft lopen met de andere componenten. Hier voor moet het door de "wasstraat" te halen.

Taken lijst todo:
- [ ] Architectuur afstemming
- [ ] Ontwerp gegevens model
- [ ] Realisatie
- [ ] Postman testscripts
- [ ] Documentatie Redoc
- [ ] Testscripts aan leveren aan testvoorziening
- [ ] Voorbeeld implementatie
- [ ] Code opleveren in Utrecht repo

Checklist Definition of done
- [ ] Oas documentatie
- [ ] Postman scripts (test scripts)
- [ ] Aangeleveren testscripts aan de api test voorziening
- [ ] Containers moeten gepubliceert zijn
- [ ] Gereviewd op de design decisions
- [ ] Voorbeeld implementatie beschikbaar
- [ ] Redoc moet beschikbaar zijn
- [ ] Documentatie moet beschikbaar zijn op github-pages
- [ ] NLX integratie moet werken

**Comment by rubenvdlinde** [comment]
Even voor de duidelijkheid, dit is een puur technisch verhaal dan. Er word geen norm toegepast over ander datamodel etc. Het gaat er puur om dat de api en functionaliteit up te date is.

Wel zou ik hem graag iets meer configurabel maken in de trand van data bronnen, dan denk ik met name aan het selecteren van databronnen (dus welk brp gebruik je, of welke dataset etc) ivm mocken en gebruiekrs reizen.

**Comment by matthiasoliveiro** [comment]
Dit is een mock service dus ik vraag me af of de DoD hier net zo strikt is.

**Comment by CMasselink** [comment]
Ik kan dit moeilijk reviewen (is er een api spec beschikbaar?). We hebben nu volgens mij een werkend digispoof component. Is inderdaad een mock, dus common ground proofness is op dit moment niet zo relevant / geen prio.

**Comment by CMasselink** [comment]
@PatrickCastenmiller eens om deze te sluiten?

**Comment by PatrickCastenmiller** [comment]
Voor nu werkt het. Het lijkt me inderdaad geen prioriteit. 
Wel de vraag hoe we de drempel voor de aansluiting op DigiD bij implementatie zo laag mogelijk kunnen maken.

@CMasselink sluiten lijkt me prima.

**Comment by CMasselink** [comment]
Zoals besproken, gesloten, geen core component
