### ISSUE TITLE
Als developer wil ik het Locatie component common ground proof maken

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#238]
Voor dit component stellen wij het volgende voor op Schema.org bestaat de standaard Place voor het Locatie object wat de basis is van dit component kan zijn.

Organisatie | Standaard | URL
-- | -- | --
Schema.org | Place | https://schema.org/Place

Taken lijst todo:
- [ ] Architectuur afstemming
- [x] Ontwerp gegevens model
- [x] Realisatie
- [x] Postman testscripts
- [x] Documentatie Redoc
- [ ] ~Testscripts aan leveren aan testvoorziening~
- [x] Voorbeeld implementatie
- [ ] Code opleveren in Utrecht repo

Checklist Definition of done
- [x] Oas documentatie
- [x] Postman scripts (test scripts)
- [ ] ~Aangeleveren testscripts aan de api test voorziening~
- [x] Containers moeten gepubliceert zijn
- [ ] Gereviewd op de design decisions
- [x] Voorbeeld implementatie beschikbaar
- [ ] Redoc moet beschikbaar zijn
- [ ] ~Documentatie moet beschikbaar zijn op github-pages~
- [x] NLX integratie moet werken

**Comment by rubenvdlinde** [comment]
Naar aanleiding van wat @CMasselink ook al op slack zij, er is ook een https://schema.org/Accommodation en (om mezelf eens te qouten) https://schema.org/docs/hotels.html norm. Ik voel er zelf veel voor om daar het hotels voorbeeld te volgen. Als ik dat zo lees is het niet mega complex (3 objecten ipv 1) en de gedachten er achter rechtvaardigen dan ook wel echt dat je een apart locatie component gebruikt. Die zou je dan zowel kunnen relateren aan PDC (product) als AgendaComponent (resource) en dan heb je de datazet eigenlijk rond. Zonder dat je dingen echt overhoop trekt

**Comment by matthiasoliveiro** [comment]
- Test voorziening geeft niet thuis en kunnen we niet afronden.
- Github pages is een strech goal en een nice to have, we hebben het nu ander opgelost via de readme (zie tabel)
- NLX hebben we een andere afspraak voor gemaakt en wordt los opgepakt. Het component is NLX ready maar het staat nog niet aan dat is een andere story

**Comment by CMasselink** [comment]
@rubenvdlinde  Waar zijn de verplichte velden bij het creëren van een accomodation op gebaseerd? Verplichte velden moeten afgestemd zijn op hetgeen we nu bij een locatie vastleggen, ik weet niet of daar nu een mismatch mee is. Je bent bijvoorbeeld verplicht om een product in te voeren. Dat betekent dat je geen locaties/ruimtes op kan voeren waarbij je nog niet weet wat voor producten je daar wilt aanbieden, dat lijkt me wat onhandig.
NumberofBathrooms lijkt me ook wat overbodig.

![afbeelding](https://user-images.githubusercontent.com/39768984/74234510-3d611280-4ccd-11ea-9a0e-feec02152928.png)
Geselecteerde linkjes kloppen niet.

Kloppen deze datatype aanduidingen? Is het datatime of een string geformateerd als datetime?
![afbeelding](https://user-images.githubusercontent.com/39768984/74234640-9c268c00-4ccd-11ea-8da0-656e4e63900c.png)

**Comment by rjzondervan** [comment]
@CMasselink De totalNumberOfBathrooms-property is een property die vanuit de Schema.org standaard naar voren kwam. Ik kan me voorstellen dat je deze wat overbodig vindt, maar er zijn situaties te bedenken waarin deze property wel nuttig kan zijn, ook wanneer we in de toekomst externe locaties toe willen kunnen voegen.

De string <date-time> aanduidingen betekenen dat het component een string als datetime geformatteerd verwacht, dit wordt dan intern in een DateTime-object omgezet.

Voor wat betreft de verplichte velden geeft @matthiasoliveiro mij aan dat dit zo is opgehaald bij de specialisten, mocht dit niet meer kloppen dan moet er even worden gekeken wat de consequenties zijn.

**Comment by CMasselink** [comment]
@rjzondervan als de mensen die de locaties straks moeten beheren, deze velden verplicht willen maken, vind ik het uiteraard prima. Dan ga ik er ook van uit dat deze informatie, zoals de oppervlakte en het aantal toiletten standaard bij deze mensen aanwezig is...

**Comment by CMasselink** [comment]
@DdeBruijn @MichelleDautzenberg Zien jullie kans bovenstaande met de backoffice medewerkers te verifiëren? 
Het gaat om alle velden die hier als required staan aangegeven: 
https://lc.huwelijksplanner.online/#operation/postAccommodationCollection

**Comment by rubenvdlinde** [comment]
Oke inmiddels is boventafel waar dit vandaan komt, er worden een aantal variabelen niet gezet op de kubernetes omgevingen. Omdat de openapi.yaml locaal wordt gemaakt verklaard dat ook met het verschil. Er is inmiddels een fix voor (variale zetten) en die moet over alle deployments worden uitgerold.

**Comment by MichelleDautzenberg** [comment]
Ik heb de vraag uitgezet bij de informatieadviseur van BZ, maar ik verwacht niet heel snel antwoord gezien de werkdruk nu daar.

**Comment by matthiasoliveiro** [comment]
Deze staat nu ook op demo kan iemand even checken of dat klopt? zo ja dan is even de vraag wat we met dit issue gaan doen.

**Comment by MichelleDautzenberg** [comment]
Hoe kan ik dit checken @matthiasoliveiro
