### ISSUE TITLE
Als procesteam en UX team willen we een sessie organiseren om wireframes te maken obv van de procesmodellen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#254]
zodat de techniek hiermee aan de slag kan. 

- (Minstens) 2 uur.
- We gebruiken het inwonersproces. (blokjes daaruit)

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by RickWildHoorn** [comment]
Deze nemen we mee in de planning, die maken we tijdens de sprintwissel op woensdag 15 januari.

**Comment by RickWildHoorn** [comment]
Zal mogelijk op donderdag in de _Designweek_ plaatsvinden. Nog niet definitief.

**Comment by MichelleDautzenberg** [comment]
UX moet de gehele planner gaan bekijken. Een sessie gaat niet afdoende zijn, daarom sluit ik deze.
