### ISSUE TITLE
Als developer wil ik het order component door de wasstraat halen

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#256]
Zodat het component voldoet aan de common ground normen en internationale standaarden

Voor dit component stellen wij de Schema.org standaard voor de volgende objecten voor: 
- Order 
- OrderItem 

Wij stellen het Order-object voor als de logische basis voor dit component, en het OrderItem-object als dependency van het Order-object

Organisatie | standaart | URL
-- | -- | --
Schema.org | Order | https://schema.org/Order
Schema.org | OrderItem | https://schema.org/OrderItem

Taken lijst todo:
- [ ] Architectuur afstemming
- [ ] Ontwerp gegevens model
- [x] Realisatie
- [ ] Postman testscripts
- [x] Documentatie Redoc
- [ ] ~Testscripts aan leveren aan testvoorziening~
- [x] Voorbeeld implementatie
- [ ] Code opleveren in Utrecht repo

Checklist Definition of done
- [x] Oas documentatie
- [ ] Postman scripts (test scripts)
- [ ] ~Aangeleveren testscripts aan de api test voorziening~
- [x] Containers moeten gepubliceert zijn
- [ ] Gereviewd op de design decisions
- [x] Voorbeeld implementatie beschikbaar
- [x] Redoc moet beschikbaar zijn
- [ ] ~Documentatie moet beschikbaar zijn op github-pages~
- [X] NLX integratie moet werken

**Comment by matthiasoliveiro** [comment]
- Test voorziening geeft niet thuis en kunnen we niet afronden.
- Github pages is een strech goal en een nice to have, we hebben het nu ander opgelost via de readme (zie tabel)
- NLX hebben we een andere afspraak voor gemaakt en wordt los opgepakt. Het component is NLX ready maar het staat nog niet aan dat is een andere story

**Comment by JanWillemKooi** [comment]
Paar vragen:
- Test voorziening: bedoel je het VNG API Testplatform? 
- Als er geen vinkjes zijn gezet bij ToDo en DoD, betekent dat, dat die dingen nog wel gedaan moeten worden? Anders zou ik ze uit de lijst halen.
- De opmerking over NLX houdt dit issue niet tegen om naar Done te gaan?

**Comment by CMasselink** [comment]
Het datamodel dat je via redoc kan openen, klopt niet. lijkt het datamodel van het PDC te zijn. Order en order item komen er niet op voor.

Bij orderitem zit een description. Hoe verhoudt dit attribuut tot description bij offer & bij product? Moet de description van een orderitem niet gewoon van een product overgenomen worden en niet nog een keer gedupliceerd bij orderitem?
![afbeelding](https://user-images.githubusercontent.com/39768984/74235259-de9c9880-4cce-11ea-899b-7aa54178c605.png)

Foute link verwijzingen:
![afbeelding](https://user-images.githubusercontent.com/39768984/74235552-90d46000-4ccf-11ea-897b-b64979ea88a4.png)

**Comment by rjzondervan** [comment]
Hoi Constantijn,

Het datamodel van het ordercomponent staat op dit moment nog in de dev-versie. De dev-versie van het component is alleen op dit moment niet gedeployed, dus hierbij een link naar het juiste datamodel: https://github.com/ConductionNL/orderregistratiecomponent/blob/development/api/public/schema/datamodel.pdf 
Als dit model akkoord is kunnen we het beschikbaar maken in de productieversie.

De description in OrderItem is verder een optioneel veld dat is meegenomen omdat we de afspraak hanteren dat in principe elke entiteit minimaal een name en description heeft.

**Comment by rjzondervan** [comment]
Hier is de algemene vraag een beetje of we dit issue nog separaat moeten reviewen, gezien er voor de losse componenten ook aparte issues zijn.

**Comment by CMasselink** [comment]
Akkoord. Met als generiek restpunt de URL verwijzingen naar de repository en docker container. En de foutieve URL verwijzingen in de voorbeeld URLs (zijn al andere userstory's van)
![image](https://user-images.githubusercontent.com/39768984/76246285-ab9de400-623d-11ea-917e-16355d154d2d.png)
