### ISSUE TITLE
Als developer wil ik een webresource component

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#259]
zodat het mogelijk is om op de user interface content aan te kunnen passen (teskten foto's kleuren etc)

**Comment by rubenvdlinde** [comment]
Hiermee bedoelen we dus voor via databse ipv van code waardoor we tekstuele aanpassingen kunnen doen zonder deploy. Is dus handig voor de design week (snelheid, meteen wijzigingen laten zien)
