### ISSUE TITLE
Als Scrumteam willen we een gedeelde Product Visie hebben

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#26]
zodat we allemaal een gemeenschappelijk beeld hebben van wat het project gaat brengen.

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
 
TAKEN

- [x] Product visie staat op de Readme,md pagina 
- [ ] akkoord Rene Olling
- [ ] akkoord Jeroen du Chantinier
- [ ] akkoord Dewi Delhoofen
- [ ] akkoord Daphne de Bruijn
- [ ] akkoord Rick Wildenberg
- [ ] akkoord Michelle Dautzenberg
- [ ] akkoord Thijs Broersen
- [ ] akkoord Matthias Oliveiro
- [ ] akkoord Ruben van der Linde
- [ ] akkoord Constantijn Masselink
- [x] akkoord Jan Willem Wooderink
- [ ] akkoord Henk van Dijkhuizen
- [x] akkoord Patrick Castenmiller
- [x] Kunera van den Belt
- [x] akkoord Jan Willem Kooi

**Comment by JanWillemKooi** [comment]
Tijdens de start op 23 oct kwamen twee opmerkingen over de huidige product visie naar voren:
- Waarom staat er 'zo geen mogelijk concessies aan CG" en niet "geen concessies aan CG"
- De burgers moeteen meer centraal staat in de product visie.

**Comment by JanWillemKooi** [comment]
Zet jullie voorstellen, opmerkingen en aanpassingen in deze user story.

**Comment by CMasselink** [comment]
@JanWillemKooi Ik had je laatste comment niet gelezen, ik heb een pull request van mijn wijzigingsvoorstellen gemaakt: #139

**Comment by JanWillemKooi** [comment]
Voor wie pull request ingewikkeld vindt, hierbij de voorstellen van @CMasselink :

Product visie:
Met de huwelijksplanner realiseren we componenten (zowel registratiecomponenten als gebruikersinterface) waarmee gemeenten een goed werkend trouwproces kunnen inrichten waarmee de burger ontzorgd wordt bij het plannen van een huwelijk. De huwelijkplanner wordt zo snel mogelijk gefaseerd in productie gebracht bij 1 of meerdere gemeenten. We ontwikkelen de huwelijksplanner conform de visie en principes van common ground en willen met de huwelijksplanner actief bijdragen aan samen organiseren. 

Doel:
* Inwoners in staat stellen om snel en eenvoudig vanaf de bank hun huwelijk te regelen.
* Backoffice van gemeenten die bij het huwelijksproces betrokken zijn, te ontlasten

**Comment by JeroenduC** [comment]
Voorstel: 

**Productvisie**
Een product opleveren dat waarde toevoegt voor de mensen die een geregistreerd partnerschap willen aangaan.

**Randvoorwaarden:**
-We ontwikkelen de huwelijksplanner conform de visie en principes van common ground.
-De huwelijksplanner wordt zo snel mogelijk gefaseerd in productie gebracht bij 1 of meerdere gemeenten.
-We werken samen met meerdere gemeenten aan de huwelijksplanner.

**Comment by JanWillemKooi** [comment]
@JeroenduC Persoonlijk vind ik het voorstel van Constantijn wat beter in de zin dat het concreter beschrijft wat we willen doen. 
Jullie hebben echter aangegeven dat je 'waarde toevoegen' in de product visie wil zien. Hoe zou dat in die van Constantijn kunnen?

**Comment by JanWillemKooi** [comment]
Versie van Kunera

Product visie:
Met de huwelijksplanner realiseren we componenten (zowel registratiecomponenten als gebruikersinterface) waarmee gemeenten een goed werkend trouwproces kunnen inrichten. Daarmee wordt waarde toegevoegd voor de burger en daarmee ontzorgd wordt bij het plannen van een huwelijk. De huwelijkplanner wordt zo snel mogelijk gefaseerd in productie gebracht bij 1 of meerdere gemeenten. We ontwikkelen de huwelijksplanner conform de visie en principes van common ground en willen met de huwelijksplanner actief bijdragen aan samen organiseren.

Doel:

    Inwoners in staat stellen om snel en eenvoudig vanaf de bank hun huwelijk te regelen.
    Backoffice van gemeenten die bij het huwelijksproces betrokken zijn, te ontlasten
