### ISSUE TITLE
Als developer wil ik een berichten component

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#260]
zodat het mogelijk is om berichten te sturen naar gebruikers van de trouwplanner.

Functionaliteiten
-standaard berichten (templates)

**Comment by rubenvdlinde** [comment]
Volgensmij bestaat deze inmiddels :) Er is wel nog een ander los issue over de implementatie ervan

**Comment by CMasselink** [comment]
@rubenvdlinde welk issue is dat? 
Ik zoek ook even naar een manier hoe ik deze userstory kan reviewen.
Het berichtencomponent voldoet overigens nog niet helemaal aan DoD:
Net zoals bij alle andere componenten kloppen onderstaande verwijzingen niet:
![afbeelding](https://user-images.githubusercontent.com/39768984/74029890-05e12600-49ae-11ea-8a75-218d56966084.png)

**Comment by CMasselink** [comment]
@rubenvdlinde je refereert naar #291 denk ik?

**Comment by CMasselink** [comment]
Berichten werken nu

**Comment by CMasselink** [comment]
Berichten werken ook op demo
