### ISSUE TITLE
Als developer wil ik een Dashboard component

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#261]
zodat het makkelijk mogelijk is om dashboards in te stellen. Denk hierbij bijvoorbeeld aan dashboards om locaties toe te voegen.

**Comment by rubenvdlinde** [comment]
Voor nu is dit even 80% out of scope, daarvoor zijn meer user stories met de juiste prio nodig vanuit de beheerders en gebruikers groepen. Maar onder water weten we natuurlijk dat er een dashboard moeten komen. 

Sterker nog dat is er nu al gedeeltelijk en zit in de huidige applicatie, met het uit elkaar trekken van de applicatie zou het dan ook wat mij betreft logisch zijn om de bestaande dashboarden even te “parkeren” in een eigen aplicatie. Dus laten we dit timeboxen in de trand van voorbereiden wat nodig en logisch maar niet ontwikkelen met als doel af. Dat verdient een eigen sprint in gemeenschap met andere teams.

**Comment by rubenvdlinde** [comment]
Volgensmij bestaat deze inmiddels :)

**Comment by rubenvdlinde** [comment]
Uit de backlog voorbereiding geghaald omdat die in de huidige sprint op reviews staat, van naar @MichelleDautzenberg verplaats omdat Jan-Willem druk is

**Comment by MichelleDautzenberg** [comment]
True, ik sluit deze (deployen ook al gebeurd)
