### ISSUE TITLE
Als procesteam willen we Huub Westendorp betrekken

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#27]
zodat we aansluiten op de landelijke ideeen over (micro)processen en architectuur keuzes.

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by JanWillemKooi** [comment]
Deze suggestie kwam van Kunera.

**Comment by CMasselink** [comment]
Ik denk graag mee over architectuurkeuzes rond processen.

**Comment by RickWildHoorn** [comment]
Afspraak staat gepland voor 9 december.
Rick/Daphne/Michelle
