### ISSUE TITLE
BUG: Digispoof zit nog niet op https

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#272]
en geeft in browsers terecht een waarschuwing

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by matthiasoliveiro** [comment]
Digispoof, zelf zit op HTTPS de fout treed op in de return URL.
Dus:

1. Ga naar de huwelijks planner
2. login via digispoof
3. Digispoof stuurt je terug naar de huwelijksplanner. Hier treed de fout op bij firefox.

**Comment by CMasselink** [comment]
Heb je een suggestie hoe ik deze user story kan hernoemen?

**Comment by matthiasoliveiro** [comment]
> Heb je een suggestie hoe ik deze user story kan hernoemen?

De titel is technisch correct, het duurde even voor dat ik hem gereproduceerd had.

**Comment by rubenvdlinde** [comment]
Deze blijkt in extreme gevallen blocking voor testing dus pakken we vandaag op als hotfix

**Comment by rubenvdlinde** [comment]
Deze is gehotfixed, @CMasselink wil jij hem reviewen en dien akoord sluiten?

**Comment by CMasselink** [comment]
@rubenvdlinde Getest en opgelost bevonden.
