### ISSUE TITLE
Als medewerker wil ik een tijdelijke API key op de API's

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#274]
als tijdelijke oplossing tot we autorisatie/authenticatie goed hebben ingericht, zodat testdata beschermd is.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
Quick win zou hier wat mij betreft zijn om even een vaste api key te zetten, op termijn willen we natuurlijk de zgw authorisatie componenten hanteren.  Dus laten we er op letten geen dubbel werk te doen.

**Comment by rubenvdlinde** [comment]
Deze is randvoorwaardelijk voor #291 , en aangezezien die is ingepland trek ik deze even mee.

**Comment by CMasselink** [comment]
@rubenvdlinde is deze nu niet al gerealiseerd?

**Comment by rubenvdlinde** [comment]
Tsjechisch wel, maar in de drukt nog niet uitgerold over alle omgevingen. Maar defacto komt deze elke keer mee als we een component "aanraken"

**Comment by rubenvdlinde** [comment]
@CMasselink  Oke ik heb dit nu voor alle componenten klaar staan, maar..... dat vraagt het deployen van alle componenten op alle omgevingen. Das niet zo zeer veel werk (yeay dev straat) maar wel tricky omdat we morgen willen demoen.

Mijn voorstel is dan ook om dit naar donderdag ochtend te verplaatsen.

Ik heb het al wel voor het wrc al aangepast, dus tis al wel testbaar. (je kan met postman een get doen op https://wrc.huwelijksplanner.online/templates en dan krijg je een auth error) en daar kom je alleen langs met de juiste aut header (die ik een niet op github zal zetten)

**Comment by CMasselink** [comment]
Lijkt me goed om dit op een moment te doen dat er geen demo wordt gegeven of actief gereviewed wordt. Maar wel ASAP omdat er veel getest wordt.

**Comment by CMasselink** [comment]
@rubenvdlinde ik neem aan dat ik kan reviewen? Kan je mij via Slack de API key sturen?
Een call via de browser levert trouwens deze melding op bij het locatie component:
![afbeelding](https://user-images.githubusercontent.com/39768984/76196262-381eb700-61ea-11ea-96bc-8658f452c7d8.png)

**Comment by CMasselink** [comment]
@rubenvdlinde Review resultaten:
Get request op locatiecomponent levert een error 500 op. Kan dus niet testen of authenticatie voor dit component werkt.
Er zit geen API key op medewerkerscomponent.
Er lijkt geen API key op VTC te zitten.
Agendacomponent op https://ac.huwelijksplanner.online/ levert een 502 bad gateway op dus kan ik niet testen.
Er lijkt geen authenticatie op BRP component te zitten: https://brp.huwelijksplanner.online/ingeschrevenpersonen
Er lijkt geen authenticatie op instemmingen te zitten: https://irc.huwelijksplanner.online/assents

Voor de pagina's die een 500 melding geven, zal ik een bug aanmaken. Voor de componenten waar nog geen authenticatie op zit, zit nog werk voor deze userstory denk ik?

**Comment by CMasselink** [comment]
Update: Agenda component is weer online dus heb ik ondertussen kunnen testen. Er lijkt op het agenda component ook geen authenticatie te zitten.

**Comment by rubenvdlinde** [comment]
Dit is een deploy verhaal, zie ook #438 die tevens een deploy van de componenten afdwingt. We gaan deze er ergens vandaag weer doorheen halen.

**Comment by CMasselink** [comment]
Alle componenten gecontroleerd. Kan naar deploy

**Comment by rubenvdlinde** [comment]
Zullen we hem dan ook naar depoly zetten ;)

**Comment by CMasselink** [comment]
Had ik nog niet gedaan vanwege een vraag in Slack. Jij hebt hem nu in done gezet, alles is nu dus gedeployed?
