### ISSUE TITLE
Als project team wil ik een "slim" dashboard voor de design week

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#276]
Zodat we redelijk eenvoudig wijzigingen kunnen doorvoeren op de objecten en op de front-end

- [ ] Dashboard pagina's creëren voor alle entiteiten van alle componenten
- [ ] Front-end op hakken in te beheerbare delen voor op het Dashboard 
- [ ] Dashboard Initial setup
- [ ] Dashboard eerste logica
- [ ] Weergeven verzoeken
- [ ] bewerken templates
- [ ] bewerken css
- [ ] bewerken applicaties
- [ ] bewerken verzoeken
- [ ] Weergeven en bewerken ambtenaren
- [ ] Weergeven en bewerke locaties
- [ ] Weergeven en bewerken agendas
- [ ] Weergeven en bewerken producten
- [ ] Verder abstraheren slimme commonground service

**Comment by matthiasoliveiro** [comment]
Zo als afgesproken op 9 januari

**Comment by PatrickCastenmiller** [comment]
een van de activiteiten is in " Front-end op hakken in te beheerbare delen voor op het Dashboard".  Graag een toelichting op deze activiteit. waarom is deze nodig? 
welke informatie MOET aanpasbaar zijn door de gebruiker.

**Comment by PatrickCastenmiller** [comment]
het gaat om het kunnen maken van aanpassingen. Er is geen beheerproces nodig.

**Comment by PatrickCastenmiller** [comment]
wat betekent "Verder abstraheren slimme commonground service"

**Comment by matthiasoliveiro** [comment]
> een van de activiteiten is in " Front-end op hakken in te beheerbare delen voor op het Dashboard". Graag een toelichting op deze activiteit. waarom is deze nodig?
> welke informatie MOET aanpasbaar zijn door de gebruiker.

Dit houd in bewerkbaar maken van de templates in het dashbord. Niet het ophakken van de trouwplanner

**Comment by MichelleDautzenberg** [comment]
@PatrickCastenmiller kan je deze gesloten?

**Comment by PatrickCastenmiller** [comment]
Kan gesloten worden. Er is in de designweek gewerkt met een dashboard. Deze is achterhaald. De ontwikkeling is al verder.
