### ISSUE TITLE
Vergelijk datamodellen van convenant gemeentes met vigerende data modellen in de huwelijks planner

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#277]
Het doel van deze story is verschillen identificeren tussen de datamodellen van de convenant gemeenten en de huidige huwelijksplanner. Verschillen zullen leiden tot een afweging wat er mee te doen.

**Comment by CMasselink** [comment]
Wat wordt met deze userstory precies bedoeld?

**Comment by PatrickCastenmiller** [comment]
Deze moet specifieker gemaakt worden. Welk product levert dit op, welke informatiemodelen gaat het over

**Comment by matthiasoliveiro** [comment]
Het doel van deze story is verschillen identificeren tussen de datamodellen van de convenant gemeenten en de huidige huwelijksplanner.

**Comment by CMasselink** [comment]
Voorstel: we kijken vanuit de huidige inrichting of we een proces kunnen afronden en daarbij alle informatie kunnen opslaan die nodig is voor het plannen en verwerken van een huwelijk.

**Comment by CMasselink** [comment]
Deze userstory heeft nog geen prio. Er staan in todo nog userstories die een hoge prio hebben, die eerst oppakken. 
De verwachting is dat uit het uitvoeren van de processen aan de voorkant (vanuit inwonerperspectief) en vanuit de backoffice eventuele missende gegevens ook aan het licht gaan komen.

**Comment by rubenvdlinde** [comment]
Denk dat we sowieso wel missende data tegen zullen komen maar hier hebben mensen natuurlijk voorwerk op geleverd dus dan is het wel zo netjes er even naar te kijken. 

Dat gezegd hebben is dit inderdaad niet de hoogste prio nee. 

Datasets staan trouwens op
https://github.com/VNG-Realisatie/huwelijksplanner/tree/master/documenten/datasets_CG

**Comment by CMasselink** [comment]
Ik ben al even gaan vergelijken en het levert ook best wel weer aardige keuzes op:
In de convenant gemeenten dataset over BABS'en wordt bijvoorbeeld vastgelegd wanneer iemand beëdigd is. 
Vraag 1: waarom is deze informatie nodig?
Vraag 2: waar leggen we deze informatie vast? Voelt wat raar om dat bij product op te slaan...
De vraag is ook waar we namen, geboortedatum etc zouden moeten vastleggen. Er is voor medewerkers volgens mij geen doelbinding om een BSN vast te leggen. Ophalen via haalcentraal gaat dus niet. Opslaan bij product babs is niet logisch.
Telefoonnummer staat bijvoorbeeld ook niet in de BRP.
Als we al deze gegevens nodig hebben, lijkt het me logischer om deze gegevens in het medewerkers component op te slaan.

**Comment by CMasselink** [comment]
We sluiten deze userstory, mochten er meer attributen nodig hebben, dan moet het komen vanuit functionele userstory's

**Comment by rubenvdlinde** [comment]
Als deze is gesloten hoort die volgensmij niet op de backlog ;)
