### ISSUE TITLE
Vergelijken BPMN processen met werking huwelijks planner

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#278]
Toets de huwelijksplanner op de bestaande processen van utrecht en convenant gemeenten

**Comment by PatrickCastenmiller** [comment]
Wat is hiervan het doel? wat hebben we hierna meer dan nu?

**Comment by matthiasoliveiro** [comment]
Het doel, hier van is het testen van de processen met de werking van de huwelijksplanner.

**Comment by matthiasoliveiro** [comment]
Is gedaan! en niet echt te reviewen
