### ISSUE TITLE
Als productowner wil ik verifiëren of alle oorspronkelijke userstories van zowel Utrecht als de Convenantgemeenten zijn meegenomen in het nieuwe project

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/huwelijksplanner#28]
zodat .....

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by JanWillemKooi** [comment]
Taken:
- [ ] Team techniek. Alle US's vanuit Convenant + Utrecht oude proj.  zijn meegenomen
- [ ] Team UX. Alle US's vanuit Convenant + Utrecht oude proj.  zijn meegenomen
- [ ] Team proces. Alle US's vanuit Convenant + Utrecht oude proj.  zijn meegenomen
- [ ] Team Implementatie: Alle US's vanuit Convenant + Utrecht oude proj.  zijn meegenomen
- [ ] Team Scrum: Alle US's vanuit Convenant + Utrecht oude proj.  zijn meegenomen
- [ ] Team Regie. Alle US's vanuit Convenant + Utrecht oude proj.  zijn meegenomen

**Comment by JanWillemKooi** [comment]
Hier staat alle user story's uit het Convenant project als .json file. Handig voor de mensen die geen toegang tot de Trello hebben. 

https://github.com/VNG-Realisatie/huwelijksplanner/blob/master/documenten/archief/AlleUserStory'sVanConvenantGemeente.json

**Comment by JanWillemKooi** [comment]
Zie ook #69
