### ISSUE TITLE
Als inwoner wil ik met een 'home' knop terug naar de homepagina kunnen zodat ik snel verder kan navigeren door de huwelijksplanner

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#282]
Als ik nog niet ingelogd ben en aan het navigeren ben door de verschillende pagina's zou ik verwachten dat ik (ook) via het logo linksboven terug kan naar de beginpagina.

**Comment by JeroenduC** [comment]
Browser: Edge 44
OS: Windows 10

**Comment by MichelleDautzenberg** [comment]
Dubbel met #388
