### ISSUE TITLE
Als inwoner wil ik de juiste prijs zien bij de kosten voor de types trouwen zodat ik weet wat ik kan verwachten

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#285]
Bij de prijzen die getoond worden bij bij de keuze voor het type trouwen staat de punt niet goed. Er staat nu 1.63 bij eenvoudig trouwen, het lijkt mij dat dat 163 moet zijn.

**Comment by JeroenduC** [comment]
Browser: Chrome79
OS: Windows 10

**Comment by rubenvdlinde** [comment]
Komt door het twee keer delen door 100

**Comment by JanWillemKooi** [comment]
Getest tijdens design week.
