### ISSUE TITLE
Als lid van het huwelijksplannerteam wil ik Digispoof ook in Edge 44 kunnen gebruiken zodat ik kan testen

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#286]
Met Digispoof inloggen in Edge44 op Windows 10 lukt niet. Bij chrome is er geen probleem.

Browser: Edge 44 (En Chrome 79)
OS: Windows 10

**Comment by rubenvdlinde** [comment]
Hey @JeroenduC zou je deze kunnen herttesten, en indien opgelost kunnen afsluiten. Als het goed is dan is dit probleem inmiddels verholpen.

**Comment by JeroenduC** [comment]
Hertest, probleem komt niet meer voor. Issue gesloten.

**Comment by rubenvdlinde** [comment]
Thanxs
