### ISSUE TITLE
Als inwoner wil ik niet per ongeluk een trouwdatum kunnen kiezen in het verleden 

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#287]
Het is mogelijk om op 17-1-2020 een trouwdatum te kiezen op 8-5-1990.

**Comment by JeroenduC** [comment]
Browser: Chrome 79
OS: Windows 10

**Comment by rubenvdlinde** [comment]
Verplaatsen van de kalender code is hiervoor randvoorwaardelijk

**Comment by CMasselink** [comment]
> 
> 
> Verplaatsen van de kalender code is hiervoor randvoorwaardelijk

Wat bedoel je hiermee?

**Comment by rjzondervan** [comment]
Dit ging om een stuk javascript dat op een locatie stond waar het niet dynamisch bewerkt kon worden. Dit is inmiddels verplaatst naar een bewerkbare locatie.

**Comment by rjzondervan** [comment]
Inmiddels de oplossing gevonden en online gezet. @JeroenduC zou je willen valideren dat de datepicker op dit punt doet wat je verwacht?

**Comment by JeroenduC** [comment]
Ik kan in de datepicker niet meer met de muis kiezen voor een datum die al geweest is.

Tijdens het hertesten ben ik er wel achter gekomen dat na het kiezen en bevestigen van een datum de datum niet 'onthouden' wordt door het datum scherm. Stappen:

1) Kies datum. (testgeval 29-02-2020)
2) Bevestig. Ik wordt doorgestuurd naar het 'locatie' scherm.
3) Ga terug naar het datum scherm.

Verwacht resultaat: de eerder gekozen datum, 29-02-2020 wordt weergegeven.
Daadwerkelijk resultaat: De datum staat op 'vandaag' (op het moment van schrijven 04-02-2020).

**Comment by rjzondervan** [comment]
Dankjewel! De nieuwe bug die je noemt was ook al gemeld in #398, waarvoor inmiddels een oplossing gevonden is, maar die nog moet worden uitgerold.

**Comment by rjzondervan** [comment]
@JeroenduC zou je willen controleren of dit nu is opgelost?

**Comment by JeroenduC** [comment]
@rjzondervan 

An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in __string_template__8f6d85cda129665948faf9a854e83cf387b584cebc1fb5338b5faf4583c0671e at line 81.

**Comment by rjzondervan** [comment]
Is dat bij het openen van de datumpagina of een andere pagina?

**Comment by rjzondervan** [comment]
@JeroenduC De fixes zijn nu op productie beschikbaar. Zou je hem nogmaals willen hertesten? Wel het verzoek om dit in een nieuw verzoek te doen, want het kan zijn dat oude verzoeken een storing veroorzaken.

**Comment by JeroenduC** [comment]
Hertest vanuit een nieuw verzoek. Niet mogelijk om een datum te kiezen in het verleden.
