### ISSUE TITLE
Als inwonwer wil ik na het toevoegen van een getuige gemakkelijk nog een getuige kunnen toevoegen

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#289]
Als een inwoner een getuige heb uitgenodigd dan wordt ik vanzelf doorgestuurd naar de volgende stap. Als ik al een lijstje met getuigen heb die ik wil toevoegen moet ik een stap terug.

Browser: Chrome 79
OS: Windows 10

**Comment by rubenvdlinde** [comment]
Dubbel met #305

**Comment by JanWillemKooi** [comment]
Getest. Bevinding: gekozen getuigen zijn niet zichtbaar.

**Comment by JeroenduC** [comment]
Eens dat dit dubbel is met #305. Op Done gezet.
