### ISSUE TITLE
Als inwoner wil ik zien wie ik als getuigen heb uitgenodigd en wat de status daarvan is zodat ik vertrouwen heb dat het goedkomt

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#290]
Er is nu na het uitnodigen geen overzicht van uitgenodigde getuigen. Een overzicht van wat er verstuurd is en wat de status daarvan is geeft mij vertrouwen dat het proces in gang is gezet. 

Browser: Chrome 79
OS: Windows 10

**Comment by rubenvdlinde** [comment]
In theorie staat dit op de checklist, maar getuigen zouden ook meteen moeten worden toegevoegd worden aan de getuigen pagina

**Comment by rubenvdlinde** [comment]
De technische bug hiervan zit al in #305

**Comment by JeroenduC** [comment]
Alhoewel de informatie er al staat, vind ik hem bijna niet leesbaar voor de gebruiker. Ik zou dan ook willen voorstellen de data op de manier zoals hieronder gewireframed weer te geven, zodat het een beetje overzichtelijker wordt.

![20200226_170133](https://user-images.githubusercontent.com/49227194/75363133-fb81c000-58b9-11ea-88d1-feeb49cee1b1.jpg)

Als onderstaande wireframe niet duidelijk is, laat het weten dan licht ik het graag toe.

**Comment by JeroenduC** [comment]
Ziet er al een stuk beter uit! Maar de velden Voornaam en Achternaam moeten niet getoond worden, die worden al weergegeven. 
![image](https://user-images.githubusercontent.com/49227194/76340771-68567a80-62fc-11ea-9f3b-63e5190d7609.png)

**Comment by JeroenduC** [comment]
Netjes! Getest op Dev, ziet er goed en overzichtelijk uit!

**Comment by JeroenduC** [comment]
Succesvol getest. Done.
