### ISSUE TITLE
Als developer wil ik de berichten service aan zetten

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#291]
zodat mails daadwerkelijk verstuurd en getest kunnen worden.

~~ Om goed voorbereid de DesignWeek in te gaan willen we de mogelijkheid hebben om de inwoner een e-mail notificatie te kunnen sturen naar aanleiding van een trigger (taak voltooid, tijd verlopen, etc.). 

Ook willen we het verstuurde bericht kunnen bewerken/aanpassen in HTML.

Nice to have: Notificatie ook verstuurbaar via SMS/Whatsapp/Facebook ~~

**Comment by matthiasoliveiro** [comment]
Dit is gereed we moeten het alleen even aanzetten op een opportuun moment.

**Comment by rubenvdlinde** [comment]
Zullen we dat dan deze week eens doen? Wel leuk voor het UX team ook om mee te kunnen spelen

**Comment by matthiasoliveiro** [comment]
Het issue is technisch gerealiseerd maar staat nu om beveiligingsredenen uit. Als scrum team moeten we hier een keuze in maken.

**Comment by rubenvdlinde** [comment]
Eigenlijk is het enige wat dit issue nu groter maakt de hoeveelheid componenten waarvoor de apikey dan moet worden aangezet
