### ISSUE TITLE
Beveiligingswaarschuwing bij inloggen

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#293]
**Beschrijving van de bug**
Als ik inlog krijg in een beveiligingswaarschuwing.

**Wat heb ik gedaan**
Inloggen

**Verwachting**
Geen waarschuwing

**Bug**
De pop-up window met 
![afbeelding](https://user-images.githubusercontent.com/45660740/72973678-fe2a5a80-3dcd-11ea-84d4-f46b30de765d.png)

**Comment by CMasselink** [comment]
Is dubbel met #272

**Comment by rubenvdlinde** [comment]
Deze blijkt in extreme gevallen blocking voor testing dus pakken we vandaag op als hotfix

**Comment by rubenvdlinde** [comment]
Deze is gehotfixed, @CMasselink wil jij hem reviewen en indien akkoord sluiten?

**Comment by CMasselink** [comment]
@rubenvdlinde Getest en opgelost bevonden
