### ISSUE TITLE
Vreemde boodschap bij partnerschap

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#294]
**Beschrijving van de bug**
In het scherm bij Partnetschap staat een onduidelijke regel Status: granted

**Wat heb ik gedaan**
Geklikt op partnerschap na inloggen

**Verwachting**
Duidelijk scherm

**Bug**
Vreemde boodschap: Status granted Onduidelijk wat daarmee bedoeld wordt.
![afbeelding](https://user-images.githubusercontent.com/45660740/72973625-e521a980-3dcd-11ea-9b35-1cc027619a8d.png)

**Comment by rubenvdlinde** [comment]
Dit is weer gekoppeld aan translation

**Comment by rubenvdlinde** [comment]
Het kernprobleem hiervoor was dat translation dus niet goed werkte, dat is als het goed is loopt er nu een deploy waarin dit gefixed is (en dus ook de rij van issues waar die hier aan vast hangen) we houden even finger aan de pols en als het goed gaat zetten we deze op review :)

**Comment by rubenvdlinde** [comment]
![vertaling doet het](https://user-images.githubusercontent.com/4021899/75240198-43262000-57c4-11ea-8c06-8bce082ce601.PNG)

Top, lijkt het te doen :) Als er nu nog ergens onterecht Engels in staat ping dat vooral even aan want dan zijn we een translation vergeten.

**Comment by MichelleDautzenberg** [comment]
Duidelijker zo. Ik sluit deze!
