### ISSUE TITLE
De naam van partner verdwijnt nadat ik heb opgeslagen

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#298]
**Beschrijving van de bug**
Als ik een naam invul bij vraag uw partner ten partnerschap (in dat Nederland?) verdwijnt deze als ik op Opstaan druk

**Wat heb ik gedaan**
Als ik een naam invul bij vraag uw partner ten partnerschap (in dat Nederland?) verdwijnt deze als ik op Opstaan druk

**Verwachting**
Dat je ingetypte naam in beeld blijft. Zie ook bug #296

**Bug**
Ingevulde gegevens lijken te verdwijnen nadat je op Opstaan hebt geklikt.

**Comment by rjzondervan** [comment]
Bug hertest, en de volgende resultaten:
![image](https://user-images.githubusercontent.com/10433082/73349164-fb76ac00-428a-11ea-8671-603f66f647e7.png)
![image](https://user-images.githubusercontent.com/10433082/73349177-016c8d00-428b-11ea-8157-bad6655446a4.png)


Dit, voor alle duidelijkheid, zowel bij huwelijk als partnerschap. Naar mijn idee is de bug daarmee verholpen?

**Comment by JanWillemKooi** [comment]
Getest. Extra aanvulling
![afbeelding](https://user-images.githubusercontent.com/45660740/73466483-390a3080-4382-11ea-8812-3bb6d26e7555.png)

**Comment by rjzondervan** [comment]
E-mail en telefoonnummer worden nu weergegeven. @bbrands02 gaat nadenken over het toevoegen van een editknop zodat het formuliertje kan vervallen wanneer de contactgegevens ingevuld zijn.

**Comment by rjzondervan** [comment]
Editknop en formuliertjes zijn nu toegevoegd, het formulier aan de onderzijde van de pagina laat alleen nog de open velden zien.

**Comment by MichelleDautzenberg** [comment]
Beter, alleen blijft het envelopje nog staan, ook al heb ik mijn contactgegevens al doorgegeven. 

![image](https://user-images.githubusercontent.com/48316239/75249048-b4220380-57d5-11ea-87c4-ee5d44e853bc.png)

**Comment by rjzondervan** [comment]
Bovenstaande wensen zijn inmiddels verwerkt.

**Comment by MichelleDautzenberg** [comment]
Top! Ik maak nog een extra userstory om het knopje 'wijzig contactgegevens' toe te voegen.
