### ISSUE TITLE
De locatie wordt niet opgeslagen op het moment dat je voor de optie "inloggen om te reserveren" kiest.

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#302]
**Beschrijving van de bug**
Als je nog niet bent ingelogd, kan je verschillende locaties bekijken. Er is een knop met "log hier in om de locatie te reserveren". Als je vervolgens inlogt, wordt de locatie niet daadwerkelijk opgeslagen/geselecteerd.

**Wat heb ik gedaan**
Zorgen dat je niet ingelogd bent. Naar de locatie pagina gaan. Een locatie selecteren.  
Op de knop "log hier in om de locatie te reserveren" klikken en inloggen. Kiezen voor een nieuw verzoek. Naar de overzichtspagina/checklist pagina gaan: de locatie is niet opgeslagen 

**Verwachting**
De locatie die voor inloggen geselecteerd was, als opgeslagen/geselecteerd locatie bij locaties.

**Bug**
Locatie wordt niet onthouden

**Comment by rubenvdlinde** [comment]
Hoor bij #358

**Comment by JanWillemW** [comment]
Terug naar backlog. Oppakken nadat US #376** is opgepakt
