### ISSUE TITLE
Onduidelijk: Wanneer je niet bent ingelogd, zie je bij ceremonies, niet de keuzes simpel of uitgebreid trouwen.

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#303]
**Beschrijving van de onduidelijkheid**
Als je niet bent ingelogd, en bij de knop ceremonies kijkt, suggereert de tekst onder de knop ceremonies dat je meer informatie kan vinden over simpel of uitgebreid trouwen. 
![image](https://user-images.githubusercontent.com/39768984/73059130-55dfc900-3e95-11ea-99d0-5343f23ef2cb.png)
Je komt echter op een pagina waar het verschil tussen huwelijk en partnerschap staat.

**Wat heb ik gedaan**
Klik op ceremonies als je nog niet bent ingelogd. Je komt op een pagina uit waar informatie op staat over huwelijk en partnerschap maar waar geen informatie staat over de verschillende ceremonies (simpel en uitgebreid trouwen). 
![image](https://user-images.githubusercontent.com/39768984/73059297-b4a54280-3e95-11ea-85ea-715c6bdf08fe.png)

**Verwachting**
Op basis van de tekst had ik verwacht hier uit te komen:
![image](https://user-images.githubusercontent.com/39768984/73059477-1ebde780-3e96-11ea-81fa-0df2f8ea3b1b.png)

**Bug**
Ceremonies en plechtigheid worden in tekst en pagina's door elkaar gehaald

**Comment by matthiasoliveiro** [comment]
Na review blijkt dat de onduidelijkheid dieper zit dan alleen hier. We moeten als team een heldere lijn kiezen wat een plechtigheid is en wat een ceremonie is. Na aanleiding van deze keuze kunnen we de planner in lijn brengen.

**Comment by rubenvdlinde** [comment]
@bbrands02 als het goed is ka @matthiasoliveiro je meer vertellen over de textuele keuzes hier.

**Comment by CMasselink** [comment]
Akkoord, tekst is nu in lijn met de pagina waar je op uit komt.
