### ISSUE TITLE
Als burger wil ik niet helemaal naar beneden hoeven scrollen om weer terug naar het ambtenaren overzicht te gaan

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#304]
zodat ik sneller door de huwelijksplanner kan navigeren.
Als ik nu op de detail pagina van een trouwambtenaar klik, en ik daarna weer terug wil naar het overzicht met alle ambtenaren, is de terug knop niet zichtbaar maar moet je eerst naar beneden scrollen, nog onder het filmpje. 

Mogelijke oplossing: ook bovenin een knop "terug naar overzicht"

**Comment by rubenvdlinde** [comment]
In een bredere zin is er behoefte aan een menu voor niet ingelogde gebruiker en/of andere duidelijke manier van navigeren.

**Comment by JanWillemKooi** [comment]
Deze user story is getest echter er ontstond een brede discussie over UX. We hebben een groter vraagstuk over de gehele navigatie, vormgeven, flow, aanpassingen aan devices etc. Hier is een epic UX voor en user story  #377
