### ISSUE TITLE
Bij het toevoegen van een getuige, word ik na het opslaan doorgeleid naar de extra opties pagina ipv dat ik de bevestiging zie

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#305]
**Beschrijving van de bug**
Bij het toevoegen van een getuige, word ik doorgeleid naar de extra opties ipv dat ik de bevestiging zie en een volgende getuige kan uitnodigen. Ik heb nu voor maar 1 persoon een getuige geselecteerd en heb dus nog onvoldoende getuigen voor het voltrekken van een huwelijk. Toch ga ik naar de volgende stap.

**Wat heb ik gedaan**
Log in, doorloop alle stappen in volgorde van de knoppen. Selecteer een getuige voor persoon 1. Klik op "uitnodigen" onder aan de pagina. 

**Verwachting**
Bevestiging van uitnodiging maar wel op de getuigen pagina blijven.

**Bug**
Je wordt doorgeleid naar de extra opties pagina ipv dat je nog een getuige kan selecteren.

**Comment by CMasselink** [comment]
Dubbel met #289 ik laat hem nog even open omdat de omschrijving hier wat uitgebreider is.

**Comment by rubenvdlinde** [comment]
- Dit gesuggereerd dat extra optie pagina geen flash berichten weergeeft.  
- We moeten ook controleren wat er gebeurd met pas doorzetten bij vier getuigen

**Comment by CMasselink** [comment]
Het is redelijk een UX ding maar ik kan me voorstellen dat we niet meer automatisch naar de volgende stap gaan.
Bij het opslaan / uitnodigen zie je dan op de getuigen pagina een bevestiging van de actie die je net hebt uitgevoerd, in dit geval het toevoegen van een getuige. 
Je kan er dan voor kiezen om nog een getuige toe te voegen of naar de volgende stap te gaan.

**Comment by JanWillemKooi** [comment]
Na testen kan je meer dan 4 getuigen toevoegen.

**Comment by CMasselink** [comment]
@rubenvdlinde 
Nog niet akkoord:
Ik kan nu 2 getuigen voor dezelfde partner toevoegen en daarna wordt ik weer doorgeleid naar de extra pagina. Ik heb dan nog steeds niet een getuige voor elke persoon ingesteld. Ik voldoe daarmee nog steeds niet aan de voorwaarden: minimaal 1 getuige per persoon. 

Ik denk dat het handig is om bij getuigen het automatisch doorgaan naar de volgende stap, pas te doen nadat 4 getuigen zijn ingevuld, of helemaal niet.

**Comment by rjzondervan** [comment]
Hier is nu een oplossing voor gemaakt, deze vereist alleen een deploy die we niet een avond voor de sprintwissel gaan doen. Morgenmiddag of donderdag komt dit online. Dan tikken we jullie even aan.

**Comment by rjzondervan** [comment]
De oplossing voor dit issue is inmiddels uitgerold.

**Comment by CMasselink** [comment]
@rjzondervan De oplossing is op dev uitgerold. Daar is het correct. Issue pas sluiten als het ook in demo goed staat neem ik aan?

**Comment by MichelleDautzenberg** [comment]
Ik zet deze naar deploy, zoals afgesproken in laatste sprintwissel.

**Comment by CMasselink** [comment]
Opgelost. Je wordt nu niet meer doorgeleid.
