### ISSUE TITLE
Er komt geen groen vinkje bij het cadeau icoontje na het selecteren van een extra optie

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#306]
**Beschrijving van de bug**
Er komt geen groen vinkje bij het cadeau icoontje na het selecteren van een extra optie

**Wat heb ik gedaan**
Trouwboekje als extra geselecteerd

**Verwachting**
Een groen vinkje bij het cadeau icoontje in de knoppen balk

**Bug**
geen vinkje zichtbaar.

**Comment by rubenvdlinde** [comment]
Grappige is dat we nog een discussie open hebben staan over wanneer we daar een vinkje zetten, an zich is géén extra's namenlijk ook goed.

**Voorstel**
Bij het toevoegen van een extra OF drukken op de knop volgende locatie geven we een finkje.

**Comment by CMasselink** [comment]
Ja precies, de keuze "ik hoef geen extra opties" is ook een keuze.

**Comment by rubenvdlinde** [comment]
De vraag is even hoe, omdat we er niet op kunnen valideren als geen data is. We gaan hier even over nadenken.

**Comment by matthiasoliveiro** [comment]
De vraag hier is wanneer moet hier een groen vinkje komen en moet er wel een groen vinkje komen? Het is immers een optionele stap. Ik wil graag van UX en Proces hier een uitspraak over.

**Comment by MichelleDautzenberg** [comment]
Ik zou zeggen:

Een groen vinkje zodra je op Volgende klikt na het toevoegen van minstens één extra (meer mag altijd) OF kiezen voor de optie 'ik wil geen extra's' (is ook een keuze, dus te valideren toch?).

**Comment by matthiasoliveiro** [comment]
Het is inderdaad een keuze maar hoe leg je het vast? Als je namelijk later inlogt moeten we terug zoeken wat je keuze is. Op dit moment kijken we of er extra's zijn of niet. Als je geen extra's hebt dan kan het zijn dat je of nog niet gekozen hebt of ze niet wil. 
We kunnen het quick en dirty oplossen door een product aan te maken "Geen extra's" maar dat is wel heel erg misbruik maken van de functionaliteit.

**Comment by MichelleDautzenberg** [comment]
Besproken tijdens designweek:

bij elke extra een keuze voor Ja of Nee (bijv. radiobutton), zodat inwoner bewust wel of niet voor een extra kiest.

**Comment by CMasselink** [comment]
Opgelost, voor elk van de extra's komt er nu een groen vinkje
