### ISSUE TITLE
Ik kan niet inloggen vanaf de knop "log hier in om deze locatie te reserveren"

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#307]
**Beschrijving van de bug**
Ik kan op de demo-omgeving niet inloggen vanaf de knop "log hier in om deze locatie te reserveren". Als ik dan klik op inloggen word ik teruggeleid naar de homepage en wordt ik niet ingelogd. 

**Wat heb ik gedaan**
Zorg dat je niet ingelogd bent. Ga naar de infopagina van Locaties. Kies de Stadhuis kleine zaak. Klik op de knop 'Log hier in om deze locatie te reserveren'. Log in (any personage). Ik word nu terug naar de homepage geleid en ben niet ingelogd.

**Comment by rubenvdlinde** [comment]
Thanxs :)

Dit is in wezen dezelfde fout als die ook onder de inloggen knop in de menu balk staat, onderwerg naar digispoof verlies je https met als gevolg dat je bij terugkomt niet meer de applicatie in komt. 

De daar toegepaste oplossing moet hier (en bij ambtenaren) inderdaad ook worden toegepast.

**Comment by matthiasoliveiro** [comment]
#302 
Is gerelateerd maar beschrijft een andere situatie. Deze situatie gaat er over dat je "Land" waar je was gebleven. 302 gaat over het onthouden van gemaakte keuzes.

**Comment by rubenvdlinde** [comment]
Hoort bij #358
