### ISSUE TITLE
De knop "terug naar ambtenaren" geeft een foutpagina

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#308]
**Beschrijving van de bug**
Als je op een pagina van een ambtenaar op de knop terug naar ambtenaren klikt, krijg je een foutpagina.

**Wat heb ik gedaan**
Een ambtenaar selecteren zodat je op de detail pagina komt, daarna op de knop terug naar ambtenaren klikken.

**Verwachting**
Terug naar overzichtspagina

**Bug**
Foutpagina

**Comment by rjzondervan** [comment]
Dit issue treed ook op bij locaties. Fix is inmiddels gevonden
