### ISSUE TITLE
Ik verwacht een uitleg over simpel of uitgebreid trouwen achter de tegel Ceremonies 'simpel of uitgebreid' in plaats van het verschil tussen partnerschap en trouwen.

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#312]
**Beschrijving van de bug**
Tekst komt niet overeen met verwachting.

**Wat heb ik gedaan**
Geklikt op 'Lees meer' bij Ceremonies

**Verwachting**
Verschil tussen simpel en uitgebreid trouwen kunnen lezen. Bijvoorbeeld dat simpel alleen doordeweeks op dagen x en y kan en weekenden uitgebreid is etc.

**Comment by CMasselink** [comment]
@DdeBruijn deze is dubbel met #303

**Comment by DdeBruijn** [comment]
Dubbel met 303

**Comment by DdeBruijn** [comment]
> @DdeBruijn deze is dubbel met #303

Dank voor de bewaking ;)
