### ISSUE TITLE
Het gebruik van Status 'granted' en 'requested' is onduidelijk

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#316]
**Beschrijving van de bug**
Bij het inloggen en bij het instemmen komt er Status Granted of Status Requested in beeld te staan.
Het is onduidelijk wat dit betekent.

**Comment by rubenvdlinde** [comment]
Hier moeten we de translation op inregelen

**Comment by MichelleDautzenberg** [comment]
dubbel met #294
