### ISSUE TITLE
Als inwoner wil ik ook op een andere dag dan dinsdag kunnen trouwen

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#317]
zodat ik ook kan kiezen voor een andere dag.

Aanvullend:
Ik wil ergens inzichtelijk hoe de prijs mee veranderd als ik bijvoorbeeld een donderdag, vrijdag of zaterdag kies.

Bijvoorbeeld:
Dag en Tijd / Trouwzaal / Andere locatie

Maandag 9.00 en 9.30 uur (zie ook onderstaande informatie) | gratis | n.v.t.
Werkdagen 9.00, 10.00 en 11.00 uur | € 185,25 | € 317,55
Werkdagen 12.00, 13.00, 14.00, 15.00 en 16.00 uur | € 332,95 | € 465,25
Werkdagen 17.00, 18.00 en 19.00 uur | € 480,60 | € 612,90
Werkdagen op een ander tijdstip (in overleg met Burgerzaken) | niet mogelijk | € 1017,60
Zaterdag 11.00, 12.00, 13.00 en 14.00 uur | € 749,05 | € 881,35
Zaterdag op een ander tijdstip en locatie buiten stadhuis (in overleg met Burgerzaken) | niet mogelijk | € 1017,60
Toeslag bij huwelijk of geregistreerd partnerschap op locatie | 132,30 |  
Toeslag bij huwelijk of geregistreerd partnerschap op andere tijdstippen dan bovenstaande tijdstippen | € 268,55

**Comment by rjzondervan** [comment]
Dit wordt op dit moment geset in /api/public/js/dashboard.js. Om het dynamischer te kunnen maken is een andere locatie wellicht beter.

**Comment by DdeBruijn** [comment]
Andere dagen zijn nu te kiezen. Consequentie van dagen/tijden op prijs is nog niet zichtbaar.
@matthiasoliveiro @rubenvdlinde deze open houden of nieuwe US aanmaken hier specifiek voor?

**Comment by matthiasoliveiro** [comment]
@DdeBruijn dit is inderdaad een aparte US. Je gaat daar echt andere dingen doen dan dit issue beschrijft.

Excuus ik had deze even gemist.

**Comment by matthiasoliveiro** [comment]
#457 @DdeBruijn ik heb het issue gevonden!!!! Deze kan dicht.

**Comment by DdeBruijn** [comment]
Tijden en prijzen verplaatst naar #457
