### ISSUE TITLE
Na het inloggen van 2e partner blijft de pagina op instemmingsverzoek hangen en blijft Status op Requested staan. 

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#318]
**Beschrijving van de bug**
Als ik als 2e partner inlog kan ik het instemmingsverzoek accorderen. Er komt vervolgens in beeld te staan 'Status is bijgewerkt naar granted'. Dan word ik echter weer teruggeleid naar de instemmingspagina, waarbij de status nog steeds op requested staat. 

Ook wordt de bovenaan de pagina de tekst veranderd naar de naam van de 2e partner. Dit is erg verwarrend. Wie is er nu ingelogd? 
De tekst 'Beste John Willem de Kieft u bent ingelogd over een beveiligde verbinding, klik hier om uit te loggen' is na de instemming veranderd naar 'Beste Miley Sinclair u bent ingelogd over een beveiligde verbinding, klik hier om uit te loggen'

Als ik doorga met de stappen en bij Getuigen kom, zie ik dat de 2e partner niet in het lijstje voorkomt.

**Verwachting**
Mijn verwachting is dat je na het accorderen van je instemmingsverzoek naar de 'Hoe wilt u gaan trouwen' pagina verder wordt geleid.

Het gebruik van de status zou ik weglaten. En op een andere manier zichtbaar maken wie er nu ingelogd zijn.

**Comment by rubenvdlinde** [comment]
Dit gaat om het technische stuk, de onduidelijkheid zit hem in #296

**Comment by MichelleDautzenberg** [comment]
Voor deze userstory akkoord, mits #296 en #316 nog worden aangepakt.
