### ISSUE TITLE
Na december 2020 is er undefined 2020 in de kalender

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#319]
**Beschrijving van de bug**
Tussen december 2020 en januari 2021 is er een maand 'Undefined 2020'

**Wat heb ik gedaan**
Tijdens het scrollen in de kalender

**Verwachting**
Geen undefined maand

**Comment by JanWillemKooi** [comment]
Getest tijdens de design week
