### ISSUE TITLE
Als procesteam wil ik een proces beschrijven voor de situatie waarbij een medewerker de huwelijksplanner invult voor de inwoner

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#32]
Beschrijving van de taak:

Uitzoeken in welke situaties dit gebeurt en wat dit voor het proces betekent. 

Let op:
- [ ] duidelijke beschrijving wat moet gebeuren
- [ ] gekoppeld aan een persoon (assign)
- [ ]  gekoppeld aan een user story (door # en het nummer toe te voegen)

**Comment by CMasselink** [comment]
Wordt al opgelost met #484
