### ISSUE TITLE
Locatie modern & extern is niet vast te leggen in de huwelijksplanner

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#320]
**Beschrijving van de bug**
Wanneer ik klik op Modern of Extern kan ik niet opslaan in de pagina

**Wat heb ik gedaan**
Tijdens het selecteren van de locatie Modern of Extern kan ik niet opslaan

**Verwachting**
Knop voor opslaan of reserveer deze locatie zoals dit bij de anderen wel is.

**Comment by rjzondervan** [comment]
Modern en extern op de locatiepagina's zijn demofilters om locaties mee te filteren.
De locaties die we op dit moment in de testset hebben zitten zijn niet toegewezen aan deze filters.

De achterliggende contentvraag is hier: waar willen we op kunnen filteren?

**Comment by rubenvdlinde** [comment]
Deze vraag is al een keer geweest en beantwoord namenlijk locatie kenmerken, hiervan is ook een lijst opgesteld. Die zou kunnen worden opgehaald / verniewd maar denk daarbij aan rolstoeltoegankelijk, audio installatie etc.

@JanWillemW kan jij een lijst van kenmerken aanleveren?

**Comment by rubenvdlinde** [comment]
@bbrands02 deze kunnen we gewoon in stappen oppakken in ieder geval is hiervoor nodig in het dashboard.
- Overzicht producten
- Pagina product beweren
- Overzicht product kenmerken
- Pagina kenmerk bewerken

Vervolgens kunnen we zelf voorbeeld kenmerken inregelen en aan de hand daarvan de filters inregelen. Het aanleveren van definitieve kenmerken is dan even aan implementatie.

**Comment by DdeBruijn** [comment]
Toevoeging zou dan wel zijn, dat categorieën die leeg zijn niet worden getoond.

**Comment by DdeBruijn** [comment]
Staat in review maar categorieën worden nu helemaal niet meer getoond. Wat moet ik reviewen?

**Comment by matthiasoliveiro** [comment]
@DdeBruijn ik heb met @JeroenduC  hier even over gespard en UX wil graag dat deze filters niet zichtbaar zijn. Maw je kan dit niet testen en hij zou dicht kunnen.
