### ISSUE TITLE
Als inwoner wil ik kunnen aangeven dat ik geen voorkeur heb voor een ambtenaar

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#321]
zodat mijn voorkeur mijn datum of locatie niet beperkt.

**Comment by matthiasoliveiro** [comment]
Voorstel: We voegen een "Ambtenaar" met de naam  "Geen voorkeur" oid. Dit is een quick fix en zou mooier kunnen. Sizing is nu XS

**Comment by DdeBruijn** [comment]
Oplossing lijkt mij prima, ik zie hem echter in dev en prod niet terug.

**Comment by matthiasoliveiro** [comment]
Hertest op Dev mogelijk

**Comment by DdeBruijn** [comment]
Getest en akkoord. Nieuw issue gemaakt over tekstueel dingetje voor UX #464
