### ISSUE TITLE
Ik kan maar voor één partner getuigen toevoegen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#322]
**Beschrijving van de bug**
Ik ben ingelogd als John Willem Kieft en als Kevin Ross. Ik heb alle stappen doorlopen, tot ik bij Getuigen kwam. Daar kan ik alleen voor Kevin Ross een getuige toevoegen (andere partner is niet zichtbaar in het lijstje 'voor partner').

**Comment by rubenvdlinde** [comment]
Als je bij de checklist kijkt heb je dan wel twee partners?

**Comment by MichelleDautzenberg** [comment]
Ik denk dat er iets mis is gegaan bij het koppelen van een partner. En dat je daarom ook maar voor één partner de getuigen kon invoeren.
Het probleem zit niet bij getuigen maar bij het inloggen van de 2e partner, dus ik sluit dit issue.

**Comment by CMasselink** [comment]
@MichelleDautzenberg  bedoelen wij hetzelfde? #305
