### ISSUE TITLE
Tekst bij getuigen is niet correct.

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#323]
Bij getuigen zou moeten staan dat er minimaal 2 maximaal 4 getuigen per huwelijk zijn.
Nu staat er dat 1 van de partners geen 3 getuigen mag hebben, ook niet als de ander er maar 1 heeft.
Dit mag wel.

**Comment by rubenvdlinde** [comment]
@DdeBruijn is dit een textuele wijziging op de getuigen pagina?

**Comment by JanWillemKooi** [comment]
Getest door @PatrickCastenmiller
