### ISSUE TITLE
Klikken op 'Ik wil geen opties' leid naar betaalpagina

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#324]
**Beschrijving van de bug**
Wanneer je klikt op ik wil geen opties bij extra opties dan kom je in het scherm dat je voor een optie hebt gekozen waarvoor je moet betalen.

**Wat heb ik gedaan**
Extra opties - Ik hoef geen extra opties

**Verwachting**
Uw keuze is vastgelegd ipv betaalpagina

**Bug**
Wanneer je aangeeft geen opties te willen zou je juist niet bij de betaalpagina moeten komen.

**Comment by rubenvdlinde** [comment]
Zou opgelost moeten zijn met stage completed fix,  ga ik even controleren op dev.

**Comment by rubenvdlinde** [comment]
Hoort bij #358

**Comment by matthiasoliveiro** [comment]
Het onderliggende issue is denk ik dat het betaalscherm niet duidelijk genoeg is. Op het moment dat je geen gratis huwelijk hebt gekozen dan zal je altijd wat moeten betalen. Hier zal dus iets moeten komen van een overzicht van de kosten (factuur achtig?) Dan kan je ook mooi weergeven dat je geen kosten hebt aan extra's.

**Comment by DdeBruijn** [comment]
Ziet er wat mij betreft nu goed uit. Wanneer andere opties nog niet zijn ingevuld was het erg onlogisch om na aan te geven dat je niets wil wel op de betaalpagina komt en dat is er nu uit.
