### ISSUE TITLE
Ik kan een locatie annuleren die ik niet heb gereserveerd

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#325]
**Beschrijving van de bug**
ErrorException
in src/Controller/DefaultController.php (line 740)
                $property = iterator_to_array($subArray);                break;            }        }                if(is_array($request['properties'][$property["name"]])){            $key = array_search($id, $request['properties']);            unset($request['properties'][$property["name"]][$key]);        }        else{            $request['properties'][$property["name"]] = null;
in vendor/symfony/http-kernel/HttpKernel.php->unsetAction (line 151)
        $this->dispatcher->dispatch($event, KernelEvents::CONTROLLER_ARGUMENTS);        $controller = $event->getController();        $arguments = $event->getArguments();        // call controller        $response = $controller(...$arguments);        // view        if (!$response instanceof Response) {            $event = new ViewEvent($this, $request, $type, $response);            $this->dispatcher->dispatch($event, KernelEvents::VIEW);
in vendor/symfony/http-kernel/HttpKernel.php->handleRaw (line 68)
    public function handle(Request $request, $type = HttpKernelInterface::MASTER_REQUEST, $catch = true)    {        $request->headers->set('X-Php-Ob-Level', (string) ob_get_level());        try {            return $this->handleRaw($request, $type);        } catch (\Exception $e) {            if ($e instanceof RequestExceptionInterface) {                $e = new BadRequestHttpException($e->getMessage(), $e);            }            if (false === $catch) {
in vendor/symfony/http-kernel/Kernel.php->handle (line 198)
        $this->boot();        ++$this->requestStackSize;        $this->resetServices = true;        try {            return $this->getHttpKernel()->handle($request, $type, $catch);        } finally {            --$this->requestStackSize;        }    }
Kernel->handle(object(Request))
in public/index.php (line 25)
    Request::setTrustedHosts([$trustedHosts]);}$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);$request = Request::createFromGlobals();$response = $kernel->handle($request);$response->send();$kernel->terminate($request, $response);

ErrorException
--
ErrorException: Notice: Undefined index: locatie    at src/Controller/DefaultController.php:740   at App\Controller\DefaultController->unsetAction(object(Session), 'locatie', 'https://pdc.zaakonline.nl/products/7ebcc7a9-ce12-401b-b3a1-18497c54d79d', object(RequestService))      (vendor/symfony/http-kernel/HttpKernel.php:151)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/http-kernel/HttpKernel.php:68)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (vendor/symfony/http-kernel/Kernel.php:198)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))      (public/index.php:25)

**Comment by rjzondervan** [comment]
Dit issue geldt ook voor ambtenaren
