### ISSUE TITLE
Locatie word niet onthouden als ik inlog vanuit een locatie reserveren

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#326]
Ik selecteerde de locatie en klikte op log in om te reserveren.
Vervolgens kwam ik op ceremonie kiezen en de locatie is niet onthouden.
Hierdoor moet ik weer op de locatie klikken en deze reserveren.

**Comment by matthiasoliveiro** [comment]
Er zijn twee mogelijk oplossingsrichtingen die gekozen kunnen worden. 
1. Het implementeren van een Authtentication provider
2. Het implementeren van lokaal opslaan in de sessie

Optie 1 is netter en eigenlijk de netste oplossing maar kost daar door ook het meeste tijd. Optie 2 is een snelle fix (hack).

**Comment by rubenvdlinde** [comment]
Hoort bij #358
