### ISSUE TITLE
Een gereserveerde locatie is niet zichtbaar op de locatie pagina

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#327]
Even twijfel tussen bug of feature request:
**Beschrijving van de bug**
Als je een locatie reserveert, is deze wel zichtbaar in de checklist maar als je op de locatie pagina zelf kijkt, is dit niet zichtbaar, niet het overzicht van alle locaties en ook niet op de detail pagina.

**Wat heb ik gedaan**
Locatie reserveren, bijvoorbeeld de kleine zaal stadhuis, bij checklist pagina kijken, daarna weer op de locatie pagina kijken.

**Verwachting**
Zichtbaar dat je een locatie al gereserveerd hebt. Zowel in het overzicht van de locaties als op de detail pagina

**Bug**
Niet zichtbaar welke locatie je hebt gereserveerd op de locatie pagina.

**Comment by rjzondervan** [comment]
Deze bug is opgelost en plenair gereviewd.
