### ISSUE TITLE
Links in de checklist geven een errorpagina

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#328]
**Beschrijving van de bug**
Als ik op de links klik in de checklist naar zaken die ik nog moet regelen krijg ik een errorpagina.

**Wat heb ik gedaan**
Niet alle stappen doorlopen. Bij de checklist werd ik hier op gewezen. Klikken op de linkjes leidt echter tot errorpaginas. 

**Verwachting**
Dat ik via de linkjes terug wordt geleid naar de pagina waarop ik dit alsnog kan regelen.

**Comment by JanWillemW** [comment]
Ceremonie doet het nog niet

**Comment by JanWillemKooi** [comment]
Getest tijdens de design week.
