### ISSUE TITLE
Als medewerker wil ik een BABS op 'niet zichtbaar' zetten (op de site)

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#330]
zodat deze niet gekozen kan worden.

Denk aan junioren of BABS-en die ondersteunen bij een externe BABS. Omvang middel, wens. 

DoD: kan ik een BABS onzichtbaar maken op de site maar deze wel inplannen als medewerker.

**Comment by rubenvdlinde** [comment]
De technische uitvoering hiervan is ondergebracht in #354, dus dit issue betreft het instellen daarvan via het dashboard

**Comment by JanWillemKooi** [comment]
Zie ook #354
