### ISSUE TITLE
Als medewerker wil ik een overzicht hebben welke locaties wanneer beschikbaar zijn

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#331]
zodat ik overzicht heb.

Nodig voor haalbaarheid (reistijd). Let op: eerste stap is het (in samenhang met andere 2 overzichten) creëren van een schets voor het dashboard

DoD: plan een aantal huwelijken in en check of deze in het overzicht als niet beschikbaar staan.

**Comment by rubenvdlinde** [comment]
Dit hangt samen met de gedachte over overzichts paginas

**Comment by rubenvdlinde** [comment]
@DdeBruijn heb jij voorbeeld link van pink die je laats liet zien?

**Comment by CMasselink** [comment]
Kan al in het medewerkersportaal
