### ISSUE TITLE
Als BABS wil ik weten wanneer en op welke locatie ik welk stel ga trouwen (scherm)

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#332]
zodat ik zicht heb op mijn eigen planning.

Vraagt om een eigen portal voor de BABS. Dit zou als ontwikkeling groot zijn, maar als eerst rollen worden gerealiseerd wordt dit een stuk kleiner. 

Voor designweek eerst een schets maken van het BABS portal.

DoD: schets van het portal? (bij bouwen: plan een aantal huwelijken in op verschillende locaties voor één BABS en bekijk het overzicht)

**Comment by rubenvdlinde** [comment]
Voorgestelde aanpak is dat techniek een mock pagina ter discussie aanlevert, en dat we naar aanleiding hiervan itereren naar een werkzame overzichts pagina voor babsen.

Overigens hangt dit wel weer samen met de gedachte dat er rollen en rechten moeten komen die inregelbaar zijn vanuit het dashboard.

**Comment by bbrands02** [comment]
Moeten we morgen even een demo van geven om te reviewen.

**Comment by CMasselink** [comment]
Eerste versie van scherm is gemaakt toch? Moet nog gereviewed worden met babsen samen met team proces?

**Comment by DdeBruijn** [comment]
Versie stond nog lokaal en was nog niet in te zien. Ik heb een verzoek ingediend in Almere voor een datum voor review, maar verwacht dit niet binnen 1-2 gereed. Zodra in te zien kan het meegenomen worden.

**Comment by matthiasoliveiro** [comment]
Scherm staat online en kan tzt gereviewd kan worden
https://db.huwelijksplanner.online/babs/huwelijk

Username: wiedanook
ww: test22

**Comment by DdeBruijn** [comment]
Nieuwe US aangemaakt voor issue waar ik tegenaan loop om deze goed te kunnen reviewen. #413
