### ISSUE TITLE
Als scrumteam wil ik weten welke generieke rollen er zijn in het hele proces

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#336]
zodat ik bij de uitwerking van de individuele userstories eenvoudig kan benoemen welke rollen en rechten noodzakelijk zijn.

DoD: er is een door het team vastgestelde set van rollen

Impact: klein

**Comment by DdeBruijn** [comment]
Ik vermoed dat dit verwijst naar de rollen en rechten voor het Dashboard.
Gezien er nu 3 kopjes zijn, trouwambtenaar, medewerker en beheerder vermoed ik dat we daarmee ook de drie inititeel benodigde rollen te pakken hebben. @JanWillemW mee eens?

**Comment by MichelleDautzenberg** [comment]
Ik ben het in ieder geval eens Daphne!

**Comment by DdeBruijn** [comment]
@JanWillemW kun je nog naar deze kijken?

**Comment by DdeBruijn** [comment]
Gezien gebrek aan reactie verplaats ik deze naar done.
Uitkomst: 3 rollen, trouwambtenaar, medewerker en beheerder
