### ISSUE TITLE
Als inwoner wil ik dat het menu-onderdeel waar ik mee bezig ben oplicht

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#337]
zodat ik weet waar ik ben

Mag ook in andere vorm dan 'oplichten' zijn. Omlijnd of whatever als het maar mooi en duidelijk is.

Omvang: klein?

**Comment by rubenvdlinde** [comment]
In principe weet de pagina reeds waar in het proces je bent, dus we zouden dit kunnen afvangen met een html/csss wijziging.

**Comment by rubenvdlinde** [comment]
@bbrands02 We kunnen aan de hand van de active stage een grafische wijziging doen op dat icoontje. @rjzondervan kan evt helpen met het logica stukje.

**Comment by matthiasoliveiro** [comment]
In overleg met Jeroen en Renee: Invert kleuren van de stap logo en zet er een ring om heen.

inschatten

**Comment by bbrands02** [comment]
Reviewbaar op https://www.dev.huwelijksplanner.online

**Comment by JeroenduC** [comment]
Ziet er al goed uit! Helaas nog een kleine onvolkomendheid kunnen ontdekken, dus hij kan nog niet op Done. 

Als je een heel nieuw huwelijksverzoek opstart, dan begin je op de Ceremonie pagina. De Ceremonie stap is dan niet opgelicht (kleuren geinverteerd). 

Stappen:
-Log in als nieuwe gebruiker
-Start nieuwe huwelijksaanvraag
-Wacht totdat Ceremoniepagina geopend wordt

Verwacht resultaat: ceremonie stap heeft een inverse kleur.
Daadwerkelijk resultaat:  ceremonie stap heeft geen inverse kleur.

![image](https://user-images.githubusercontent.com/49227194/75445534-e3677a80-5965-11ea-8c6f-cebed3d1dc6f.png)

**Comment by JeroenduC** [comment]
Ceremonie licht nu ook prachtig op! Super!

**Comment by MichelleDautzenberg** [comment]
Jeroen, volgens mij is dit nu gefixt.
We hebben gisteren afgesproken dat als wij iets getest hebben in de dev-omgeving en het is akkoord, wij het dan verplaatsen van Review naar de kolom Deploy. Dan wordt het uitgerold naar productie-omgeving en krijgen wij een signaal om het daar nogmaals te testen.

**Comment by JeroenduC** [comment]
Ik denk dat ik nu mijzelf hier vanaf moet halen en het aan iemand van Conduction toe moet kennen, zodat het gedeployed gaat worden zodat ik het daarna weer kan testen. 

Mocht ik dat fout hebben, laat het mij weten en ken mij dan weer toe aan dit issue.

**Comment by JeroenduC** [comment]
Another one bites the dust! Done!
