### ISSUE TITLE
Als medewerker wil de agenda van een locatie kunnen inzien en blokkeren/reserveren van bepaalde tijden (scherm)

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#339]
zodat er geen dubbele boeken zijn --> denk aan eventplanning

Techniek inschatting: Medium 

Acties:
-Overzichten van Locaties kunnen zien
-Maand, week  en jaar overzicht.
-Overzicht v/d halve uren kunnen blokkeren (per minuut of blok?) 

is gerelateerd aan #340 #51

**Comment by rubenvdlinde** [comment]
Kort samengevat wil je voor alles wat een agenda heeft deze agenda kunnen inzien en aanpassen via het dashboard. Dit lijkt me één die we deze week zouden moeten willen oppakken,

**Comment by MichelleDautzenberg** [comment]
Voor nu akkoord wat scherm betreft.
