### ISSUE TITLE
Als scrumteam wil weten welke onderdelen van de site aanpasbaar moeten zijn

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#343]
zodat deze onderdelen kunnen worden voorzien van contentbeheer functionaliteit

DoD: het scrumteam heeft een lijst met onderdelen vastgesteld en geprioriteerd.

**Comment by DdeBruijn** [comment]
De pagina met 'Extra opties' moet instelbaar zijn qua tekst, afbeeldingen en prijzen.

**Comment by MichelleDautzenberg** [comment]
Dit is al uitgewerkt in losse userstories met het label Beheer
