### ISSUE TITLE
Als contentbeheerder wil ik de informatie op de Home aanpassen

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#344]
zodat deze gemeentespecifiek is

invulling van één van de onderdelen van #343

**Comment by rubenvdlinde** [comment]
Afhankelijk van of de huidige dashboard functionaliteit volstaat zou dit in principe reed geregeld moeten zijn. @JanWillemKooi zullen we deze op review zetten en dan donderdag een dashboard review doen?

**Comment by JanWillemKooi** [comment]
Technisch gereed. Vraag is hoe de UX van een technische beheerder gedaan moet worden. Zou kunnen met huidige dashboard. Voorlopig goed genoeg voor MPV. Risico is wel dat een beheerder op deze manier de applicatie kan stuk maken.

**Comment by JanWillemKooi** [comment]
Getest tot 2022
