### ISSUE TITLE
Als medewerker wil ik babsen aanbieden op de pagina met de optie een voorkeur of meerdere (1,2,3) door te geven

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#345]
zodat ik wel babsen kan tonen maar hun agenda nog niet compleet hoeft te zijn als ik daar als gemeente voor kies.

**Comment by rubenvdlinde** [comment]
Deze is redelijk heftig omdat het betekend dat we een tweede type huwelijk moeten inrichten (het gaat hier dan immers over een huwelijk met een ander soort voorwaarden). 

Dit leid dan vervolgens weer bijna automatische tot #356 en #357 dat te samen maakt dit "large" dat gezegd hebbende zijn dit allen zaken die we zowiezo een keer moeten oppakken. En wel een mooi bij resultaat zouden zijn van de design week.

**Comment by PatrickCastenmiller** [comment]
@rubenvdlinde wat bedoel je met een 'type huwelijk' ? Het gaat hier toch om een alternatief scenario, waarvan er uiteindelijk 1 gekozen wordt?

**Comment by rubenvdlinde** [comment]
Euh nee het gaat om twee scenarios die tegelijkertijd bestaan, in dit geval Rotterdam en Utrecht die bijde een wat afwijkende flow hanteren. Wat de vraag op roept wat we centraal in een proces regelen en wat lokale afwijkingen zijn.

**Comment by RickWildHoorn** [comment]
We gaan niet meer met een voorkeur werken, maar met een keuze die een X periode voor de huwelijksdatum gemaakt kan worden. Zie #550
