### ISSUE TITLE
Als medewerker wil ik handmatig een BABS inplannen en de keuze van de inwoner 'overrulen'

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#347]
zodat ik waar nodig aanpassingen kan doen.

Bij ziekte van een BABS of bij een slechte 'klik' met een BABS kan het zijn dat (in overleg met de inwoner) wordt besloten een andere BABS in te zetten. Om te voorkomen dat dan de inwoner dan wordt gevraagd dit aan te passen op de site moet de medewerker dit ook kunnen doen.

DoD: test of een medewerker de BABS kan wijzigen en dat de inwoner dit dan in zijn / haar overzicht kan zien (waar van toepassing)

Hangt samen met kunnen invoeren namens de inwoner. Is een groter vraagstuk, waarvoor een userstory wordt opgesteld #342

**Comment by CMasselink** [comment]
Dit kan reeds
