### ISSUE TITLE
Als scrumteam wil ik inzicht hebben in de business rules voor het automatisch toewijzen van BABS-en

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#348]
zodat we weten wat we moeten doen om BABS-en automatisch te koppelen aan een huwelijk. Het systeem bepaalt dan welke BABS gekoppeld wordt.

DoD: vastgestelde business rules voor het geautomatiseerd verwerken van de koppeling. 

Heeft zowel te maken met wanneer je dit doet als met welke regels!

**Comment by MichelleDautzenberg** [comment]
Actie: uitzoeken procesteam wat we hier voor MVP mee willen doen. Automatisch toewijzen of medewerker laten doen?

Kan erg complex worden om hier businessrules voor te bepalen. Hoeveel huwelijken per babs op een dag? Mag elke Babs toegewezen worden?

**Comment by MichelleDautzenberg** [comment]
Business rules bij vrije keuze Babs zijn uitgewerkt bij #551 
Bij flits/eenvoudig/gratis heeft de inwoner geen keuze voor een Babs, maar wordt er een (B)Abs handmatig toegewezen door een coördinerend medewerker. (zie ook #432 voor configuratie hiervan)
