### ISSUE TITLE
Als scrumteam wil ik inzicht hebben op de business logica (proces) achter gemeentespecifieke keuzes

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#349]
zodat we keuzes kunnen maken wat we wel/ niet inregelbaar moeten maken .

Dit issue komt voort uit het kunnen uitvragen of het paar ringen wil uitwisselen. Maar dat wisselt per gemeente. Eerst check of er nog meer dergelijke zaken zijn en bepalen wat als informatie getoond wordt, en wat met deze informatie gedaan moet worden (al dan niet geautomatiseerd).

DoD: vastgesteld beeld van opties voor proces (ringen en?) en keuze wat wel en in welke vorm en wat niet.

**Comment by MichelleDautzenberg** [comment]
Je kan nu alle producten die je als gemeente kiesbaar wilt hebben, toevoegen aan de PDC. 
Voor de MVP lijkt ons dat voldoende.
