### ISSUE TITLE
Als developer wil ik graag dat alle resources in alle apis worden voorzien van dateCreated en dateModified

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#350]
Als developer wil ik graag dat alle resources in alle apis worden voorzien van dateCreated  en dateModified, zodat ik hierop kan ordenen in overzichten.

Het gebruik van UUID's betekend dat het niet mogelijk is om te sorteren op oplopendheid van ID's, dit zorgt er in voorkomende gevallen voor dat overzichts lijsten voor gebruikers "ongeordend" aanvoelen. 

We willen dit graag stapsgewijs op alle resources in alle api's aanpassen (ook ter vervanging van de her en der al gebruikte createdAt en updatedAt properties), zodat we lijsten beter kunnen weergeven aan gebruikers. 

Zie ook
https://schema.org/dateCreated
https://schema.org/dateModified

**Comment by rubenvdlinde** [comment]
Hier moeten we als techniek team een besluit over nemen

**Comment by CMasselink** [comment]
Ik denk dat we deze functionaliteit inderdaad wel nodig gaan hebben maar mijn voorstel zou zijn: implementeer het eerst voor de resources waarbij we het nodig hebben. Overige resources kunnen later aan bod komen. 
Als we via het proto component de wijziging naar alle componenten/resources eenvoudig kunnen laten propageren, zouden we wel kunnen kijken of we met relatief weinig effort alles in 1 keer kunnen bijwerken.

**Comment by CMasselink** [comment]
@rubenvdlinde Voorstel zoals vorige week besproken was toch om dit door te voeren voor resources die we toch al aanraken/waar wijzigingen op nodig zijn?

**Comment by rubenvdlinde** [comment]
Yup, we nemen deze mee daar waar we componenten aanraken maar gaan niet bewust alle componenten hiervoor aanpassen.

**Comment by CMasselink** [comment]
Ik sluit deze  user story, wordt onderdeel van DoD
