### ISSUE TITLE
Als developer wil ik moeder kind relaties in groups (PDC)

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#351]
Zodat ik een betere ordening kan aanbrengen binnen producten, we zien dat in de praktijk product groepen worden gebruikt als stapelbare taxonomie (dus ambtenaren als onderdeel van huwelijken etc). Dit is iets dat verstandig zou zijn om te ondersteunen.

**Comment by rubenvdlinde** [comment]
Hier moeten we als techniek team een besluit over nemen

**Comment by CMasselink** [comment]
Idee voor nu: generiek koppelobject/resource in PDC. Met generieke source in PDC naar een object uit een andere registratie. 
Nog verder uitwerken: welke informatie moet er op de relatie vastgelegd worden.

**Comment by rubenvdlinde** [comment]
Nou het gaat hier niet om relaties met producten maar om de taxanomie van groupen. Ik zou verwachten dat dat een boom is. Ofwel kleding -> broeken -> korte broek. Maar  tis nu plat.

**Comment by CMasselink** [comment]
OAS documentatie is nog niet zuiver. Bij de description staat "any" 
![image](https://user-images.githubusercontent.com/39768984/73521771-2980fb00-4407-11ea-86d8-fc53048e2be0.png)

De relatie lijkt nu 2 kanten op te lopen, klopt dat? Hoe moet ik een parent-child relatie leggen, geef ik bij een parent de child's aan of bij een child de parents?

**Comment by CMasselink** [comment]
@rubenvdlinde zie mijn vragen in mijn vorige comment.

**Comment by matthiasoliveiro** [comment]
Zou nu correct moeten zijn. https://pdc.huwelijksplanner.online/

**Comment by CMasselink** [comment]
Children is uit documentatie gehaald. Documentatie klopt nu.
