### ISSUE TITLE
Als medewerker wil ik producten kunnen oormerken als intern

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#354]
zodat babsen in mijn systeem kan hebben en kan toewijzen aan  huwelijken zonder dat deze op de website zichtbaar zijn.

[Producten ](https://schema.org/Product) kennen in schema.org een [audience](https://schema.org/audience), mij voorstel zou zijn om deze op te nemen in het PDC als property op een product en dan te zetten op bijvoorbeeld internal/public zodat we er in het dashboard en de applicatie anders op kunnen filteren.

**Comment by CMasselink** [comment]
attribuut audience toevoegen met enum: internal/public lijkt me voor nu prima.

**Comment by rubenvdlinde** [comment]
Hier is nu een atribuut voor
- Dat moet voor reeds bestaande producten worden ingeregeld
- Defaulten naar "internal"
- Er moet een product "stage ambtenaar" worden toegevoegd, die moet op internal zodat de werking zichtbaar wordt.

**Comment by JanWillemKooi** [comment]
Technische gerealiseerd en getest tijdens de design week

**Comment by CMasselink** [comment]
@rubenvdlinde is hier bewust geen enum van gemaakt? In de OAS staat als type string
