### ISSUE TITLE
Als klant wil ik meerdere soorten processen kunnen afhandelen

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#356]
zodat ik bijvoorbeeld ook een aanvraag BABSVO of trouwlocatie via de applicatie kan indienen, of een huwelijk bij een andere gemeente.

Grappig genoeg is deze user technisch niet eens zo interessant, we draaien het hele trouwprocces immers al configureerbaar. Het enige wat we zouden moeten toevoegen is een scherm waarin je een proces kiest (we forceren nu altijd een huwelijk bij Utrecht).

**Comment by CMasselink** [comment]
Technisch gezien is het mogelijk.  Voor de individuele processen, zoals aanvragen babs voor een dag, moeten aparte userstories gemaakt worden. Zowel voor het aanvraag proces vanuit burger perspectief, als het afhandel perspectief vanuit de medewerker.

**Comment by rubenvdlinde** [comment]
Deze moeten we dan even uit elkaar trekken in een technisch issue voor de mogelijkheid (das dan hierbij deze). En inderdaad losse user stories voor de individuele processen.

**Comment by JanWillemKooi** [comment]
Technische gerealiseerd. Inhoudelijk is input vanuit Koggerland en Almere aangeleverd. 
Zie ook user story #92 met de gegevens vanuit Utrecht.
ToDo: toevoegen werkelijke proces vanuit Utrecht

**Comment by MichelleDautzenberg** [comment]
Zie de BPMNs onder documenten.
