### ISSUE TITLE
Als developer wil ik de default controller uitkleden

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#358]
zodat de afhandeling van routing overzichtelijker wordt.

Dit is een puur technisch (code punt) maar doordat er nu te veel in de controller van de huwelijksplanner gebeurd is de afhandeling van routing onoverzichtelijk. Dit draagt bij tot een aantal bugs rondom interne verwijzingen, onthouden van waar je was bij inloggen etc. 

Daarnaast is er een toenemende behoeft aan flexibiliteit voor processen en organisaties. Het zou dan ook goed zijn de code even op te schonen en de logica naar een service te verplaatsen. Zou niet meer dan een uurtje werk mogen zijn.

**Comment by JanWillemKooi** [comment]
Door Rene, Patrick, Jan Willem (2x) (na uitgebreide uitleg van Conduction dat dit is geimplementeerd) gesloten.
Tevens is een nieuw inzicht ontstaan over aantal verzoeken. Hier is een nieuwe user story voor aangemaakt (#376)
