### ISSUE TITLE
Als procesteam wil ik het proces vastleggen van wijzigen en annuleren van een reservering

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#36]
#35 

Let op:
- [ ] duidelijke beschrijving wat moet gebeuren
- [ ] gekoppeld aan een persoon (assign)
- [ ]  gekoppeld aan een user story (door # en het nummer toe te voegen)

**Comment by MichelleDautzenberg** [comment]
Wijzigen was al mogelijk in de reeds gemaakte BPMN modellen. Deelproces van annuleren is toegevoegd (zie map BPMN)

**Comment by JanWillemKooi** [comment]
Welke user story's zijn hieraan gerelateerd?

**Comment by MichelleDautzenberg** [comment]
#231 
#230 
#229 
#227 
#169 
#41
