### ISSUE TITLE
Als Scrumteam willen we alle wensen/ eisen die door Rick Wildenberg zijn verzameld gecheckt worden

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#365]
Tijdens de design week op 28 jan 2020 is dit gedaan door: Jan Willem (2x), Patrick, Rene, Daphne aan de hand van het inwonersperspectief

Inwonersperspectief:
•	Als inwoner wil ik het proces in kunnen gaan met de datum of locatie als hoofduitgangspunt, omdat dat voor mij het belangrijkste element is.
**User story: #310**

•	Als inwoner wil ik uitleg over een trouwboekje, zodat ik daarmee de afweging kan maken om er wel/geen te kopen.
**User story: #348**

•	Als inwoner wil ik op de kalender al kunnen zien op welke data en tijden de door mij geselecteerde BABS daadwerkelijk beschikbaar is, zodat ik niet teleurgesteld raak omdat later iets niet blijkt te kunnen.
Bron: Project Convenant gemeenten
**User story: #60**

•	Als inwoner wil ik een digitale bevestiging van de met alle vastgelegde opties zodat ik zeker weet dat mijn huwelijk gaat zoals ik wil.
Bron: Project Convenant gemeenten
**User story: #360**

•	Als inwoner wil ik de mogelijkheid hebben om data als optie in te plannen, zodat ik hierin flexibel mijn trouwmoment kan organiseren.
Bron: Project Convenant gemeenten
**Zit impliciet in de applicatie. Is een ongewenste optie. Inwoners kunnen veel data reserveren zonder er gebruik van te willen maken en daarmee faliciteiten blokkeren voor anderen.**

•	Als inwoner wil ik inzichtelijk hebben wanneer ik bepaalde zaken uiterlijk geregeld moet hebben, zodat ik niet te laat ben. Denk hierbij aan bijvoorbeeld de melding of het definitief maken (of betalen) van de reservering.
Bron: Project Convenant gemeenten
**User story: #362 #363 #364**

•	Als inwoner wil ik direct de garantie / bevestiging in beeld dat mijn gereserveerde datum en tijd ook in het systeem zijn vastgelegd.
Bron: Project Convenant gemeenten
**Zit in de applicatie doormiddel van een vinkje. Echter de reservering zit 'nog' niet in de systemen van de gemeente. Zie daarvoor user story #360**

•	Als inwoner wil ik direct ook mijn melding voorgenomen huwelijk/partnerschap kunnen regelen zodat ik in 1x klaar ben.
Bron: Project Convenant gemeenten
**Deze user story was doorgestreept, echter toch besproken. Conclusie staat in user story #367**

•	Als inwoner wil ik digitaal kunnen aangeven dat ik een eigen BABS heb geregeld, zodat ik geen standaard BABS hoef te kiezen.
Bron: Project Convenant gemeenten
**Deze user story was doorgestreept, echter toch besproken. De knop is aanwezig in de applicatie echter het proces erachter nog niet. Zie user story #369**

•	Als inwoner wil ik digitaal kunnen aangeven dat ik een eigen locatie heb geregeld, zodat ik geen standaard locatie hoef te kiezen.
Bron: Project Convenant gemeenten
**User story #92**

•	Als inwoner wil ik direct duidelijkheid of ik voldoe aan de (wettelijke) eisen voor het reserveren/sluiten van een huwelijk of geregistreerd partnerschap, zodat ik meteen weet waar ik aan toe ben.

Bron: Programma van eisen, Utrecht
**User story #367 gevat meer dan wat hier wordt gevraagd. Discussie over wat 'direct' mogelijk is. Zie ook user story #168**

•	Als inwoner wil op hele en halve uren een reservering kunnen maken (bijvoorbeeld 15.00, 15.30, 16.00 uur etc.)
Bron: Programma van eisen, Utrecht
**Zit in de applicatie**

•	Als inwoner wil ik van de ‘vaste’ locaties inzichtelijk hebben hoeveel mensen er op de locaties terecht kunnen, zodat ik weet hoeveel mensen ik kan uitnodigen bij mijn ceremonie.
Bron: Programma van eisen, Utrecht
**User story #370**

•	Als inwoner wil ik van de ‘vaste’ locaties inzichtelijk hebben of de locaties roltoegankelijk zijn, zodat ik daar rekening mee kan houden.
Bron: Programma van eisen, Utrecht
**User story #370**

•	Als inwoner wil ik van de ‘vaste’ locaties inzichtelijk hebben wat wel/niet toegestaan is. Denk hierbij aan het strooien van rijst, het oplaten van ballonnen of het laten vliegen van duiven etc.
Bron: Programma van eisen, Utrecht
**User story #370**

•	Als inwoner wil ik een duidelijke foto (binnen, buitenkant en kleur-opties) van een trouwboekje, zodat ik een goede keuze kan maken.
Bron: Programma van eisen, Utrecht
**User story #343**

•	Als inwoner wil ik de mogelijkheid hebben om cash te kunnen betalen.
Bron: Programma van eisen, Utrecht
**User story #371**

•	Als inwoner wil ik tijdens het maken van de reservering wil ik ook gelijk mijn Naamgebruik-voorkeuren doorgeven.
Bron: Programma van eisen, Utrecht
**User story #372**

•	Als inwoner wil ik uitleg over het Naamgebruik, zodat ik weet waar de gemeente het aan doorgeeft en waar ik het zelf moet doorgeven.
Bron: Programma van eisen, Utrecht
**User story #372**

•	Als inwoner wil ik dat alle teksten op B1 niveau geschreven zijn, dat ik deze als licht verstandelijk gehandicapte of als iemand met een niet-Nederlandse achtergrond ook kan begrijpen.
Bron: Programma van eisen, Utrecht
**User story #373**

•	Als inwoner wil ik dat dat de tool ook toegankelijk is voor slechtzienden, zodat ik niet buitengesloten wordt.
Bron: Programma van eisen, Utrecht
**User story #374**

•	Als inwoner wil ik een FAQ beschikbaar hebben, zodat ik de meest gestelde vragen kan vinden.
Bron: Programma van eisen, Utrecht
**User story #375**

**Comment by matthiasoliveiro** [comment]
@RickWildHoorn ter review

**Comment by PatrickCastenmiller** [comment]
Is afgehandeld in de designweek op maandag en dinsdag.
