### ISSUE TITLE
Als scrum team wil ik een Mock van de checklist die de "deadlines" per in te vullen item bevat

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#366]
zodat ik een goede overweging kan maken of dit de manier van het weergeven is.

Als we dit willen kunnen we van uit techniek een goede inschatting geven hoeveel werk dit is.

**Comment by JanWillemKooi** [comment]
Demo gehad van de mock van Conduction
