### ISSUE TITLE
Als developer wil ik gebruikers informeren dat ze al een ambtenaar of locatie hebben gekozen

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/huwelijksplanner#368]
zodat ze makkelijk kunnen navigeren wanneer ze deze keuze willen wijzigen.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by JanWillemKooi** [comment]
Getest tijdens de design week met Rene, Patrick en JW (2x)
