### ISSUE TITLE
Als scrumteam wil ik dat het proces rond het aanstellen van een BABS voor een dag wordt beschreven, 

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/huwelijksplanner#369]
zodat we kunnen bepalen of & hoe we deze in de huwelijksplanner kunnen verwerken.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Zie [https://www.utrecht.nl/fileadmin/uploads/documenten/wonen-en-leven/burgerzaken/Aanvraagformulier-al-benoemd-trouwambtenaar-1dag.pdf]

Je kan dit formulier als uitgangspunt gebruiken om een instemmingsverzoek te versturen naar de zelfgekozen Babs. (meeste velden heb je al, dus het kan een vrij kort formuliertje worden).

De zelfgekozen Babs geeft vervolgens instemming. (net als bij een getuige dus).

**Comment by MichelleDautzenberg** [comment]
Zie de 2 BPMNs onder documenten!
