### ISSUE TITLE
Als inwoner wil ik tijdens het maken van de reservering / melding ook gelijk mijn naamgebruik voorkeuren doorgeven

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#372]
zodat ik dit allemaal makkelijk in één keer heb geregeld.

Hiervoor moet worden uitgezocht hoe dit werkt als mensen trouwen bij een andere gemeente dan de gemeente waarvan ze inwoner zijn.

Hierbij  ook meenemen info over naamgebruik, wie dit door krijgt en wanneer dit in gaat.

**Comment by rubenvdlinde** [comment]
Deze hangt samen met #372 er moet een mogelijkheid komen om als stap in het proces een soort "formulier" te hebben met aanvullende vragen.

**Comment by MichelleDautzenberg** [comment]
Zie ook #61 

Is het mogelijk om ipv de tekstuele beschrijving ("eerst uw eigen achternaam...") ook de opties met de daadwerkelijke namen te laten zien?
Dus bijv:
Anita Henrika de Kieft
Anita Henrika De Kieft - Dekker
Anita Henrika Dekker - de Kieft
Anita Henrika Dekker

**Comment by MichelleDautzenberg** [comment]
Ik sluit deze, want dubbel met #61
