### ISSUE TITLE
Als inwoner wil ik dat alle teksten op B1 niveau geschreven zijn

### ISSUE THREAD

**Issue by JanWillemW** [VNG-Realisatie/huwelijksplanner#373]
zodat ook iemand die minder taalvaardig is goed uit de voeten kan met de huwelijksplanner.

**Comment by MichelleDautzenberg** [comment]
Bijv:
Email adres = E-mailadres
Telefoon nummer = telefoonnummer

**Comment by MichelleDautzenberg** [comment]
Dubbel met #315
