### ISSUE TITLE
Als developer wil ik een lijst met mogelijke extra's

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/huwelijksplanner#378]
zodat we deze kunnen implementeren en weergeven op de pagina extra's

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
De beheerder kan deze extra's toevoegen.
