### ISSUE TITLE
Als developer wil ik product kenmerken

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#379]
zodat ik hierop kan filteren

**Comment by CMasselink** [comment]
@rubenvdlinde 
Hoe is dit geïmplementeerd? En wat willen we hiermee / hoe gebruiken we het?
Bij de product resource is een attribuut additionalProperties toegevoegd maar de documentatie klopt niet:
![afbeelding](https://user-images.githubusercontent.com/39768984/73761130-a6490780-476e-11ea-973d-484f8ade26a7.png)
Ik zie ook een resource propertyValue. Moet het attribuut additionalProperties verwijzen naar de resource propertyValue? 

Het datamodel moet nog aangepast worden op het toevoegen van de attributen en resources.

**Comment by rjzondervan** [comment]
De additionalProperties moeten inderdaad verwijzen naar PropertyValues, die een naam en een beschrijving hebben. Ik zal de documentatie hier even op aanvullen.

**Comment by CMasselink** [comment]
Ok, assign mij maar weer als ik kan reviewen. Vraag blijft nog hoe we dit nu gebruiken voor de huwelijksplanner.

**Comment by CMasselink** [comment]
@rjzondervan 
Documentatie is nog niet goed op o.a. product list:
![image](https://user-images.githubusercontent.com/39768984/75624686-d7262c00-5bb6-11ea-8847-5aa8cc0a4256.png)


Documentatie van additionalPropoerties is nog niet aangepast bij bijvoorbeeld een POST:
![image](https://user-images.githubusercontent.com/39768984/75624708-ff158f80-5bb6-11ea-8c33-300359c9324c.png)

**Comment by rjzondervan** [comment]
Documentatie is inmiddels bijgewerkt.

**Comment by CMasselink** [comment]
@rjzondervan ik sluit hem voor dit specifieke issue. De documentatie van het PDC als geheel is echter nog steeds niet op orde. Vooral bij query parameters mist vaak de toelichting. Zou je daar nog een keer naar kunnen kijken?
