### ISSUE TITLE
Als procesteam wil ik het proces vastleggen voor als een melding voorgenomen huwelijk verloopt

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#38]
Beschrijving van de taak:
Meldingen zijn maar x periode geldig, wat als de melding verloopt voordat het huwelijk heeft plaatsgevonden?

Let op:
- [ ] duidelijke beschrijving wat moet gebeuren
- [ ] gekoppeld aan een persoon (assign)
- [ ]  gekoppeld aan een user story (door # en het nummer toe te voegen)

**Comment by MichelleDautzenberg** [comment]
Dit proces verloopt al goed met de huidige procesbeschrijvingen. De aanwezigheid en geldigheid van de melding wordt immer gecheckt (in het proces Reservering afhandelen) na iedere wijziging. Wel extra userstories voor aangemaakt.

**Comment by JanWillemKooi** [comment]
Welke user story's zijn hieraan gerelateerd?

**Comment by MichelleDautzenberg** [comment]
#86 
#141 
#155 
#166 
#227
#228
