### ISSUE TITLE
Favicon toevoegen aan de URL

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#380]
Om vertrouwen van de inwoner te vergroten willen we en favicon in tabblad hebben staan.

![favicon](https://user-images.githubusercontent.com/36506861/73453645-c5115d80-436c-11ea-85d6-bc12bbf693f8.png)

**Comment by JanWillemKooi** [comment]
Technisch gerealiseerd.
Wacht op aanlevering van de juiste favicon

**Comment by Ollie-nl** [comment]
Hier een URL
https://www.utrecht.nl/templates/images/favicon.png

**Comment by rubenvdlinde** [comment]
Ow nooz...

![image](https://user-images.githubusercontent.com/4021899/73608999-a1971e80-45c9-11ea-8433-cff145ad9967.png)

**Comment by CMasselink** [comment]
https://www.utrecht.nl/templates/images/favicon.ico lijkt wel te werken. @Ollie-nl is deze link wel correct of moet het een andere favicon zijn. (de .ico is redelijk klein)

**Comment by JeroenduC** [comment]
Besproken met @Ollie-nl , hij gaat het verder opzoeken.

**Comment by Ollie-nl** [comment]
probeer deze eens
https://www.utrecht.nl/favicon.ico

**Comment by RickWildHoorn** [comment]
@Ollie-nl Techniek kan nu verder met jouw favicon als het goed is? Zou je hen willen assignen en terug naar In Progress?

**Comment by matthiasoliveiro** [comment]
Hertest wat mij betreft goed. @JeroenduC denk jij er ook zo over?

**Comment by JeroenduC** [comment]
Staat goed op dev.huwelijksplanner.online. Hertest goed. Issue closed.
