### ISSUE TITLE
Als tester wil ik een testplan maken

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#385]
zodat ik het testen van de processen en applicatie goed kan organiseren en uitvoeren en we daardoor de juiste feedback krijgen zodat we een goedwerkende huwelijksplanner krijgen

- [X ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [X] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [x] Voeg alle taken die nodig zijn voor de user story toe.

In het testplan moet rekening gehouden worden:
in kaart brengen van groepen testers zoals:
- Inwoners
- Medewerkers in de back office van de gemeente
- Balie medewerkers
- Babsen
- IT van de gemeente

Zorgen voor de juiste tooling per groep (Github, e-mail, telefoon of directe begeleiding)
Zorgen voor de juiste begeleiding per groep testers

Per groep verschillende scenario's uitwerken:
Inwoners: Gratis, Eenvouding en Uigebreid huwelijk maar ook zaken als onder curatele, buitenland etc.)
Medewerkers: Invullen voor bruger, completeren van een verzoek, overzichten van geplande huwelijken
Babs: planningen (kunnen lezen en aanpassen), informatie bijwerken
IT van de gemeente: rechten per rol/ gebruiker, management van gebruikers van de applicatie, security, infrastuctuur, destructive testen. Deze testen moeten door profesionele testers worden uitgevoerd.

In samenwerking met de ontwikkelaars geautomatiseerd testen introduceren van unit testen, regressietesten vooral na aanpassingen en oplossen van bugs.

In het testplan moet rekening worden gehouden met de hele keten vanuit het idee van een burger om te gaan trouwen tot en met het voltrokken huwelijk met de geudate registers, juiste actes en afronden van alle acties.

TIPS: scenario's uitwerken op basis van de interviews en eventueel bevindingen van de Bruidsbeurs (https://www.trouwen-bruiloft.nl/trouwbeurzen.htm)

**Comment by MichelleDautzenberg** [comment]
Testplan is door Jeroen gemaakt.
