### ISSUE TITLE
Als inwoner wil ik een homebutton in de planner kunnen gebruiken

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#388]
zodat ik altijd terug naar de homepage kan.

Deze homepagina moet nog toegevoegd worden. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
Er mist nu ook een mogelijkheid om terug te gaan naar je verzoeken overzicht

**Comment by rjzondervan** [comment]
Deze is overigens dubbel met #282

**Comment by matthiasoliveiro** [comment]
Hi Jeroen ik snap de noodzaak tot een "home" button maar waar zullen we die eens zetten

**Comment by JeroenduC** [comment]
In de huidige app zou ik hem eens op het logo (de trouwringen) linksboven zetten.

**Comment by matthiasoliveiro** [comment]
Home is pagina stap 0 #394. Mouse over moet de tekst "home". 
Ringen zijn de home knop, en alleen klikbaar wanneer je niet op  home pagina bent.
![image](https://user-images.githubusercontent.com/36506861/74817027-8a13a180-52fc-11ea-9399-a1b5e3aaf8b3.png)

**Comment by CMasselink** [comment]
@rubenvdlinde je hebt dit naar review geplaatst, wie moet reviewen?

**Comment by matthiasoliveiro** [comment]
Knop verwijst nu naar het eerste scherm. Stap 0 is nog niet geïmplementeerd. Als die er is zal de knop daar naar toe verwijzen.

**Comment by MichelleDautzenberg** [comment]
Eens, voor nu voldoende. Straks inderdaad linken aan de 0-pagina.
