### ISSUE TITLE
Als inwoner wil ik vinkjes bij alle stappen zien

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#389]
zodat ik zeker weet dat ik niets ben vergeten.

Dus ook bij Extra's. #306 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
Volgensmij is deze inmiddels opgelost

**Comment by MichelleDautzenberg** [comment]
Hoe krijg ik bij Overig een vinkje?

**Comment by bbrands02** [comment]
@MichelleDautzenberg Er is dus nog een lopende discussie of we "overig" gaan gebruiken in de huwelijksplanner. Het was er nu even ingezet als voorbeeld omdat er vragen waren of we nu wel zoveel menu items in de huwelijksplanner willen hebben. Melding, betaling en naamgebruik is er nu in geschoven maar dit zal waarschijnlijk nog veranderen. 

Daarom dat ik "overig" even buiten het dashboard scherm heb gelaten.

**Comment by MichelleDautzenberg** [comment]
Duidelijk, aangezien die stap toch waarschijnlijk anders gaat worden laat ik dat dan wel even achterwege. FIjn dat het nu bij Extra's wel werkt. Ik sluit deze.
