### ISSUE TITLE
Als inwoner wil ik zien in welke stap ik zit

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#390]
zodat ik beter kan navigeren door de stappen.

Wij denken aan een ring om het bolletje heen. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by CMasselink** [comment]
Close want dubbel met #337
