### ISSUE TITLE
Als inwoner wil ik mijn Melding Voorgenomen huwelijk in de huwelijksplanner doen zodat ik alles gemakkelijk in één (web)app kan afhandelen

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#391]
De huidige huwelijksplanner verwijst bij de Melding voorgenomen huwelijk naar een externe pagina. Dit zou in de huwelijksplanner zelf moeten kunnen.

**Comment by MichelleDautzenberg** [comment]
Dubbel met #86

**Comment by JeroenduC** [comment]
Omdat het dubbel is, afgesloten.
