### ISSUE TITLE
Als inwoner die aan het navigeren is door de huwelijksplanner wil ik niet afgeleid worden door animaties zodat ik rustig keuzes kan maken

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#392]
De animaties van de 'stappenbolletjes' bij het kiezen van een nieuwe stap mag weg.

**Comment by matthiasoliveiro** [comment]
Dus alleen als je inlogt (1 keer de animatie) en daarna niet meer?

**Comment by JeroenduC** [comment]
Graag beginnen met de animatie helemaal verwijderen. Ik denk dat dat al goed zat (en misschien beter dan één keer wel)

**Comment by JeroenduC** [comment]
Is anders dan eerst beschreven zin, maar voortschrijdend inzicht.

**Comment by matthiasoliveiro** [comment]
Geen animatie.

inschatten @rubenvdlinde

**Comment by JeroenduC** [comment]
Ik zie een groot gebrek aan springende bolletjes op dev. Issue op Done gezet.
