### ISSUE TITLE
Als inwoner wil ik na het starten van een nieuw proces een 'stap 0' pagina waarin mij wordt verteld wat ik moet gaan doen zodat ik zeker ben van wat ik allemaal moet gaan doen om mijn administratieve zaken af te handelen bij de Gemeente

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#394]

**Comment by JeroenduC** [comment]
Maak meteen duidelijk wat de gebruiker in deze (web)app kan doen en geef een checklist weer van alle stappen die gedaan moeten worden. De inwoner weet meteen waar hij/zij aan toe is en wat er moet gebeuren om het trouwen succesvol af te handelen.

**Comment by matthiasoliveiro** [comment]
Op het moment is het zo dat wanneer je niet ingelogd bent je op het locatie scherm een locatie kan kiezen en dan meteen kan inloggen en deze locatie kan reserveren.
Hier zit geen stap 0 tussen. Dit betekend dat er meerdere flows van inloggen zijn. 
@MichelleDautzenberg @DdeBruijn Ik denk dat we even moeten beschrijven wat de inlog flows zouden moeten zijn.

**Comment by MichelleDautzenberg** [comment]
Wat mij betreft is de info-pagina echt alleen een info-pagina en kan je vanuit daar niet direct door naar een stap in het proces. En is er dus maar één inlog-flow @JeroenduC Hoe denk jij hierover?

**Comment by JeroenduC** [comment]
Het idee was een pagina te maken die de gebruiker na het inloggen ziet, waarin beschreven wordt wat er allemaal moet gebeuren. Ik zal de opzet daarvoor toevoegen aan het issue.

**Comment by JeroenduC** [comment]
Opzet voor een tekst op de 'stap 0' pagina. Nog niet proefgelezen, maar geeft al wel een idee van wat er moet komen te staan.

Als je gaat trouwen moet je veel regelen. Om je wat overzicht te geven hebben we hieronder een lijstje gemaakt van alles wat je met de Gemeente moet regelen. Alles wat je al gedaan hebt vind je in het <link>overzicht<link>.
Kijk je liever een filmpje waar we alles uitleggen? Dat kan hier!

**Keuze maken tussen Huwelijk of Geregistreerd Partnerschap**
Jullie moeten een keuze maken of jullie een huwelijk of een geregistreerd partnerschap willen afsluiten. Als je nog niet weet welke keuze je moet maken kan je op de site van de Rijksoverheid lezen waar je rekening mee moet houden.
>> Maak type keuze

**Informatie van beide partners doorgeven**
We hebben gegevens nodig van beide partners om het huwelijk of het partnerschap te registreren. 
>> Vul partnerinfo in.

**Keuze maken tussen gratis, eenvoudig of ceremonieel trouwen**
<<is deze keuze relevant bij partnersschap?>>
Als jullie gaan trouwen zijn moet je kiezen tussen gratis, eenvoudig en ceremonieel trouwen. Dit bepaalt hoeveel keuze je hebt bij locaties, datums en trouwambtenaren. 
>> Maak keuze van het trouwen.

**Trouwdatum kiezen**
Jullie moeten kiezen wanneer je bij de Gemeente de plechtigheid wil laten voltrekken. De beschikbare data zijn afhankelijk van het type ceremonie (gratis, eenvoudig of ceremonieel).
>> Kies trouwdatum

**Trouwlocatie kiezen**
De keuze in trouwlocatie is afhankelijk van het type huwelijk (gratis, eenvoudig of ceremonieel). Als het type huwelijk de mogelijkheid biedt om een locatie te kiezen, is het nodig dat jullie aangeven waar jullie het huwelijk willen laten voltrekken.
>> Kies locatie

**Trouwambtenaar kiezen**
De trouwambtenaar is degene die het huwelijk gaat voltrekken. De keuze in trouwambtenaar is afhankelijk van het type huwelijk (gratis, eenvoudig of ceremonieel). Als het type huwelijk de mogelijkheid biedt om een trouwambtenaar te kiezen, is het nodig dat jullie aangeven welke trouwambtenaar jullie willen voor jullie ceremonie.
>> Kies trouwambtenaar

**Getuigen aanmelden**
Bij het trouwen of geregistreerde partnerschap is het wettelijk verplicht dat er minimaal twee getuigen aanwezig zijn, één voor elke partner. Er zijn maximaal <X> getuigen toegestaan bij <de Gemeente Utrecht/Almere/…>. 
>>>  Kies getuigen.

**Extra’s kiezen**
Het is mogelijk om extra opties te kiezen om je huwelijk extra feestelijk te maken, zoals bijvoorbeeld een trouwboekje als aandenken aan het huwelijk. 
>>>  Kies extra’s

**Melding voorgenomen huwelijk**
Voordat je gaat trouwen of een geregistreerd partnerschap aangaat is het wettelijk verplicht een melding voorgenomen huwelijk te gaan doen. Dit moet minimaal <x> dagen voordat de ceremonie voltrokken wordt. We hebben hier alles samengevat over de melding voorgenomen huwelijk.
>>> Melding doen

**Betaling doen**
Tenzij je voor een gratis huwelijk hebt gekozen moet je betalen voor je huwelijk. De kosten zijn afhankelijk van het type huwelijk wat je kiest.
>>> Doe de betaling

**Comment by matthiasoliveiro** [comment]
Actie: @JeroenduC  schets / wireframe als voorbeeld. 

Voorstel: combineer stap 0 met de checklist.

**Comment by JeroenduC** [comment]
![20200220_111015](https://user-images.githubusercontent.com/49227194/74924338-8c482f80-53d2-11ea-8758-9e8ec9ff2cb1.jpg)

Bij deze de wireframe met toevoeging (sorry, je moet hem even een kwartslag draaien, heb geprobeerd een gedraaide versie te uploaden maar dat is niet gelukt).

De roze nummers zijn wat extra opmerkingen, zie hieronder:

1) De normale header

2) De huidige navigatiebalk

3) De tekst. De [opgemaakte tekst heb ik even als Word bestand (voor de opmaak) in Git gezet.](https://github.com/VNG-Realisatie/huwelijksplanner/blob/master/documenten/Stap0.docx). De linkjes onder de kopjes hebben placeholder linkjes, maar volgens mij is het duidelijk waar ze naar verwijzen.

4) Elk kopje beginnen met het icoontje uit de navigatiebalk waar het over gaat. Dus als het gaat over de plechtigheid, de ringen. Als het gaat over de datum, de kalender. Etc. etc.

5) De checklist header. Maak van de header een link naar de checklist pagina. Maak van de list items een link naar de pagina van de app waar je de relevante gegevens kan invullen.

De volgende regels moeten er onder (zelfde als op checklist pagina):
- Ceremoniekeuze
- Informatie partner 1
- Informatie partner 2
- Plechtigheid
- Trouwdatum
- Trouwlocatie 
- Ambtenaar 
- Getuigen
- Melding Voorgenomen Huwelijk
- Betaling
- Extra's 

6) Bij een keuze die al gedaan is, een groen vinkje weergeven. 

7) Bij een keuze die nog moet en nog niet in een kritische periode zit, een zandlopertje (zoals op de checklist pagina). Wat een kritische periode is ga ik nog uitzoeken. Hou voor nu vier weken voor de geplande trouwdatum aan. Als er geen trouwdatum bekend is, dan is het dus altijd een zandlopertje.

8) Bij een keuze die nog moet en in een kritische periode zit, een rood bordje met uitroepteken er in (zoals op de checklist pagina). Wat een kritische periode is ga ik nog uitzoeken. Wat een kritische periode is ga ik nog uitzoeken. Hou voor nu vier weken voor de geplande trouwdatum aan. Als er geen trouwdatum bekend is, dan is het dus altijd een zandlopertje.

**Comment by rubenvdlinde** [comment]
Ik trek deze de sprint in omdat die vast zit (randvoorwaardelijk lijkt te zijn) voor een issue in de sprint

**Comment by JeroenduC** [comment]
Netjes. Gewoon goed. Mag gedeployed worden.

**Comment by JeroenduC** [comment]
Top. Op done gezet.
