### ISSUE TITLE
Als inwoner wil ik zien wat de gevolgen zijn van een keuze van plechtigheid

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#396]
zodat ik weet waarom er bijvoorbeeld ineens vinkjes komen te staan bij Locatie en Ambtenaar.

Hoe willen we dit:
- Onder de opties voor Eenvoudig Trouwen en Gratis Trouwen wil ik een zin hebben staan: "De gemeente kiest uw trouwlocatie en ambtenaar." 
- Onder de optie voor Trouwen/plechtigheid wil ik een zin hebben staan "U kiest zelf uw trouwlocatie en ambtenaar". 

Na te hebben gekozen voor een Eenvoudig of Gratis huwelijk komen er ook vinkjes te staan bij de stappen Locatie en Ambtenaar. Als je naar deze stappen gaat moet het direct duidelijk zijn wat er gekozen is én dat de keuze hier is gemaakt door de gemeente (dus niet pas onder Extra Uitleg knop). Hier dan een zin opnemen als: "Gratis huwelijken vinden altijd plaats op het Stadskantoor". 

Zie ook #393 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
Grappig genoeg sluit dit aan bij een bug report van onszelf waarin we spotten dat hier vroeger teksten voor waarden, we kunnen nu zelf even placeholder teksten plaatsen in lijn met het voorstel van @MichelleDautzenberg en die teksten kunnen dan later door Utrecht via het dashboard worden aangepast.

**Comment by MichelleDautzenberg** [comment]
Ik vind deze hier akkoord door het toevoegen van de teksten, mits #393 nog wordt opgepakt.
Ik vind het namelijk nog niet helemaal duidelijk wat je toegewezen locatie en ambtenaar is (nu worden alle locaties en ambtenaren nog getoond).
