### ISSUE TITLE
Als inwoner wil ik een getuige ook kunnen verwijderen of wijzigen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#397]
zodat ik fouten kan herstellen, een getuige die niet wilt kan vervangen of kan weglaten.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rjzondervan** [comment]
Technisch is dit nu mogelijk, echter, er loopt iets nog niet helemaal goed waardoor deze nog niet in review kan.

**Comment by bbrands02** [comment]
Reviewbaar op https://dev.huwelijksplanner.online/getuige

**Comment by MichelleDautzenberg** [comment]
Ik krijg nog een error als ik op Annuleer getuige druk?

**Comment by CMasselink** [comment]
@rubenvdlinde je hebt deze naar review geplaatst, wie moet er reviewen?

**Comment by rjzondervan** [comment]
Wanneer je een getuige invoert is het nu mogelijk om deze te annuleren. Wijzigen hebben we vooralsnog on hold gezet omdat het dan ongeveer evenveel werk is om de getuige te verwijderen en opnieuw in te voeren.

**Comment by CMasselink** [comment]
Getest op DEV. Daar werkt het inderdaad.
Moet nog wel doorgezet worden naar demo, daar werkt het nog niet. 
@rjzondervan kan ik deze sluiten en wordt het dan doorgezet naar demo?

**Comment by matthiasoliveiro** [comment]
Hertest net gedaan en is nu OK op Demo je kan hem sluiten @CMasselink

**Comment by CMasselink** [comment]
@matthiasoliveiro Ik heb het net ook getest op demo. Het verwijderen van een getuige geeft op demo een internal server error. Issue kan nog niet gesloten worden.
![image](https://user-images.githubusercontent.com/39768984/76242997-e13fce80-6237-11ea-85cc-826cd51fd7ce.png)

**Comment by matthiasoliveiro** [comment]
@CMasselink er gaat hier iets mis in de werk volg orde. Als jij hem goed keurt op Dev dan gaan we hem daarna pas deployen naar demo. Demo is echt een demo omgeving en geen test omgeving

**Comment by matthiasoliveiro** [comment]
We gaan hem deployen naar demo
