### ISSUE TITLE
Als ik een datum heb gekozen, blijf ik op de datum pagina en is mijn keuze niet zichtbaar

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#398]
**Beschrijving van de bug**
Ik kies een datum en kom dan weer op dezelfde pagina terecht. er staat wel een vinkje bij datum, maar het is onduidelijk wat ik heb gekozen en hij is ook niet verder gegaan naar de volgende stap. 

**Verwachting**
Dat mijn keuze onthouden wordt onder de datum pagina en dat ik naar de volgende stap wordt geleid. 

**Bug**
Beschrijf wat het onverwachte resultaat was?

**Comment by rjzondervan** [comment]
Dit issue zou nu opgelost moeten zijn, met die kanttekening dat er in oude verzoeken nu fouten kunnen zijn ontstaan. @MichelleDautzenberg zou je willen hertesten om te kijken of dit nu naar behoren werkt?

**Comment by MichelleDautzenberg** [comment]
De datum houdt hij nu goed vast, maar de tijd die ik heb gekozen niet!

**Comment by matthiasoliveiro** [comment]
Dit is een nieuwe bug laten we deze sluiten en en een nieuwe bug openen. Dat zorgt er voor dat we het overzicht behouden.

**Comment by MichelleDautzenberg** [comment]
Top, dan kan deze gesloten.
