### ISSUE TITLE
Als ik eerst een Eenvoudig of Gratis huwelijk kies, en dan besluit te wisselen voor een Uitgebreid huwelijk dan wordt de locatie en ambtenaar nog vastgehouden van mijn vorige keuze

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#399]
**Beschrijving van de bug**
Als ik eerst een Eenvoudig of Gratis huwelijk kies, dan wordt de locatie en ambtenaar voor mij gekozen. Echter, als ik dan besluit te wisselen voor een Uitgebreid huwelijk, dan wordt de locatie en ambtenaar nog steeds vastgehouden van mijn vorige keuze (Terwijl ik nu wel zelf mag kiezen).

**Verwachting**
Ik verwacht dat het vinkje bij locatie en ambtenaar verdwijnt als ik wissel naar een ceremonieel huwelijk, zodat ik weet dat ik deze nu wel kan kiezen. 

**Bug**
Beschrijf wat het onverwachte resultaat was?

**Comment by matthiasoliveiro** [comment]
Hier moet ook een goede melding bij (flash messages) dat locatie en ambtenaar vervallen.

**Comment by CMasselink** [comment]
Eens met Matthias, je wilt de burger wel informeren dat door een nieuw type huwelijk, er zaken opnieuw gekozen moeten worden.

**Comment by rjzondervan** [comment]
Op dit moment is de status van dit issue dat de locatie en ambtenaar worden geleegd wanneer we overstappen naar uitgebreid trouwen, echter blijven de vinkjes op dit moment nog hangen. Daarom is dit issue nog niet reviewbaar.

**Comment by rjzondervan** [comment]
Hier draait nu een deploy voor. Als de deploy er doorheen is kan deze gereviewd worden.

Flow: open een nieuw verzoek, en kies voor een gratis of eenvoudig huwelijk. Ga daarna terug naar de plechtighedenpagina en kies dan voor uitgebreid trouwen. Locatie en Ambtenaar worden nu vrijgegeven en de vinkjes verdwijnen.

**Comment by MichelleDautzenberg** [comment]
Opgelost, wel #467 aangemaakt.
