### ISSUE TITLE
Als ik geen openstaande verzoeken heb, krijg ik toch de Mijn verzoeken pagina te zien

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#400]
**Beschrijving van de bug**
Als ik nu geen openstaande verzoeken heb, krijg ik toch de Mijn verzoeken pagina te zien en de knop 'ik wil toch liever een nieuw verzoek starten'

**Verwachting**
Dat ik de Mijn verzoeken pagina niet te zien krijg

**Bug**
Beschrijf wat het onverwachte resultaat was?

**Comment by rubenvdlinde** [comment]
Simpel geval van bij count 0 meteen een nieuw verzoek opstarten

**Comment by rjzondervan** [comment]
Hiervoor is nu een oplossing geïmplemteerd. @MichelleDautzenberg zou je deze willen hertesten?

**Comment by MichelleDautzenberg** [comment]
Akkoord! Lijkt logisch zo.
