### ISSUE TITLE
Als ik een partner toevoeg gaat hij niet automatisch naar de volgende stap

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#401]
**Beschrijving van de bug**
Als ik een partner toevoeg gaat hij niet automatisch naar de volgende stap (zoals bij andere stappen wel gebeurt). 

**Wat heb ik gedaan**
Beschrijf in welke situatie (bijvoorbeeld in welk scherm) je de bug bent tegen gekomen:

**Verwachting**
Beschrijf wat je had verwacht als resultaat?

**Bug**
Beschrijf wat het onverwachte resultaat was?

**Comment by rjzondervan** [comment]
Volgens ons zou dit issue inmiddels opgelost moeten zijn. Zou je hem willen hertesten?

**Comment by MichelleDautzenberg** [comment]
Hij gaat nu inderdaad door naar de volgende stap. Exacte tekst van bevestigingsbericht moet nog eens naar gekeken worden, maar dat gebeurt in #315 nog.
