### ISSUE TITLE
Als inwoner wil ik kunnen zien welke getuige voor welke partner is

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/huwelijksplanner#402]
zodat direct zichtbaar is dat ik mij getuigen goed heb geregeld.

Nu zie je wel de getuigen maar niet bij welke partner deze horen.
nb. ook de medewerker heeft hier volgens mij behoefte aan.

**Comment by DdeBruijn** [comment]
Is het belangrijk voor wie welke getuige is? Stellen kunnen ook samen voor een getuige kiezen b.v. omdat ze elkaar via die persoon hebben leren kennen. Is dit uit interviews gekomen of?

**Comment by rjzondervan** [comment]
Hiervoor moeten we in de instemmingsverzoeken ook gaan bijhouden voor wie het verzoek gedaan wordt. Op zich lijkt me dat geen onredelijke actie, maar ik kan me ook iets bij @DdeBruijn's vraag voorstellen.

**Comment by rubenvdlinde** [comment]
Is het juridisch niet zo dat je getuigd voor een persoon? althans op de akte?

**Comment by rjzondervan** [comment]
Deze kan nu gereviewd worden.

Hertest: maak een nieuw verzoek aan, definieer een partner, voer getuigen in.

**Comment by MichelleDautzenberg** [comment]
Procesteam heeft dit gecheckt, maar je kiest **2 tot 4 getuigen per koppel.** Er wordt nergens vastgelegd welke getuige bij welke partner hoort. Ik stel daarom voor om deze functionaliteit uit de huwelijksplanner te halen! @PatrickCastenmiller eens?

**Comment by PatrickCastenmiller** [comment]
Ja, mee eens.

**Comment by MichelleDautzenberg** [comment]
Vandaag nogmaals bij de medewerkers BZ gecheckt en hier wordt echt niets mee gedaan. ik maak daarom een US aan om dit eruit te halen.
