### ISSUE TITLE
Als procesteam wil ik een (of meerdere) sessie(s) organiseren met medewerkers

### ISSUE THREAD

**Issue by DdeBruijn** [VNG-Realisatie/huwelijksplanner#403]
zodat we het medewerkerportaal kunnen bekijken en hier input over op kunnen halen.

**Comment by DdeBruijn** [comment]
Verzoek voor een afspraak bij Burgerzaken ingeschoten bij de teammanager.

**Comment by DdeBruijn** [comment]
Reminder gestuurd naar teammanager Burgerzaken om een sessie in te plannen.
@matthiasoliveiro @rubenvdlinde wanneer is de verwachting dat het medewerkersportaal in ieder geval te reviewen is op locatie?

**Comment by matthiasoliveiro** [comment]
Hi Daphne (@DdeBruijn),
Vanaf woensdag is het beschikbaar. 
Als ik zo naar de Epic planning kijk wilde we komende sprint met medewerkers gaan zitten.

**Comment by DdeBruijn** [comment]
Top @matthiasoliveiro, handig om te weten als de afspraak ingepland wordt. Verwacht nog niet op heel korte termijn aangezien ik al een reminder moest sturen.

**Comment by MichelleDautzenberg** [comment]
Deze is te vaag. Nieuwe userstories aanmaken als we weten waarover we specifiek een sessie willen organiseren.
