### ISSUE TITLE
Inloggen als tweede partner resulteert in error 500

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/huwelijksplanner#404]
**Beschrijving van de bug**
Wanneer ik klik op "uw partner laten inloggen" krijg ik een 500-status terug met de titel "Undefined index: givenName".

**Wat heb ik gedaan**
Beschrijf in welke situatie (bijvoorbeeld in welk scherm) je de bug bent tegen gekomen:
Ingelogd als willekeurig persona, doorklikken naar partner, klik op "uw partner laten inloggen"

**Verwachting**
Hier zouden we naar Digispoof geleid moeten worden om de tweede partner te laten inloggen

**Bug**
Foutmelding met titel "Undefined index: givenName".

**Comment by rjzondervan** [comment]
Deze is wat mij betreft opgelost, maar als iemand de test even wil herhalen, gezien ik zelf het probleem heb opgelost, zou dat heel fijn zijn.

**Comment by DdeBruijn** [comment]
opgelost
