### ISSUE TITLE
Als ik een Extra kies krijg ik kort allemaal code in beeld en dan gaat het door naar de volgende stap

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#406]
**Beschrijving van de bug**
Als ik een Extra kies krijg ik kort allemaal code in beeld, dan het vinkje en dan gaat het door naar de volgende stap.

**Verwachting**
Als ik een Extra kies krijg ik het vinkje in beeld en dan blijf ik op de Extra's pagina om nog meer Extra's te kunnen kiezen.

**Comment by rjzondervan** [comment]
Bugje is er van de week ingeslopen tijdens het fixen van een andere bug. Inmiddels is een fix klaargezet voor de volgende iteratie.

**Comment by rjzondervan** [comment]
Deze is inmiddels als het goed is opgelost. Echter, het meldingenproces heeft nog een gelijkaardig probleem, ware het niet dat die flow nog grotendeels ingeregeld moet worden.

**Comment by rubenvdlinde** [comment]
Oke, maar dan kunnen we deze wat mij betreft inderdaad sluiten
