### ISSUE TITLE
Als inwoner wil ik het proces van het doen van een melding op elk moment kunnen afbreken en weer bij het verzoek/registratie terecht komen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#410]
zodat ik de overige onderdelen van mijn huwelijk weer verder kan plannen en niet gevangen zit in het scherm voor het doen van een melding.

**Comment by MichelleDautzenberg** [comment]
Dit is al opgelost met een terugknop vanuit de melding.
