### ISSUE TITLE
De URL verwijzingen naar de github repository en docker hub werken niet op de redoc pagina van de componenten

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#412]
**Beschrijving van de bug**
De urls verwijzen naar de redoc pagina i.p.v. naar de github pagina en docker hub pagina:
![afbeelding](https://user-images.githubusercontent.com/39768984/74249067-e2d5af80-4ce8-11ea-9da9-fcce29c9d4ee.png)
Dit gaat voor alle componenten fout. Lijkt dus iets in deployement te zijn

**Verwachting**
Correcte links naar github repostory (gemeente utrecht github) en docker hub (gemeente utrecht omgeving)

**Comment by rubenvdlinde** [comment]
@rjzondervan deze hadden we zelf ook als onverklaarbaar ding gespot. Als je er nog eens naar zou willen kijken zou het mooi zijn. Maar als je er meer dan 30 min voor nodig hebt pak ik hem graag over.

**Comment by rjzondervan** [comment]
Ik pak deze vanmiddag heel even op, maar ik ga er niet vanuit dat ik in 30 minuten een mogelijkheid vind dit op te lossen.

**Comment by rjzondervan** [comment]
Ik ga er nu niet uitkomen, maar in ieder geval een paar constateringen:
- Dit issue treed alleen op in productieomgevingen
- Het deployen naar productieomgevingen heeft geen effect op de openapi.yaml in de repository, omdat deze bij in de CI/CD straat niet gecommit wordt.

**Comment by CMasselink** [comment]
Ìs al opgelost in #438
