### ISSUE TITLE
Als medewerker wil ik inzage in mijn openstaande taken (functionaliteit)

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#418]
zodat ik weet wat ik nog moet doen voor een huwelijk.

In vervolg op de gemaakte schermen in #54 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
Lossen we deze niet op met #435 ? If so dan kan die wat mij betreft naar review

**Comment by MichelleDautzenberg** [comment]
Is dubbel emt #435 dus hierbij sluit ik hem.
