### ISSUE TITLE
Als beheerder van de trouwplanner wil ik kunnen configureren welke tarieven van toepassing zijn (scherm)

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#42]
zodat we hierin als gemeente flexibel kunnen zijn. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by rubenvdlinde** [comment]
Het is nu wel technisch (via de api) mogelijk om producten te beheren. Dus in theorie kan prijs wijzigen ook gewoon (in het verleden hadden we daar ook een formulier voor binnen de trouwplanner zelf). Dus we zouden dit kunnen mee nemen in het dashboard. Sterker nog dit was een van de gedachten over waarom we een dashboard wouden.

**Comment by rubenvdlinde** [comment]
@bbrands02 Gaat hier in stap 1 even om de schermen

**Comment by MichelleDautzenberg** [comment]
Scherm voor nu akkoord.
