### ISSUE TITLE
Als developer wil ik zaaktypen in de OpenZaak catalogus voor de huwelijksplanner

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#421]
zodat ik deze deelprocessen zaakgericht kan afhandelen. 

Aan te maken zaaktypen: 
- Melding voorgenomen huwelijk
- Aanvraag eigen Babs (Beedigd en niet-beedigd)
- Aanvraag eigen locatie

Extra controle recordmanager nodig op archiefgegevens #428 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Melding voorgenomen huwelijk
UUID 28e05004-1754-48cf-bb1e-15525ebdeb0b 
Heeft als statussen: 1) Ontvangen, 2) In behandeling genomen, 3) Verwerkt
Heeft als resultaten: Verwerkt (https://selectielijst.openzaak.nl/api/v1/resultaten/0fb921b0-4752-4263-8d5e-554b2599dadf) en Ingetrokken (https://selectielijst.openzaak.nl/api/v1/resultaten/ac98caff-760b-46e5-bcea-46dfe8b625f8)
Heeft als rol: Behandelaar

**Comment by MichelleDautzenberg** [comment]
**Eigen locatie**
UUID 
411c9246-df08-4be2-859c-a14e497f472a 
Heeft als statussen: 1) Ontvangen, 2) In behandeling genomen, 3) Afgehandeld
Heeft als rol: Behandelaar
Heeft als eigenschap: Trouwdatum
Heeft als resultaten: Goedgekeurd (https://selectielijst.openzaak.nl/api/v1/resultaten/b58eb4af-95a0-4148-907b-3732def8c751), Afgewezen (https://selectielijst.openzaak.nl/api/v1/resultaten/e6089c84-1722-4342-b24c-888b7d6fcc22) en Ingetrokken (https://selectielijst.openzaak.nl/api/v1/resultaten/0e8e7833-e491-44e2-8770-fd23f3f249b0)

**Comment by MichelleDautzenberg** [comment]
**Eigen Babs (niet beëdigd)**
UUID 7110435b-7cd0-4c5c-a14d-110003947279
Heeft als statussen: 1) Ontvangen, 2) In behandeling genomen, 3) Afgehandeld
Heeft als rol: Behandelaar
Heeft als eigenschap: Trouwdatum
Heeft als resultaten: Goedgekeurd (https://selectielijst.openzaak.nl/api/v1/resultaten/b58eb4af-95a0-4148-907b-3732def8c751), Afgewezen (https://selectielijst.openzaak.nl/api/v1/resultaten/e6089c84-1722-4342-b24c-888b7d6fcc22) en Ingetrokken (https://selectielijst.openzaak.nl/api/v1/resultaten/0e8e7833-e491-44e2-8770-fd23f3f249b0)

**Comment by MichelleDautzenberg** [comment]
**Eigen Babs (beëdigd)**
UUID a6f126ac-3710-4e2f-8aca-585fc23acc13
Heeft als statussen: 1) Ontvangen, 2) In behandeling genomen, 3) Afgehandeld
Heeft als rol: Behandelaar
Heeft als eigenschap: Trouwdatum
Heeft als resultaten: Goedgekeurd (https://selectielijst.openzaak.nl/api/v1/resultaten/b58eb4af-95a0-4148-907b-3732def8c751), Afgewezen (https://selectielijst.openzaak.nl/api/v1/resultaten/e6089c84-1722-4342-b24c-888b7d6fcc22) en Ingetrokken (https://selectielijst.openzaak.nl/api/v1/resultaten/0e8e7833-e491-44e2-8770-fd23f3f249b0)

**Comment by matthiasoliveiro** [comment]
Ik heb even een MD aangemaakt als document:
https://github.com/VNG-Realisatie/huwelijksplanner/blob/master/documenten/techniek/zaaktypen.md
dan kunnen we dit issue ook sluiten.

**Comment by MichelleDautzenberg** [comment]
Zaaktypen toegevoegd. Resultaattypen moeten denk ik nog wel gewijzigd, daarom blijft #428  nog open.
