### ISSUE TITLE
EPIC: Als medewerker wil ik huwelijks-zaken kunnen afhandelen in de huwelijksplanner

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#422]
zodat ik hiervoor niet een apart zaakafhandelinterface hoef te gebruiken. 

het betreft zaken uit OpenZaak van de zaaktypen:
- Naamgebruik #479 
- Eigen locatie #142 
- Melding voorgenomen huwelijk #482
- Eigen Babs (beedigd #480 en niet beedigd #481)

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Dit doen we via Camunda en bptl. 
Zie BPMN model 'Zaak behandelen' in de map BPMN.
In het model wordt gebruik gemaakt van 3 topics (initialize-zaak, set-result en close-zaak), waarvan je [hier](https://bptl.utrechtproeftuin.nl/taskmappings/) kan vinden wat minimaal nodig is aan metadata om deze stappen uit te kunnen voeren.

**Comment by CMasselink** [comment]
We hebben hier nu separate userstory's voor. De epic gaan we sluiten, we gaan het label medewerker gebruiken.
