### ISSUE TITLE
Contactgegevensformulier blijft zichtbaar op pagina Partners, ook al heb ik mijn contactgegevens net doorgegeven

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#437]
Zie ook #298 

**Beschrijving van de bug**
Ik heb op de pagina Partners mijn eigen contactgegevens doorgegeven (email en telefoonnummer). Deze worden dan onthouden, maar het contactgegevensformuliertje blijft eronder staan.
![image](https://user-images.githubusercontent.com/48316239/75249332-678af800-57d6-11ea-8694-2ea86b17c684.png)

Bij de partner werkt het anders, want als ik daar de contactgegevens invoer, dan gaat het formuliertje vervolgens ook weg. Dat is duidelijker. Al mist bij beiden dan een knop om contactgegevens te wijzigen. 

**Verwachting**
Ik vul de contactgegevens in en klik op opslaan.
De contactgegevens komen onder Adres en Contact te staan.
Het formuliertje is nu weg, maar er is een button 'Contactgegevens wijzigen' bij gekomen.

**Comment by rjzondervan** [comment]
@bbrands02 zou jij een dergelijk modal ook kunnen toevoegen voor de aanvragende partner (zij het zonder de mogelijkheid om de naam te wijzigen) zodat we dit formulier ook kunnen opnemen?

**Comment by rjzondervan** [comment]
Dit functioneert nu weer, echter, om alle logica goed uit te voeren moeten we even wachten op een deploy van de huwelijksplanner UI, anders resulteert bewerken met de modal in een 500.

**Comment by MichelleDautzenberg** [comment]
Ik heb het getest in dev en nu werkt het wel goed.
