### ISSUE TITLE
Linkjes binnen de technische documentatie worden niet goed gezet in de deploy

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#438]
**Beschrijving van de bug**
de linkjes onderstaand gaan bij alle documentatie fout. Er zit ergens een algemeen probleem

![](https://user-images.githubusercontent.com/39768984/74239234-b49ba400-4cd7-11ea-983b-0e7b3e235872.png)

**Wat heb ik gedaan**
de linkjes verwijzen nu niet naar de juiste plaats dus als je er nu op klikt krijg je niets te zien.

**Verwachting**
De juiste links

**Bug**
Beschrijf wat het onverwachte resultaat was?

**Comment by rubenvdlinde** [comment]
Hier is inmiddels is boventafel waar dit vandaan komt, er worden een aantal variabelen niet gezet op de kubernetes omgevingen. Omdat de openapi.yaml locaal wordt gemaakt verklaard dat ook met het verschil. Er is inmiddels een fix voor (variale zetten) en die moet over alle deployments worden uitgerold.
