### ISSUE TITLE
Als medewerker wil ik voor een inwoner de reservering kunnen wijzigen en annuleren (functionaliteit)

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#439]
zodat dit ook telefonisch of aan de balie kan gebeuren. 

Als vervolg op de gemaakte schermen in #231 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by CMasselink** [comment]
Wordt opgelost in #484
