### ISSUE TITLE
Als medewerker wil ik een stabiele demo omgeving voor het medewerkersportaal

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#440]
zodat er geen fouten zijn tijdens een demo.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
We hebben de omgevingen afgelopen week verder uit elkaar getrokken en versimpeld.

Voor het medewerkers portaal is nu db.huwelijksplanner.nl beschikbaar als demo omgeving en db.dev.huwelijksplanner als development omgeving. Bijde achter wachtwoord en wachtwoord is per pm op te vragen (zetten we liever niet publiek in git)

**Comment by rubenvdlinde** [comment]
Review verzoek aan @MichelleDautzenberg om te kijken of ze op bovenstaande link kan inloggen en de schermen kan vinden (zou je in één keer op moeten uitkomen)

**Comment by MichelleDautzenberg** [comment]
Yes, alles weer goed bereikbaar
