### ISSUE TITLE
Opvoeren email adres bij ingelogde gebruiker leid tot een 500

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#452]
**Beschrijving van de bug**
Opvoeren email adres bij ingelogde gebruiker leid tot een 500

**Wat heb ik gedaan**
Start een nieuw verzoek en ga naar het partner scherm. vul hier je email adres in en sla op

**Verwachting**
door gaan in de flow

**Bug**
Zie pic
![image](https://user-images.githubusercontent.com/36506861/75972792-4dd36a00-5ed4-11ea-8904-23fa76bfa524.png)

**Comment by matthiasoliveiro** [comment]
Hertest op Dev NOK

zie screenshot:
![image](https://user-images.githubusercontent.com/36506861/76201557-bcc20300-61f3-11ea-81de-216d2342bddf.png)

**Comment by rjzondervan** [comment]
Probleem lag elders, en zou inmiddels verholpen moeten zijn.

**Comment by matthiasoliveiro** [comment]
hertest OK
