### ISSUE TITLE
Product informatie plechtigheid is niet volledig

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#453]
**Beschrijving van de bug**
Product informatie plechtigheid is niet volledig

**Wat heb ik gedaan**
Ga naar het plechtigheden scherm:
![image](https://user-images.githubusercontent.com/36506861/75973194-10231100-5ed5-11ea-84c8-fbe055814198.png)
en dan naar meer info:
![image](https://user-images.githubusercontent.com/36506861/75973208-174a1f00-5ed5-11ea-8f8b-b2aa4e3965e6.png)

**Verwachting**
Een volledige product omschrijving

**Bug**
Er staat nu 1 woord.

**Comment by SamiJamal** [comment]
Hier moet een tekst voor komen @matthiasoliveiro

**Comment by bbrands02** [comment]
Zou iemand hier een tekst voor kunnen aanleveren? Ik heb het hier over de beschrijvingen van de plechtigheden.

**Comment by DdeBruijn** [comment]
Wij kennen geen 'pakketten' in Almere. De prijs wordt bepaald door combinatie dag/tijd/locatie.
Tekst kan dus het beste uit Utrecht komen.

**Comment by MichelleDautzenberg** [comment]
Deze teksten zouden voor Utrecht van toepassing zijn:

**Gratis trouwen**
Maandagochtend om 10.00 uur of om 10.30 uur kunt u gratis trouwen op het stadskantoor. 
De wachtlijst voor gratis trouwen is ongeveer 9 maanden. 
U trouwt zonder ceremonie (5-10 minuten).
U trouwt in een kleine trouwruimte op de 6e etage van het stadskantoor.
Er kunnen maximaal 10 personen naar binnen, dit is inclusief het bruidspaar, de getuigen en een eventuele fotograaf.
De trouwambtenaar houdt geen toespraak en heeft vooraf geen contact met u.
Een afspraak voor eenvoudig en gratis trouwen kan pas worden gemaakt als u uw voorgenomen huwelijk al gemeld hebt.

**Eenvoudig trouwen:**
Mogelijk op maandag 11.00 uur en 11.30 uur en dinsdag, woensdag en vrijdag om 10.00 uur, 10.30 uur, 11.00 uur of 11.30 uur.
U trouwt zonder ceremonie (5-10 minuten).
U trouwt in een kleine trouwruimte op de 6e etage van het stadskantoor.
Er kunnen maximaal 10 personen naar binnen, dit is inclusief het bruidspaar, de getuigen en een eventuele fotograaf.
De trouwambtenaar houdt geen toespraak en heeft vooraf geen contact met u.
De wachtlijst voor eenvoudig trouwen is ongeveer 3 maanden.
Een afspraak voor eenvoudig en gratis trouwen kan pas worden gemaakt als u uw voorgenomen huwelijk al gemeld hebt.

**Ceremonie:**
Mogelijk op een door u gekozen dag en tijdstip.
U trouwt in één van de beschikbare locaties of regelt een eigen locatie.
De trouwambtenaar houdt een toespraak en heeft vooraf contact met u. 
Een eigen trouwambtenaar (reeds beëdigd of nog niet beëdigd) is ook mogelijk,

**Comment by CMasselink** [comment]
@rubenvdlinde je hebt deze userstory naar in progress gezet, wie moet er reviewen?

**Comment by matthiasoliveiro** [comment]
@MichelleDautzenberg leverde tekst aan maar ik denk dat @JeroenduC het ook kan

**Comment by MichelleDautzenberg** [comment]
Kan de tekst anders uitgelijnd worden? Bijv. uitgevuld?
Want nu ziet het er niet heel mooi uit zo in het midden uitgelijnd te hebben.

**Comment by matthiasoliveiro** [comment]
Laten we even bekijken wat je waar wil hebben. Als we alle informatie hier neerzetten dan is er geen noodzaak tot een detail pagina. Deze heb je nu wel.

Laten we een nieuw issue openen met de vraag wat je waar wil hebben en dan meteen de vormgeving mee te nemen.

**Comment by matthiasoliveiro** [comment]
Besproken met Michelle er is een nieuw issue voor gebruik van de detail pagina in relatie met de frontpage. #468
