### ISSUE TITLE
Als product owner wil ik weten hoe we omgaan met de verschillende kosten van een uitgebreide trouwplechtigheid op verschillende locaties

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#457]
omdat hier nu één prijs voor wordt getoond, terwijl gemeenten daarin verschillende prijzen voor verschillende locaties hanteren. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
In Almere wordt de prijs bepaald op basis van tijd/dag/locatie. 
In Utrecht op basis van locatie.

**Comment by DdeBruijn** [comment]
Voorbeeld Almere uit #317 
Maandag 9.00 en 9.30 uur (zie ook onderstaande informatie) | gratis | n.v.t.
Werkdagen 9.00, 10.00 en 11.00 uur | € 185,25 | € 317,55
Werkdagen 12.00, 13.00, 14.00, 15.00 en 16.00 uur | € 332,95 | € 465,25
Werkdagen 17.00, 18.00 en 19.00 uur | € 480,60 | € 612,90
Werkdagen op een ander tijdstip (in overleg met Burgerzaken) | niet mogelijk | € 1017,60
Zaterdag 11.00, 12.00, 13.00 en 14.00 uur | € 749,05 | € 881,35
Zaterdag op een ander tijdstip en locatie buiten stadhuis (in overleg met Burgerzaken) | niet mogelijk | € 1017,60
Toeslag bij huwelijk of geregistreerd partnerschap op locatie | 132,30 |  
Toeslag bij huwelijk of geregistreerd partnerschap op andere tijdstippen dan bovenstaande tijdstippen | € 268,55

**Comment by MichelleDautzenberg** [comment]
Technisch mogelijk, vraag is hoe beheerbaar dit is. 
Hangt samen met #434

**Comment by CMasselink** [comment]
Beheer blijkt uit review van #434, daarom deze gesloten
