### ISSUE TITLE
Flash messages hebben geen tekst

### ISSUE THREAD

**Issue by rjzondervan** [VNG-Realisatie/huwelijksplanner#459]
**Beschrijving van de bug**
De flash messages op de devomgeving van huwelijksplanner.online hebben op dit moment geen tekst

**Wat heb ik gedaan**
Open de huwelijksplanner op devomgeving, log in en start een nieuw verzoek. Kies vervolgens tussen huwelijk en partnerschap, een locatie of ambtenaar (of, for that matter, doe iets anders dat een stap afsluit).

**Verwachting**
Een flash message met tekst dat x (type, locatie of ambtenaar) is ingesteld

**Bug**
Ik zie een flashmessage slechts bestaande uit een vinkje

**Comment by matthiasoliveiro** [comment]
Hertest OK
