### ISSUE TITLE
Als beheerder van de trouwplanner wil ik kunnen configureren wanneer en welke automatische reminders, notificaties en bevestigingsmails worden verstuurd

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#46]
zodat we hierin per gemeente flexibel zijn. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by rubenvdlinde** [comment]
Dit is nu nog niet configureerbaar, maar ik vraag me ook even af of dit niet verbonden is aan de gedachte over een procesengine

**Comment by CMasselink** [comment]
ER zijn al losse userstory's voor
