### ISSUE TITLE
Het opvragen van resources op het locatiecomponent leidt tot een 500 Internal Server Error

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#460]
**Beschrijving van de bug**
Het opvragen van resources op het locatiecomponent via een GET request leidt tot een 500 Internal Server Error.

**Wat heb ik gedaan**
Voer via Postman of web browser, zonder API credentials, een get request uit op bijvoorbeeld:
https://lc.huwelijksplanner.online/accommodations

**Verwachting**
Bij afwezigheid API key:
Een 401 not authorised melding vanwege het niet opgeven van een API key.

**Bug**
Een 500 internal server error

**Comment by rjzondervan** [comment]
Deze zit 'm in een afwezige maxdepth-assertion. Een update hiervoor is reeds voorbereid

**Comment by rjzondervan** [comment]
net uitgerold, zie ook nu de dev-omgeving

**Comment by CMasselink** [comment]
@rjzondervan Door de uitrol?? krijg ik op zowel dev als demo nu deze 404:
![afbeelding](https://user-images.githubusercontent.com/39768984/76777032-e35ddc00-67a7-11ea-85b5-fb9f162dc8b1.png)

Ook lc.huwelijksplanner.online geeft deze melding, evenals lc.dev.huwelijksplanner.online

**Comment by rjzondervan** [comment]
hum, dat is niet de bedoeling, ik ga even kijken, waarschijnlijk bij uitrollen een instelling niet goed gezet.

**Comment by rjzondervan** [comment]
Oke, nieuwe deploy gedaan, en nu zou het wel normaal moeten werken... Waar dit misgegaan is... Ik zou het eerlijk gezegd niet weten, alle instellingen bleken al correct te staan.

**Comment by CMasselink** [comment]
Is opgelost. Kan gedeployed worden
