### ISSUE TITLE
Het agendacomponent geeft een 502 bad gateway

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#461]
**Beschrijving_ van de bug**
Het agendacomponent geeft een 502 bad gateway

**Wat heb ik gedaan**
Open https://ac.huwelijksplanner.online/ in een browser.

**Verwachting**
Redoc documentatie van het agendacomponent

**Bug**
502 bad gateway

**Comment by rjzondervan** [comment]
Dit werd veroorzaakt door een foutje in een deploy: in plaats van de managed database die we hebben ingericht voor dit component probeerde het component een niet bestaande pod voor de database aan te roepen. Dit is nu hersteld en het component is weer online.

**Comment by CMasselink** [comment]
Opgelost
