### ISSUE TITLE
2 teksten door elkaar bij stap Locatie na wisselen van Plechtigheid

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#467]
**Beschrijving van de bug**
Een heldere omschrijving van de bug
![image](https://user-images.githubusercontent.com/48316239/76318723-6ed5f980-62de-11ea-9ae3-a7d63626a2d9.png)

**Wat heb ik gedaan**
Als ik wissel van Gratis/Eenvoudig naar Uitgebreide ceremonie krijg ik bij de stap Locatie bovenstaande tekst in beeld.

**Comment by rubenvdlinde** [comment]
Dubbel met #451
