### ISSUE TITLE
Als beheerder van de trouwplanner wil ik kunnen configureren welke termijnen binnen het proces van toepassing zijn

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#47]
zodat we hierin per gemeente flexibel kunnen zijn. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by rubenvdlinde** [comment]
In theorie laat de manier waarop de huwelijks resource is opgezet dit toe (tis een parameter) maar dan moeten we daar (binnen het dashbaord?) wel een interface voor bedenken.

**Comment by rubenvdlinde** [comment]
@bbrands02 Gaat hier in stap 1 even om de schermen

**Comment by CMasselink** [comment]
@bbrands02 hier zijn toch al dingen voor gedaan?

**Comment by MichelleDautzenberg** [comment]
Hier zijn al meerdere US over die specifieker zijn toegelicht: #39 #41 #155 
Relateert in kleine mate ook tot #141 #228 #227 

Daarom zal ik deze meer generieke US sluiten.
