### ISSUE TITLE
Foutmelding bij knop 'Aanvraag indienen' onder stap 'Checklist'

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#471]
Omgeving: dev.huwelijksplanner.online

Stap 1: Log in en doorloop de stappen tot de stap 'Checklist'
Stap 2: Druk op de knop: 'Aanvraag Indienen'
![image](https://user-images.githubusercontent.com/49227194/76444285-03feee00-63c4-11ea-9746-bbbb59dfc012.png)

Verwacht resultaat: Ik krijg een bericht over mijn aanmelding (gelukt, of ik mis nog wat gegevens, of iets dergelijks)
Daadwerkelijk resultaat: Ik krijg een foutmelding (zie hieronder):

![image](https://user-images.githubusercontent.com/49227194/76444380-26910700-63c4-11ea-9c4d-23ab33588734.png)

**Comment by JeroenduC** [comment]
@matthiasoliveiro :Ik was vergeten hem in de actuele sprint te zetten gister. Hopelijk staat het issue nu goed.

**Comment by rjzondervan** [comment]
Dit functioneert nu weer zo lang er een e-mail adres is ingevoerd voor de aanvrager. Anders komt er een fout terug van de berichtservice.

Ik kan nu een voorwaarde inregelen zodat er geen bericht wordt gestuurd als er geen e-mail adres is, maar ik denk dat het beter is om het indienen van de aanvraag te blokkeren als er geen e-mail adres is ingevuld.

**Comment by rjzondervan** [comment]
Ook het afvangen is intussen gerealiseerd

**Comment by JeroenduC** [comment]
Geen foutmelding meer! 

En inderdaad, beter om het indienen van de aanvraag te blokkeren als er geen e-mail adres is ingevoerd. Zou dit al moeten werken? want ik krijg nu zonder een e-mail adres toch een succesmelding.

**Comment by rjzondervan** [comment]
Ik heb op dit moment voor testdoeleinden tijdelijk de beschreven bypass gemaakt. Ik zal even een nieuw issue aanmaken dat het indienen zonder e-mail adres geblokkeerd moet worden ;).

**Comment by JeroenduC** [comment]
Super! Wat mij betreft dan okay.

**Comment by JeroenduC** [comment]
Top. Op done gezet.
