### ISSUE TITLE
Als beheerder wil ik gebruikersautorisaties kunnen inrichten

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#494]
zodat medewerkers alleen de applicatiefuncties kunnen uitvoeren die bij hun rol hoort.

Concreet gaat het om het kunnen definieren van de rollen. Het toekennen van rollen is al gerealiserd in: #335 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by CMasselink** [comment]
Op voorstel van team Prio hoog. @RickWildHoorn  eens?

**Comment by RickWildHoorn** [comment]
> Op voorstel van team Prio hoog. @RickWildHoorn eens?

Eens!

**Comment by rubenvdlinde** [comment]
Eerste (werkende) schermen zijn er, dus lijkt me een kwestie van itereren en doen.

**Comment by CMasselink** [comment]
Er is al een hoop gerealiseerd. Granulariteit moet gecheckt worden.
