### ISSUE TITLE
Als Scrumteam willen we het huwelijksproces in BPMn vast gelegd hebben

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#5]
zodat het proces duidelijk is voor de software ontwikkelaars en gebruik kan worden gemaakt van Camunda process engine.

**Comment by JanWillemKooi** [comment]
Deze is toch al gedaan. Ik verwacht natuurlijk dat naar aanleiding van bijvoorbeeld de UX interviews of demo's of testen dat er aanpassingen zullen volgen. Maar dan maken we op dat moment een nieuwe user story met: aanpassingen aan het BPMn proces over zus-en-zo. @MichelleDautzenberg Kunnen we deze morgen afsluiten bij de demo? Als de techniekmensen er bij kunnen dan is dit volgende mij voldoende. Jij hebt toch alles tot nu toe kunnen verwerken?

**Comment by MichelleDautzenberg** [comment]
Ja, volgens mij kan deze gesloten.
