### ISSUE TITLE
Als medewerker wil ik inzage in de Babs-agenda

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#50]
definitief/onder optie, filterbaar per Babs

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by CMasselink** [comment]
@rubenvdlinde Deze staat op de backlog maar volgens mij is deze in progress? Elementen hiervan zijn in ieder geval al gerealiseerd. definitief/onder optie missschien nog niet.

**Comment by MichelleDautzenberg** [comment]
Dubbel met #424 Daarom gesloten.
