### ISSUE TITLE
Als procesteam wil ik uitzoeken wat we kunnen doen om een no-show bij gratis, flits en eenvoudig huwelijk te voorkomen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#505]
zodat we hier in de huwelijksplanner rekening mee kunnen houden.
Nu wordt bijvoorbeeld bij deze plechtigheden het direct maken van de melding verplicht gemaakt, zodat de drempel was hoger is. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by RickWildHoorn** [comment]
Bijvoorbeeld:
- Kosteloze voltrekkingen: Wijzigingskosten.
Mag dit? Wil je dit?

- Andere voltrekkingen: betalen voor X moment.
Los van extra's als een trouwboekje etc. (mag later ook nog wijzigen).

- Reminders om te voorkomen dat men 'vergeet' te annuleren.
Doen we al (voldoende)?
