### ISSUE TITLE
Als procesteam willen we uitzoeken of de melding ongeldig wordt bij het wisselen van de plechtigheid

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#507]
zodat we weten of bij wijziging van de plechtigheid ook de melding opnieuw gedaan moet worden.
Volgens BS-expert Bas uit UTrecht wel. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by RickWildHoorn** [comment]
Hoorn heeft een digitaal formulier waar op staat 'huwelijk/geregistreerd partnerschap'. Op het formulier wordt dus geen onderscheid gemaakt. Voordeel hiervan is dat er geen issue is bij het wijzigingen van huwelijk in partnerschap of vice versa.

Ik heb voor de zekerheid bij de kwaliteitsmedewerker nagevraagd of dit wel kan (en mag). Op dat antwoord wacht ik nog.

Ik ben overigens wel benieuwd als iemand in Utrecht bijvoorbeeld 13 dagen vóór de voltrekking (dus te laat voor een 'nieuwe' melding) aangeeft toch een huwelijk te willen i.p.v. een partnerschap. Gaat dan het hele feest niet door?

**Comment by MichelleDautzenberg** [comment]
We moeten ook uitzoeken of de melding ongeldig is als de getuigen veranderen (Want daarvan moet je de namen doorgeven in de melding).

**Comment by RickWildHoorn** [comment]
Advies medewerkers Hoorn:
Als de ceremonie of getuigen veranderen, hoeft er géén nieuwe melding gedaan te worden.
Het moet ook praktisch blijven. De praktijk is dat soms op de dag zelf nog van getuigen gewisseld wordt, daar wordt ook nooit een probleem van gemaakt.

@MichelleDautzenberg 
Kunnen we dit nog met Utrecht checken zodat we een wat groter draagvlak hebben voor deze beslissing? Want eerder had Bas een andere mening?

Alternatief is het op eenzelfde manier oplossing als bij het 'verlengen/vernieuwen' van de melding als de melding verloopt door het naar achter verplaatsen van de datum.

**Comment by MichelleDautzenberg** [comment]
Aan Bas nagevraagd en wij zitten er ook praktisch in. Dus in dat geval laten we de melding gewoon zoals die is.
