### ISSUE TITLE
Als medewerker wil ik inzage in de locatie-agenda

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#51]
definitief/onder optie
filterbaar naar locatie

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by rubenvdlinde** [comment]
Betreft hier in stap 1 dan even de schermen

**Comment by CMasselink** [comment]
@MichelleDautzenberg: is dit dubbel met #339?

**Comment by MichelleDautzenberg** [comment]
Ja klopt, is dubbel. Ik sluit deze.
