### ISSUE TITLE
Als scrumteam wil ik een uitspraak van de PO over het kopietje paspoort

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#517]
zodat ik weet of we dit moeten faciliteren of niet. Het gaat om het identificeren van het bruidspaar en de getuigen op de dag zelf. 

In Utrecht is hier over gesproken binnen BZ en blijft men vasthouden aan het kopietje paspoort. Argument hiervoor is het niet willen verplichten om identiteitsbewijzen mee te moeten nemen op de huwelijksdag. 

Ik wil een uitspraak van de PO wat het uitgangpunt van de HP hierop wordt en dit opnemen in de design decisions (oid). 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by RickWildHoorn** [comment]
Vanuit een procesoogpunt zijn we geen voorstander van het vragen van een kopie. Er wordt immers al met DigiD ingelogd.

Voor de beëdiging bij de rechtbanken is het (helaas) nog wel nodig, dat is wat ons betreft de enige uitzondering.

Aan Kunera gevraagd om hier een uitspraak over te doen.

**Comment by MichelleDautzenberg** [comment]
Aan Kunera voorgelegd. Zij gaat het intern bespreken.

**Comment by matthiasoliveiro** [comment]
Het is naar mijn weten tegen de wet om om een kopie van een ID te vragen. 
Wat me bevreemd is dat BZ op de stoel gaat zitten van het paar, is dit nu juist niet iets voor UX om uit te zoeken wat hier de ruimte is.

**Comment by rubenvdlinde** [comment]
Wie is hier nu de probleem eigenaar @RickWildHoorn ?

**Comment by RickWildHoorn** [comment]
@rubenvdlinde Mijn inziens is dat Kunera.
@MichelleDautzenberg: heb je inmiddels al een reactie van Kunera gehad hierover?

**Comment by matthiasoliveiro** [comment]
Kunera: Niet in mvp of in de trouwplanner.
Mogelijk wel in het proces maar is een zorg voor later.
