### ISSUE TITLE
Als medewerker wil ik inzage in de resultaten van de persoonschecks binnen een reservering

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#52]
zodat ik weet of ik hier nog handmatige checks op moet doen of het gesprek met de inwoner over een resultaat moet aangaan. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by rubenvdlinde** [comment]
@bbrands02 Gaat hier in stap 1 even om de schermen

**Comment by MichelleDautzenberg** [comment]
Waar kan ik dit reviewen?
