### ISSUE TITLE
BUG: vreemde teksten bij starten nieuw verzoek: ingestemd & geen partner

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#530]
**Beschrijving van de bug**
Ajs je inlogt en een nieuw verzoek start, krijg je in de uitleg / checklist wat vreemde teksten:
![image](https://user-images.githubusercontent.com/39768984/77522906-470d9680-6e85-11ea-91ab-cc6f320d8e6d.png)

Er staat dat je zelf hebt ingestemd. Dit is niet relevant. 
Er staat dat je geen partner hebt, dat is wat raar als je wilt trouwen met je partner. 
Ik denk dat hier wordt bedoeld dat je nog geen partner hebt geselecteerd.
Er staat dat je geen familie met jezelf bent, dat is ook wat vreemd

**Wat heb ik gedaan**
Inloggen en nieuw verzoek starten.

**Verwachting**
De juiste info

**Bug**
Beschrijf wat het onverwachte resultaat was?

**Comment by CMasselink** [comment]
Nog even een complete screenshot. Ik kan dit nog steeds reproduceren
![image](https://user-images.githubusercontent.com/39768984/78070417-038ebd00-739c-11ea-8a6d-cc7871a0bf55.png)

**Comment by rubenvdlinde** [comment]
De teskt heeft geen partner is bedoel als check of iemand niet al in een partnerschap zit (wat kind of blocking is voor het huwelijk). Hoe zouden we dat beter kunnen formuleren?

**Comment by matthiasoliveiro** [comment]
@JeroenduC aangezien het om teksten gaat kan jij controleren of het nu voldoende is?

**Comment by JeroenduC** [comment]
@matthiasoliveiro Ik denk dat dit voor nu voldoende is, en dat we het van de gebruikers gaan horen als het echt heel gek overkomt.

**Comment by matthiasoliveiro** [comment]
zie de opmerking van jeroen closed voor nu
