### ISSUE TITLE
Als getuige wil ik kunnen instemmen met een verzoek om getuige te zijn bij een huwelijk

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#535]
zodat het trouwstel weet dat ik inderdaad kan/kom

Benodigde functionaliteit:
Een pagina inclusief login functionaliteit met DigiD waarbij ik kan aangeven of ik wel of niet instem met het verzoek.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Dubbel met #524
