### ISSUE TITLE
Als reeds beëidigde babs van een andere gemeente wil ik kunnen instemmen met een verzoek om Babs te zijn bij een huwelijk

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#536]
zodat ik kan aangeven of ik kan.

Zie ook BPMN proces in processenoverzicht voor hoe dit proces moet lopen.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by CMasselink** [comment]
Openstaande vraag: gaan we naar aanleiding van goedkeuren Babs de zaak starten? Hoe?

**Comment by MichelleDautzenberg** [comment]
NU dubbel met #534 . DIe is uitgebreider, dus ik sluit deze :)
