### ISSUE TITLE
Als medewerker wil ik inzage in mijn openstaande taken

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#54]
zodat ik weet wat ik nog moet doen voor een huwelijk. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by rubenvdlinde** [comment]
@bbrands02 volgensmij hoort deze thuis in de slag die je nu aan het maken bent rondom de schermen

**Comment by MichelleDautzenberg** [comment]
DUbbel met #161
