### ISSUE TITLE
Ondanks dat ik een uitgebreid huwelijk heb gekozen, krijg ik een melding dat ik geen trouwambtenaar mag kiezen.

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#558]
**Beschrijving van de bug**
Ondanks dat ik een uitgebreid huwelijk als plechtigheid heb gekozen, krijg ik een melding dat ik geen ambtenaar mag kiezen als ik op een ambtenaar klik nadat ik eerder al een keer een ambtenaar gereserveerd had.
![image](https://user-images.githubusercontent.com/39768984/78072938-376be180-73a0-11ea-84dc-725f8cab9ae1.png)

**Wat heb ik gedaan**
Log in. kies een uitgebreid huwelijk bij plechtigheid, selecteer de eerste trouwambtenaar, reserveer deze ambtenaar, voeg getuigen toe, kies een locatie, ga later weer terug naar het ambtenaren overzicht en klik weer op de ambtenaar die je origineel had gekozen

**Verwachting**
De melding dat je de betreffende ambtenaar al gereserveerd hebt.

**Bug**
Een melding dat je de ambtenaar niet mag kiezen omdat je ceremonie/plechtigheid dit niet toe zou laten, terwijl je een uitgebreid huwelijk hebt gekozen.

**Comment by rjzondervan** [comment]
Hier zat een kleine templatefout. Kan jij bevestigen dat dat verholpen is, @CMasselink?

**Comment by CMasselink** [comment]
Is opgelost

**Comment by CMasselink** [comment]
Opgelost
