### ISSUE TITLE
Als inwoner wil ik (in ieder geval) getuigen en extra's op een later moment kunnen toevoegen aan mijn reservering

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#56]
zodat ik wel de locatie, babs en datum kan vastleggen, maar getuigen en extra's nog wat langer over kan nadenken. 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by CMasselink** [comment]
Wordt al opgelost met #87
