### ISSUE TITLE
Als inwoner wil ik ook zonder Digid instemming kunnen geven

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#57]
Getuigen, partners hebben niet altijd Digid (want bijv. buitenlands). Dan kunnen de persoonschecks ook niet automatisch uitgevoerd worden, maar zal dit handmatig moeten gebeuren. 

Dit moet leiden tot:
- veilig digitaal kunnen verzenden van documenten door de instemmer
- een handmatige controle van de documenten door de medewerker, waarna het resultaat door de medewerker vast te leggen moet zijn in de huwelijksplanner.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by CMasselink** [comment]
Deze user story is gerelateerd aan #100 en #59

**Comment by rubenvdlinde** [comment]
Voor online instemming zal altijd digid nodig zijn, maar er zijn ook issues voor het kunnen geven van instemming aan de balie.

**Comment by MichelleDautzenberg** [comment]
Klopt. Dan moet alleen wel nog in de instemmingsmail worden opgenomen dat dit ook aan de balie kan.

**Comment by CMasselink** [comment]
Deze userstory wordt verder opgepakt in #484
