### ISSUE TITLE
Als procesteam wil ik in een proces vastleggen wat er gebeurt als een instemmer geen Digid heeft

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#58]
#57 
Uitzoeken hoe dit op te lossen.
Persoonschecks kunnen dan niet automatisch uitgevoerd worden, dus iemand zal dan langs de balie moeten komen. 

Getuigen, partners hebben niet altijd Digid (want bijv. buitenlands). Dan kunnen de persoonschecks ook niet automatisch uitgevoerd worden, maar zal dit handmatig moeten gebeuren.

Let op:
- [ ] duidelijke beschrijving wat moet gebeuren
- [ ] gekoppeld aan een persoon (assign)
- [ ]  gekoppeld aan een user story (door # en het nummer toe te voegen)

**Comment by MichelleDautzenberg** [comment]
Dit valt buiten scope van de MVP, dus gaan we nu niet uitgebreid op in. Dit wordt afgedicht aan de voorkant van de huwelijksplanner (Bv door een waarschuwing).

Wat hebben wij er nu mee gedaan:
- In MVP procesmodel is hier een opmerking over opgenomen. 
- We hebben wel userstories toegevoegd vanuit medewerker om een reservering handmatig vast te kunnen leggen.

**Comment by JanWillemKooi** [comment]
Het lijkt me dat als er iets in het proces gebeurd wat niet is geautomatiseerd, dat er dan een opmerking op het scherm komt met iets van : 'We kunnen uw huwelijk helaas niet helemaal automatisch afhandelen. Neem contact op met de gemeente door te bellen/ emailen/ afspraak maken etc.". Is het mogelijk om vanuit het UX en Procesteam hier een goede tekst voor te maken?

**Comment by MichelleDautzenberg** [comment]
Ik sluit deze, want dubbel met #232
