### ISSUE TITLE
Bij veel bewerk pagina's van de commonground dashboard krijg ik dezelfde bug

### ISSUE THREAD

**Issue by SamiJamal** [VNG-Realisatie/huwelijksplanner#580]
**Beschrijving van de bug**
Ik was op het messages component en ik wou een message bewerken, ik klikte op bewerken en toen kreeg ik deze foutmelding.

**Wat heb ik gedaan**
Als je naar messages gaat en een bericht wil bewerken krijg je een foutmelding.

**Verwachting**
Ik wil dat als ik op het bewerkscherm klik gegevens kan bewerken.  

**Bug**
![Schermopname (16)](https://user-images.githubusercontent.com/42804026/78875591-69d7a780-7a4e-11ea-9348-8499063d0835.png)

**Comment by rubenvdlinde** [comment]
Deze is gerelateerd aan #556 dus gaan we even opnieuw inplannen ná pasen

**Comment by rubenvdlinde** [comment]
Dit had te maken met dat het ophalen van loging een 201 gaf ipv, dit is nu bijgewerkt op alle componenten
