### ISSUE TITLE
Op de demo opgeving geeft het opslaan van contactgegevens op de partner pagina een error 500

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#584]
**Beschrijving van de bug**
Bij het opslaan van een email adres van de ingelogde persoon, "uw contactgegevens", leidt dit tot een error 500
![image](https://user-images.githubusercontent.com/39768984/79270992-5f2e6f80-7e9f-11ea-9003-9bcfd46f5b1a.png)
LET OP: dit is op de demo omgeving. Op Dev kon ik geen verzoek starten, dus daar niet getest.

**Wat heb ik gedaan**
Inloggen.
Ceremonie kiezen
Naar de partner pagina. Email adres invullen zoals in bovenstaande afbeelding.
Op opslaan drukken

**Verwachting**
Opgeslagen email adres

**Bug**
Error 500

**Comment by rjzondervan** [comment]
Hoi Constantijn,

@matthiasoliveiro en ik hebben deze bug vanochtend geprobeerd te reproduceren, maar dat is ons niet gelukt. Zou jij kunnen hertesten of deze bug nog steeds op de demo-omgeving aanwezig is, en zo ja, mij even heel precies mee willen nemen in de stappen die je zet?

**Comment by CMasselink** [comment]
@rjzondervan Ik kan het zelf ook niet meer reproduceren, ik gok dat het bij een recente deploy is opgelost
