### ISSUE TITLE
Ambtenaren pagina op dev is stuk

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#585]
**Beschrijving van de bug**
Klikken op de ambtenaren pagina geeft een foutmelding.
![image](https://user-images.githubusercontent.com/39768984/79306538-b0694e00-7ef5-11ea-9d76-3b5da81d5acd.png)

**Wat heb ik gedaan**
Klik op de ambtenaren pagina op dev

**Verwachting**
Ambtenaren pagina

**Bug**
Foutmelding

**Comment by rjzondervan** [comment]
Vooralsnog lijkt deze pagina terug online, ik heb alleen geen idee wat er mis gegaan is, dus laat het even weten als hij alsnog kapot valt, @CMasselink

**Comment by CMasselink** [comment]
Dit werkt weer.

**Comment by CMasselink** [comment]
Done, werkt
