### ISSUE TITLE
Op DEV: Na inloggen kan je geen nieuw verzoek starten of aan een bestaand verzoek verder werken

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#586]
**Beschrijving van de bug**
Na inloggen kom je op een lege pagina zonder knoppen / mogelijkheid om een verzoek te starten / hervatten.
![image](https://user-images.githubusercontent.com/39768984/79306944-60d75200-7ef6-11ea-9b1f-9c614f2ad861.png)

**Wat heb ik gedaan**
Inloggen
Proberen een verzoek te starten

**Verwachting**
Mogelijkheid een nieuw verzoek te starten of een verzoek te hervatten

**Bug**
Lege pagina

**Comment by rjzondervan** [comment]
Dit werd veroorzaakt door een storing in het VTC, dit component is inmiddels weer online. @CMasselink kan jij bevestigen dat het probleem verholpen is?

**Comment by CMasselink** [comment]
Verzoeken starten werkt weer

**Comment by CMasselink** [comment]
Opgelost, ook in demo
