### ISSUE TITLE
Als medewerker wil ik handmatig het resultaat van de persoonschecks kunnen vastleggen in de reservering

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#59]
zodat alle informatie op één plek blijft staan. Ook als bepaalde dingen handmatig zijn gebeurd. 
Zie ook #57 

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by CMasselink** [comment]
Dit wordt opgelost vanuit de userstory waarbij een medewerker een melding kan doen namens de burger (of deze aan kan passen)
