### ISSUE TITLE
Ux team wil kunnen resteten op de demo omgeving

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/huwelijksplanner#593]
Dit issue is naar aanleiding van de demo review afgelopen vrijdag tussen @JeroenduC @rubenvdlinde en @matthiasoliveiro 

Mag via een slack bericht

**Comment by rjzondervan** [comment]
@JeroenduC Ik denk dat het 't handigste is als we afspreken dat we dit via een slackbericht doen. Dit inregelen via een knop wordt best complex.

Op termijn zouden we wel kunnen nadenken over een stagingomgeving die elke nacht om 2 uur wordt gereset, maar het is de vraag of dat op de demo-omgeving wenselijk is.

**Comment by JeroenduC** [comment]
Wat mij betreft helemaal okay. Als we dan van te voren even een contactpersoon afspreken die Slack in de gaten houdt en die we mogen bellen als dat even niet lukt (backup), dan helemaal in orde.

**Comment by JeroenduC** [comment]
@rjzondervan Mag wat mij betreft op Done, als jij het er ook mee eens bent.

**Comment by rjzondervan** [comment]
Wat mij betreft akkoord. Ik denk dat het 't handigste is als ik in principe degene ben die de resets doet.
