### ISSUE TITLE
Als inwoner wil ik mijn naamgebruik ook direct via de huwelijksplanner kunnen doorgeven

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#61]
zodat ik dit niet apart hoef te doen. 
(Dit dient juridisch wel te leiden tot een apart verzoek.)

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

**Comment by rubenvdlinde** [comment]
@rjzondervan volgensmij hebben we deze inmiddels opgepakt via een ander issue, zou je dat even kunnen checken en hem dan naar review zetten?

**Comment by rjzondervan** [comment]
Dit is inderdaad via een ander issue al doorgevoerd. Daarom naar Review

**Comment by MichelleDautzenberg** [comment]
Is het mogelijk om ipv de tekstuele beschrijving ("eerst uw eigen achternaam...") ook de opties met de  daadwerkelijke namen te laten zien? 
Dus bijv:
- Anita Henrika de Kieft
- Anita Henrika De Kieft - Dekker
- Anita Henrika Dekker - de Kieft
-  Anita Henrika Dekker

**Comment by matthiasoliveiro** [comment]
Dat kan maar is wel een andere Userstory. Als ik het zo even bekijk is het niet heel erg veel werk. Maar ik duik er even in!

**Comment by MichelleDautzenberg** [comment]
OK, ik maak een nieuw issue aan voor de aanpassing.
