### ISSUE TITLE
DEV: Na het kiezen voor een gratis of eenvoudig huwelijk worden de locatie en trouwambtenaar niet meer automatisch ingevuld/afgevinkt.

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#611]
**Beschrijving van de bug**
- Na het kiezen voor een gratis of eenvoudig huwelijk worden de locatie en trouwambtenaar niet meer automatisch ingevuld/afgevinkt. Eerder gebeurde dit wel. 

**Wat heb ik gedaan**
Als ik als ceremonie een gratis of eenvoudig huwelijk kies, 

**Verwachting**
Dat locatie en trouwambtenaar automatisch een vinkje krijgen en dat bij die stappen te zien is wat en waarom daar gekozen voor mij is.

**Comment by matthiasoliveiro** [comment]
Issue is er nog steeds Hertest NOK
