### ISSUE TITLE
Dev: kan een trouwabtenaar en locatie reserveren zonder dat ik een datum heb gekozen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#622]
**Beschrijving van de bug**
Ik kan nu een trouwambtenaar reserveren zonder een datum te hebben gekozen. Dan weet de ambtenaar en de Babs-agenda ook niet wanneer de reservering van toepassing is. 

**Wat heb ik gedaan**
Gestart met een leeg verzoek. Locatie gereserveerd. Trouwambtenaar gereserveerd. 

**Verwachting**
Dat er stond dat ik eerst een datum moest kiezen.

**Comment by matthiasoliveiro** [comment]
Dit is "by design" het kan namelijk zo zijn dat je wel al een locatie en ambtenaar hebt maar nog geen datum hebt. Je moet dan de reservering eigenlijk zien als een selectie (de datum die je nu zou kunnen kiezen is de enige datum waar de locatie en de ambtenaar kan).

**Comment by MichelleDautzenberg** [comment]
Ok, dan sluit ik deze. Bij testen horen we wel weer of dit duidelijk is voor de inwoner.
