### ISSUE TITLE
Sub verzoek aanvragen eigen babs loopt vast

### ISSUE THREAD

**Issue by matthiasoliveiro** [VNG-Realisatie/huwelijksplanner#628]
Als je een eigen babs wilt aanvragen kom je in een sub verzoek. Als je na het invullen van de gegevens weer terug wil kan dit niet.

**Comment by matthiasoliveiro** [comment]
moet een bug zijn

**Comment by rubenvdlinde** [comment]
Moet moet moet niet zo dwingend hé ;)

Komt ook omdat de overige pagina kapot is
