### ISSUE TITLE
User Story's komen niet op het Scrumboard.

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#65]
# Impediment

Als ik in issue een User Story aanmaak, komt dit niet automatisch op het Scrumboard terecht.

**Comment by JanWillemKooi** [comment]
NIEUWE USER STORY’s
-	Ik zie veel nieuwe User Story’s. Heel goed! Ze waren alleen niet gekoppeld aan een project. En dan verschijnen ze niet op het Scrumboard. Ik heb dat nu voor alle user story’s gedaan en ze allemaal (in willekeurige volgorde) in de Project Backlog gezet. Als je dit voortaan zelf wil kunnen (graag!) dan zijn er 2 handelingen die je moet doen:

1.	Bij het opstellen, het issue koppelen aan het project. Er is maar 1 project dus dat kan niet missen. Aan de rechterkant, onder Labels, doe je dit door bij Projects op “Scrumbord Huwelijksplanner” te klikken (onderste rode pijl). 
  
2.	Bij het Scrumboard (bovenaan bij Projects) en daarna Scrumboard Huwelijksplanner.
 
Als je een nieuw issue hebt aangemaakt, komt deze in Triage te staan. Dat kan je hier op het Scrumboard zien aan de rechterkant, bij de blauw stip (Add card (New).

Als je er op klikt, komt je issue in beeld en kan je deze naar een kolom slepen. Je kan je issue in elke kolom zetten maar het is de bedoeling dat deze eerst op in de kolom ‘Product backlog’ komt te staan. Let even op de volgorde. Belangrijke issue’s bovenaan. Uiteindelijk is de Product Owner verantwoordelijk voor de volgorde, maar jullie mogen gerust meedenken 😊

**Comment by jwkooi** [comment]
De tips hierboven zijn geschikt voor de Definition of Ready
