### ISSUE TITLE
EPIC: Als developer & architect wil ik dat de huwelijksplanner de common ground architectuur volgt

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#66]
Zodat de huwelijksplanner componenten herbruikbaar en eenvoudig deelbaar zijn met andere gemeenten.

**Comment by JanWillemKooi** [comment]
Is dit wel een user story of meer een soort DoD voor andere user story's? En zo ja, waar staat de DoD voor technisch componenten?

**Comment by JanWillemKooi** [comment]
Deze Epic hang (o.a.) samen met: #221 (en alle US daarin genoemd #235, #236, #237, #238, #239, #240) en met #68

**Comment by CMasselink** [comment]
Deze userstory voegt op zichzelf geen waarde meer toe. 
Common ground archtiectuur wordt label.
