### ISSUE TITLE
Als architect wil ik alle componenten op het 5 lagen model geplot hebben

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#67]
zodat ik inzicht heb in welke componenten er zijn en hoe ze gebruikt worden.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

Gerelateerd aan #66

**Comment by JanWillemKooi** [comment]
Ik zie op laag 4 en 5 nog helemaal geen componenten in het overzicht wat vaak wordt gedeeld. 
Is dit eigenlijk 1 grote applicatie? Als het al modulair is opgebouwd, is er een overzicht van de componenten of modules?

**Comment by JanWillemKooi** [comment]
Laag 4 en 5 zijn verweven. Er is nog geen sprake van losse componenten. Het is wel nodig om laag 4 en 5 te splitsen zodat ook een andere voorkant (bijvoorbeeld MijnApp) gebruikt kan worden. De beslissing om dit al te doen voor de MVP en hoe we dit dan gaan doen hangt samen met de uitkomst van #68

**Comment by rubenvdlinde** [comment]
@CMasselink tot in hoever is deze dubbel met #275 ?

**Comment by CMasselink** [comment]
Is inderdaad dubbel
