### ISSUE TITLE
Als techniekteam willen we de huidige code stabiliseren en in een gezamelijk bereikbare repository zetten 

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#69]
zodat de code base duidelijk is en we effectief kunnen ontwikkelen.

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [x] Voeg alle taken die nodig zijn voor de user story toe.

TAKEN:
- [ ] Code van Convenant Gemeente is overgezet
- [ ] Hosting Convenant Gemeente bij VNG is weer vrijgegeven
- [ ] Code van Conduction is overgezet
- [ ] Rechten voor leden Teamtechniek staan goed en iedereen weet hoe code te commiten etc.

**Comment by JanWillemKooi** [comment]
Vraag: we hebben het gehad over een GitHub voor Codeontwikkeling. Hebben jullie deze al opgezet? Kan dan een taak worden in deze US of zullen we een nieuwe US hiervoor aanmaken?

**Comment by JanWillemKooi** [comment]
Kloppen de taken in de header? Is daar al voortgang op?

**Comment by rubenvdlinde** [comment]
Er is een aantal openbare repro's, wij zijn die u aan het opschonen en gaan een overzicht daarvan in de algemene readme zetten zodat iedereen ze kan terugvinden. Verwachting is dat we dat nog voor morgen ochtend 10:00 gaan redden :)

**Comment by JanWillemKooi** [comment]
Deze user story staat nog in progress. Wat moet er nog gebeuren?

**Comment by matthiasoliveiro** [comment]
Er loopt nu een discussie wanneer de code naar welke repo moet worden opgeleverd. Constantijn is hier met het implementatie team mee over in gesprek.

**Comment by JanWillemKooi** [comment]
Is dit discussie inmiddels afgerond?

**Comment by CMasselink** [comment]
Contact gehad met o.a. Patrick: als we voldoende rechten kunnen krijgen, de repository's verplaatsen naar de VNG. Mochten rechten een probleem zijn, kunnen we ze bij Utrecht zetten. 
Verplaatsen alleen als het niet meer dan ongeveer 2 uur werk is.

**Comment by matthiasoliveiro** [comment]
Afspraak met Constantijn gemaakt we leveren elk component op (na de wasstraat) wanneer akkoord bij review naar de Utrecht repo's.

**Comment by matthiasoliveiro** [comment]
Dit issue kan afgesloten worden het is namelijk toegevoegd aan de WoW
