### ISSUE TITLE
Als productowner wil ik alle 'oude' userstories van zowel Utrecht als Convenantgemeenten doorlopen om te beoordelen welke in het nieuwe project moeten worden overgenomen

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/huwelijksplanner#73]
zodat .....
we de kennis uit de voorgaande projecten behouden.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by CMasselink** [comment]
Userstories krijgen we via de processen. Dit is niet meer nodig.
