### ISSUE TITLE
Als productowner wil ik een demo en presentatie van de huwelijksplanner beschikbaar hebben voor de Common Ground bijeenkomst op 12 november

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/huwelijksplanner#75]
zodat .....
We de bezoekers goed kunnen informeren over de waarde van ons product en laten zien hoe ver we al zijn.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by JanWillemKooi** [comment]
zie ook #20

**Comment by JanWillemKooi** [comment]
Deze user story is speciaal voor het netwerkbijeekomst 'Samen organiseren'van 12 nov. User story #20 gaat ook over bruikbaarheid voor anderen zoals de UX-ers

**Comment by JanWillemKooi** [comment]
Bijeenkomst is geweest. Demo app was beschikbaar. Wel veel crashes die verklaart werden door infrastructurele oorzaken (was een development omgeving)
