### ISSUE TITLE
Als product owner wil ik de doelbinding vast kunnen leggen bij gegevensbevragingen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#77]
zodat we ons hier over kunnen verantwoorden.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by JanWillemKooi** [comment]
Wie pakt deze user story op? In welke expertise groep of groepen zou dit vallen? En is dit iets waar we ons nu druk over moeten maken?

**Comment by rubenvdlinde** [comment]
@JanWillemKooi dit is een lopend ding over het cg landschap en speelt bijvoorbeeld ook bij de zgw api's .

Het is een technisch/architecturaal ding waar in ieder geval de techniek groep het over moet hebben.

**Comment by rubenvdlinde** [comment]
Dit komt NLX gericht mee met #274 maar werkt ook zonder

**Comment by rubenvdlinde** [comment]
Dit is nu op de achtergrond geregeld, dus het zou mijn voorkeur hebben om komende sprint uit te schrijven hoe deze getest kan worden zodat we hem kunnen afronden.

**Comment by rubenvdlinde** [comment]
Vraag is even willen we dit weergeven in de logs

**Comment by rubenvdlinde** [comment]
Kan dus gewoon een colom zijn in de bevragingen logs (for now)

**Comment by RickWildHoorn** [comment]
Dubbel met #127
