### ISSUE TITLE
Als architect / developer wil ik onderzoeken of een BPMN procesengine van toegevoegde waarde is voor de huwelijksplanner

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#79]
Beschrijving van de taak:

Let op:
- [ ] duidelijke beschrijving wat moet gebeuren
- [ ] gekoppeld aan een persoon (assign)

Als een taak wel bij een user story hoort, dan deze taak daar (bij de beschrijving van de user story) opnemen.

**Comment by matthiasoliveiro** [comment]
Is dit niet juist iets waar de proces mensen ook iets van moeten vinden?

**Comment by JanWillemKooi** [comment]
Deze user story is overlappend met #68

**Comment by CMasselink** [comment]
gesloten: dubbel
