### ISSUE TITLE
Als klant wil ik een trouwambtenaar kunnen selecteren reserveren voor mijn huwelijk

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#82]
zodat ik enige zekerheid heb dat mijn voorkeurstrouwambtenaar ons gaat trouwen

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Dubbel met EPIC #173
