### ISSUE TITLE
Als koppel willen we een trouwlocatie kunnen reserveren

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#83]
zodat we op die locatie kunnen trouwen

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Dubbel met Epic #174
