### ISSUE TITLE
Als UX-designer wil ik de gemaakte proto-personakoppels gedigitaliseerd hebben zodat ik deze makkelijk kan delen, bewerken en uitbreiden.

### ISSUE THREAD

**Issue by JeroenduC** [VNG-Realisatie/huwelijksplanner#9]
- [ ] Done: Alle vier de personakoppels zijn gedigitaliseerd en gedeeld  met het team.

**Comment by JanWillemKooi** [comment]
Kunnen jullie hier iets meer voortgang laten zien door bijvoorbeeld een hyperlink naar het document met persona's ?

**Comment by JanWillemKooi** [comment]
Alle informatie rond persona's is hier: 
https://github.com/VNG-Realisatie/huwelijksplanner/tree/master/documenten/gebruikersonderzoek/personas
