### ISSUE TITLE
Als gemeente wil dat een huwelijk aanvraag resulteert in een zaak

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#91]
zodat de aanvraag zaakgericht afgehandeld kan worden en de burger de lopende zaak in zijn PIP / Mijn gemeente pagina terug kan zien.

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Als we dit door Camunda laten uitvoeren, dan kunnen we hiervoor de Camunda Worker gebruiken die Sergei heeft gemaakt. Dan hoef ik alleen een external task in het BPMN-proces op te nemen en regelt de Camunda Worker de rest.

**Comment by MichelleDautzenberg** [comment]
We hebben besloten dat er zaken worden gemaakt van de melding, aanvraag eigen babs en aanvraag eigen locatie. Voor de huwelijksreservering wordt er een verzoek aangemaakt.
