### ISSUE TITLE
Als developer wil ik instemmingen kunnen aanmaken zonder contact gegevens

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#98]
zodat .....

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by CMasselink** [comment]
@rubenvdlinde zou jij deze userstory wat concreter kunnen maken? Ik snap nu niet zo goed wat je hier mee bedoelt.

**Comment by rubenvdlinde** [comment]
In het verleden was het zo dat een instemming altijd contact gegevens nodig had, maar bij bijvoorbeeld het doorgeven van de laptop heb je die niet.

Overigens hebben we dit volgensmij inmiddels al aangepast. @rjzondervan kan jij dit controleren en indien correct het issue naar review zetten?

**Comment by rjzondervan** [comment]
De code geeft nu inderdaad de mogelijkheid om assents zonder contactgegevens aan te maken.

**Comment by CMasselink** [comment]
@rjzondervan Hoe kan ik dit reviewen?

**Comment by rjzondervan** [comment]
Lastig, al is dit technisch mogelijk, in de frontend wordt het als het goed is niet toegelaten, wat het heel moeilijk reviewen maakt zonder de assents in postman aan te maken.

**Comment by CMasselink** [comment]
Het contactobject in de API spec is in ieder geval niet als verplicht aangemerkt. Ik sluit dit issue
